subfolders
Improved experience for subfolders.

diff --git a/usr/httpauth b/usr/httpauth
--- a/usr/httpauth
+++ b/usr/httpauth
@@ -9,7 +9,16 @@ source /opt/webinoly/lib/general
 check_for_parameters $@
 api-events_update has
 
+
+# Only these commands are supported with subfolders
+if [[ -n $subfolder && -z $wp_admin && -z $path ]]; then
+	echo "${red}[ERROR] Subfolder option not supported!${end}"
+	exit 1
+fi
+
+
 [[ -z $empty_param && -z $h && -z $H && -z $help ]] && ! [[ -n $wp_admin && -z $domain ]] && check_for_nginx -ask
+
 
 # Check for domain.
 if [[ -n $domain && -f /etc/nginx/sites-available/$domain ]]; then
diff --git a/usr/log b/usr/log
--- a/usr/log
+++ b/usr/log
@@ -19,8 +19,11 @@ waiting_for_log() {
 }
 
 
-# Logs are for the entire domain, except when WP is in subfolder we need it to set the especific wp-config file.
-[[ -n $subfolder && -z $wp ]] && echo "${red}${dim}[WARNING] The subfolder parameter will be ignored!${end}"
+# Only these commands are supported with subfolders
+if [[ -n $subfolder && -z $wp ]]; then
+	echo "${red}[ERROR] Subfolder option not supported!${end}"
+	exit 1
+fi
 
 
 # Check for custom "lines" value
@@ -326,7 +329,7 @@ elif [[ -n $domain && -f /etc/nginx/sites-available/$domain ]]; then
 		fi
 		
 	elif [[ -n $wp ]]; then
-		echo "${red}[ERROR] WordPress configuration file not found!${end}"
+		echo "${red}[ERROR] Please, enter a valid WP site! ${dim}(${domain}${subfolder})${end}"
 		exit 1
 	
 	# Access and error logs
diff --git a/usr/webinoly b/usr/webinoly
--- a/usr/webinoly
+++ b/usr/webinoly
@@ -13,6 +13,13 @@ check_for_parameters $@
 api-events_update wys
 
 
+# Only these commands are supported with subfolders
+if [[ -n $subfolder && -z $clear_cache && -z $backup ]]; then
+	echo "${red}[ERROR] Subfolder option not supported!${end}"
+	exit 1
+fi
+
+
 if [[ -n $update ]]; then
 	api-events_update wy1
 	webinoly_update
