wp debug
WP debug log now can be displayed from a parked site, not only from the main site.

diff --git a/usr/log b/usr/log
--- a/usr/log
+++ b/usr/log
@@ -332,9 +332,23 @@ elif [[ -n $domain && -f /etc/nginx/sites-available/$domain ]]; then
 		elif [[ $wp != "true" ]]; then
 			echo "${red}[ERROR] Invalid value for WP parameter!${end}"
 			exit 1
-		elif [[ -f /var/www/$domain/htdocs$subfolder/wp-content/debug.log && $iswpdeb == "true" ]]; then
+			
+		elif [[ $iswpdeb == "true" && -f /var/www/$domain/htdocs$subfolder/wp-content/debug.log ]]; then
 			[[ ! -s /var/www/$domain/htdocs$subfolder/wp-content/debug.log ]] && waiting_for_log
 			sudo tail -f --lines=$clines /var/www/$domain/htdocs$subfolder/wp-content/debug.log
+		
+		elif [[  $iswpdeb == "true" && $(is_parked $domain) == "true" ]]; then
+			maindom=$(grep 'root ' /etc/nginx/sites-available/$domain | cut -d '/' -f 4 -s)
+			
+			if [[ ! -f /var/www/${maindom}/wp-config.php ]]; then
+				echo "${red}[ERROR] Parked main WP domain not found!${dim} (${maindom})${end}"
+				exit 1
+			fi
+			
+			echo "${blu}${dim}WP Debug Log from main site (${maindom})${end}"
+			[[ ! -s /var/www/$maindom/htdocs/wp-content/debug.log ]] && waiting_for_log
+			sudo tail -f --lines=$clines /var/www/$maindom/htdocs/wp-content/debug.log
+		
 		elif [[ $iswpdeb != "true" ]]; then
 			echo "${red}[ERROR] WordPress Debug Mode is not enabled!${end}"
 			exit 1
