cloning
Better check when cloning sites, should be the same type, and only html, php and wp.

diff --git a/usr/site b/usr/site
--- a/usr/site
+++ b/usr/site
@@ -371,8 +371,11 @@ elif [[ -n $clone_from ]]; then
 	elif [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $(is_subfolder $domain $subfolder) != "false" && $overwrite != "on" ]]; then
 		echo "${red}[ERROR] Subfolder ${blu}'$subfolder'${red} already exists!${end}"
 		exit 1
-	elif [[ $(is_parked $clone_from) == "true" ]]; then
-		echo "${red}[ERROR] Cloning a parked site is not allowed!${end}"
+	elif ! [[ $(site_type $clone_from) =~ ^(HTML|PHP|WordPress)$ ]]; then
+		echo "${red}[ERROR] Only HTML, PHP or WordPress sites are supported for cloning!${end}"
+		exit 1
+	elif [[ $overwrite == "on" && -f /etc/nginx/sites-available/$domain && $(site_type $clone_from) != $(site_type $domain) ]]; then
+		echo "${red}[ERROR] Source and destination sites should be the same type of site!${end}"
 		exit 1
 	fi
 	
