subfolders
Now we can create a new site conf in /one when is empty, even when /one/two exists.

diff --git a/usr/site b/usr/site
--- a/usr/site
+++ b/usr/site
@@ -126,10 +126,11 @@ if [[ -n $delete_all ]]; then
 elif [[ -n $mysql || ( -n $php && -n $domain ) ]]; then
 	if [[ -n $domain ]]; then
 		full_empty_not_allowed
-		if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $(is_subfolder $domain $subfolder) != "false" ]]; then
+		if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $(is_subfolder $domain $subfolder) != "false" && $(is_subfolder $domain $subfolder) != "empty" ]]; then
 			echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists!${end}"
 			exit 1
-		elif [[ -n $subfolder ]]; then	
+		elif [[ -n $subfolder ]]; then
+			[[ $(is_subfolder $domain $subfolder) == "empty" ]] && echo "${dim}[INFO] Subfolder already exists, but it's empty!${end}"
 			[[ ! -f /etc/nginx/sites-available/$domain ]] && create_empty_site
 			php_subfolder
 			sudo mkdir -p /var/www/$domain/htdocs$subfolder
@@ -161,7 +162,7 @@ elif [[ -n $empty && -n $domain ]]; then
 elif [[ -n $html && -n $domain ]]; then
 	full_empty_not_allowed
 	if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $(is_subfolder $domain $subfolder) != "false" ]]; then
-		echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists!${end}"
+		echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists! ${dim}(Just put the HTML files in it, a separate conf is not needed)${end}"
 		exit 1
 	fi
 	
@@ -197,8 +198,15 @@ elif [[ -n $wp && -n $domain ]]; then
 		[[ -n $env ]] && sudo site $domain -env=$env
 	else
 		if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $type == [123] && $(is_subfolder $domain $subfolder) != "false" ]]; then
-			echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists!${end}"
-			exit 1
+			# Check if subfolder is empty!
+			if [[ $(is_subfolder $domain $subfolder) == "empty" ]]; then
+				# Install WP in an empty folder!
+				echo "${dim}[INFO] Subfolder already exists, but it's empty!${end}"
+				wpinstall
+			else
+				echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists and it's not empty!${end}"
+				exit 1
+			fi
 		elif [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $type == [123] ]]; then
 			wpinstall
 		else
