subfolder improvements
- fixed some random errors when wp subfolder exists.
- wp subfolder improved.
- fixed php running when main site is html and wp subfolder exists.
- fixed httpauth not working with wp subfolder.
- fixed wp subfolder not working when main site is html.
- readme updated.
- httpauth whitelist improved.
- templates minor improvements.

diff --git a/plugins/httpauth b/plugins/httpauth
--- a/plugins/httpauth
+++ b/plugins/httpauth
@@ -26,8 +26,11 @@ if [[ -n $subfolder && ! ( $subfolder =~ ^\/([A-Za-z0-9_\/\-]+)?[^\/]$ ) ]]; the
 	echo "${red}[ERROR] Please, enter a valid value for subfolder!${end}"
 	exit 1
 fi
-if [[ -n $subfolder && ( -z $wp_admin || -z $domain ) ]]; then
+if [[ -n $subfolder && $(is_wp $domain $subfolder) != "true" ]]; then
 	echo "${red}[ERROR] Subfolder option is only supported for WordPress sites!${end}"
+	exit 1
+elif [[ -n $subfolder && ( -n $domain || -n $wp_admin || -n $path ) && ! -d /var/www/$domain/htdocs$subfolder ]]; then
+	echo "${red}[ERROR] Subfolder not found!${end}"
 	exit 1
 else
 	subname=$(echo $subfolder | sed "s/\//_/g")
@@ -165,11 +168,15 @@ elif [[ -n $whitelist ]]; then
 				if [[ ! -f /etc/nginx/apps.d/whitelist-acl.conf ]]; then
 					sudo touch /etc/nginx/apps.d/whitelist-acl.conf
 					sudo chmod 644 /etc/nginx/apps.d/whitelist-acl.conf
-					sudo chown -R root:root /etc/nginx/apps.d/whitelist-acl.conf
+					sudo chown -R root:root /etc/nginx/apps.d/whitelist-acl.conf	
+					echo "
+allow 127.0.0.1;
+deny all;" >> /etc/nginx/apps.d/whitelist-acl.conf
 				fi
+				
 				exist=$( grep -E "^allow $whitelist;$" /etc/nginx/apps.d/whitelist-acl.conf )
 				if [[ -z $exist ]]; then
-					echo "allow ${whitelist};" >> /etc/nginx/apps.d/whitelist-acl.conf
+					sudo sed -i "1i allow ${whitelist};" /etc/nginx/apps.d/whitelist-acl.conf
 					echo "${gre}The IP address ${blu}'$whitelist'${gre} was successfully whitelisted!${end}"
 				else
 					echo "${gre}IP '$whitelist' is already whitelisted!${end}"
@@ -245,7 +252,7 @@ elif [[ -n $path && -n $domain ]]; then
 				echo "# Path: ${firm}
 location $sign$path {
 	include common/acl.conf;
-	try_files \$uri \$uri/ /index.php\$is_args\$args;
+	try_files \$uri \$uri/ $subfolder/index.php\$is_args\$args;
 }
 # PathEnd" >> /etc/nginx/apps.d/$domain-nginx.conf
 				
diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -111,7 +111,7 @@ if [[ -n $delete_all ]]; then
 # Create PHP site
 elif [[ -n $php && -n $domain ]]; then
 	createsite
-	[[ $(conf_read php-info) != "false" ]] && sudo sed -i '/common\/php.conf/c \	include common/phpinfo.conf;' /etc/nginx/sites-available/$domain
+	[[ $(conf_read php-info) != "false" ]] && sudo sed -i '/common\/php.conf/c \	include common/phpx.conf;' /etc/nginx/sites-available/$domain
 	
 	
 # Create MYSQL site
@@ -127,7 +127,7 @@ elif [[ -n $mysql && -z $domain ]]; then
 # Create HTML site
 elif [[ -n $html && -n $domain ]]; then
 	createsite
-	sudo sed -i '/index/c \	index  index.html index.htm;' /etc/nginx/sites-available/$domain
+	sudo sed -i '/index /c \	index index.html index.htm;' /etc/nginx/sites-available/$domain
 	sudo sed -i '/index/a \	location / { try_files $uri $uri/ =404; }' /etc/nginx/sites-available/$domain
 	sudo sed -i '/php.conf/d' /etc/nginx/sites-available/$domain
 
@@ -141,12 +141,13 @@ elif [[ -n $wp && -n $domain ]]; then
 		[[ $(conf_read yoast-sitemap) == "true" ]] && sudo site $domain -yoast-sitemap=on > /dev/null 2>&1
 	else
 		if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $type == [123] && -d /var/www/$domain/htdocs$subfolder ]]; then
-			echo "${red}[ERROR] Subfolder ${blu}'$subfolder'${red} already exists!${end}"
+			echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists!${end}"
 			exit 1
 		elif [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $type == [123] && ! -d /var/www/$domain/htdocs$subfolder ]]; then
 			wpinstall
 		else
-			createsite
+			echo "${red}[ERROR] Subfolder cannot be created because${blu} $domain ${red}was not found!${end}"
+			exit 1
 		fi
 		
 		wp_subfolder
