httpauth per site
Now we can have http auth per site.

diff --git a/plugins/httpauth b/plugins/httpauth
--- a/plugins/httpauth
+++ b/plugins/httpauth
@@ -3,13 +3,32 @@
 # Http-Authentication Plugin
 # Syntax: httpauth <option> <argument>
 # Options: -add, -delete, -list, -wp-admin, -whitelist
-# Arguments: -raw, -list
+# Arguments: -raw, -list, -site
 
 source /opt/webinoly/lib/general
 check_for_parameters $@
 api-events_update has
 
 [[ -n $add || -n $delete || -n $list || -n $whitelist ]] && check_for_nginx -ask
+
+# Check for site argument.
+if [[ -n $site && -a /etc/nginx/sites-available/$site ]]; then
+	authfile="apps.d/.htpasswd-$site"
+elif [[ -n $site && ! -a /etc/nginx/sites-available/$site ]]; then
+	echo "${red}[ERROR] Site not found!${end}"
+	exit 1
+else
+	authfile=".htpasswd"
+fi
+if [[ ! -a /etc/nginx/$authfile ]]; then
+	if [[ -n $site && ! -d /etc/nginx/apps.d ]]; then
+		sudo mkdir -p /etc/nginx/apps.d
+		sudo chmod 755 /etc/nginx/apps.d
+	fi
+	sudo touch /etc/nginx/$authfile
+	sudo chmod 644 /etc/nginx/$authfile
+	sudo chown -R root:root /etc/nginx/$authfile
+fi
 
 
 if [[ -n $add ]]; then
@@ -33,9 +52,9 @@ if [[ -n $add ]]; then
 		exit 1
 	fi
 	
-	[[ -a /etc/nginx/.htpasswd ]] && exist=$( grep -E "^${user}:" /etc/nginx/.htpasswd )
+	exist=$( grep -E "^${user}:" /etc/nginx/$authfile )
 	if [[ -z $exist ]]; then
-		sudo sh -c "echo -n '$user:$(openssl passwd -1 $pass)\n' >> /etc/nginx/.htpasswd"
+		sudo sh -c "echo -n '$user:$(openssl passwd -1 $pass)\n' >> /etc/nginx/$authfile"
 		echo "${gre}User '$user' has been added successfully!${end}"
 	else
 		echo "${red}[ERROR] Can not create '$user' user because already exist!${end}"
@@ -47,42 +66,49 @@ if [[ -n $add ]]; then
 elif [[ -n $delete ]]; then
 	api-events_update ha2
 	[[ $delete == true ]] && read -p "${blu}HTTP-Auth User: ${end}" userpurge || userpurge=$delete
-	[[ -a /etc/nginx/.htpasswd ]] && exist=$( grep -F "${userpurge}:" /etc/nginx/.htpasswd )
+	[[ -a /etc/nginx/$authfile ]] && exist=$( grep -F "${userpurge}:" /etc/nginx/$authfile )
 	if [[ -z $exist ]]; then
 		echo "${red}[ERROR] User '$userpurge' does not exist!${end}"
 		exit 1
 	fi
-	sudo sed -i "/^$userpurge:/d" /etc/nginx/.htpasswd
+	sudo sed -i "/^$userpurge:/d" /etc/nginx/$authfile
+	
+	# Remove site-auth-file if empty.
+	[[ -n $site && ! -s /etc/nginx/$authfile ]] && sudo rm /etc/nginx/$authfile
+	
 	echo "${gre}User '$userpurge has been deleted successfully!${end}"
 
-		
+	
 elif [[ -n $wp_admin ]]; then
 	api-events_update ha3
-	[[ $(conf_read nginx) == "true" ]] && iswpadon=$( grep -F "acl.conf;" /etc/nginx/common/wpcommon.conf )
-	if [[ $wp_admin == "on" ]]; then
+	[[ $(conf_read nginx) == "true" && -n $site ]] && iswpadon=$( grep -F "wpcommon.conf;" /etc/nginx/sites-available/$site )
+	if [[ $wp_admin == "on" && -n $site ]]; then
 		if [[ -z $iswpadon ]]; then
 			if [[ $(conf_read nginx) == "true" ]]; then
-				sudo sed -i "/\/wp-login\.php/a \include common/acl.conf;" /etc/nginx/common/wpcommon.conf
-				sudo sed -i "/\/wp-admin\/\./a \include common/acl.conf;" /etc/nginx/common/wpcommon.conf
+				sudo sed -i '/wpcommon-noauth.conf/c \	include common/wpcommon.conf;' /etc/nginx/sites-available/$site
 				sudo service nginx reload
 			fi
-			conf_write wp-admin-auth true
-			echo "${gre}WordPress Admin HTTP Authentication has been enabled! ${end}"
+			echo "${gre}WordPress Admin HTTP Authentication for ${blu}- $site -${gre} has been enabled! ${end}"
 		else
-			echo "${gre}HTTP Authentication for WP Admin pages is already enabled! ${end}"
+			echo "${gre}WordPress Admin HTTP Authentication for ${blu}- $site -${gre} is already enabled! ${end}"
 		fi
 	
-	elif [[ $wp_admin == "off" ]]; then
-		if [[ -n $iswpadon || ( -z $iswpadon && $(conf_read nginx) != "true" ) ]]; then
+	elif [[ $wp_admin == "off" && -n $site ]]; then
+		if [[ -n $iswpadon ]]; then
 			if [[ $(conf_read nginx) == "true" ]]; then
-				sudo sed -i "/acl.conf/d" /etc/nginx/common/wpcommon.conf
+				sudo sed -i '/wpcommon.conf/c \	include common/wpcommon-noauth.conf;' /etc/nginx/sites-available/$site
 				sudo service nginx reload
 			fi
-			conf_write wp-admin-auth purged
-			echo "${gre}WordPress admin authentication has been disabled! ${end}"
+			echo "${gre}WordPress Admin HTTP Authentication for ${blu}- $site -${gre} has been disabled! ${end}"
 		else
-			echo "${gre}HTTP Authentication for WP Admin pages is already disabled! ${end}"
+			echo "${gre}WordPress Admin HTTP Authentication for ${blu}- $site -${gre} is already disabled! ${end}"
 		fi
+	elif [[ $wp_admin == "on" ]]; then
+		conf_write wp-admin-auth true
+		echo "${gre}WordPress Admin HTTP Authentication has been enabled! (global)${end}"
+	elif [[ $wp_admin == "off" ]]; then
+		conf_write wp-admin-auth purged
+		echo "${gre}WordPress Admin HTTP Authentication has been disabled! (global)${end}"
 	else
 		echo "${red}[ERROR] Invalid value for wp-admin! ${end}"
 		exit 1
@@ -91,17 +117,17 @@ elif [[ -n $wp_admin ]]; then
 
 elif [[ -n $whitelist ]]; then
 	api-events_update ha4
-	if [[ -z $purge && -a /etc/nginx/common/acl.conf ]]; then
+	if [[ -z $purge && -a /etc/nginx/common/htauth-acl.conf ]]; then
 		if [[ -n $list ]]; then
 			[[ $list == "raw" || -n $raw ]] && echo "" || echo "${blu}"
-			sudo sed -n 's/^allow //p;' /etc/nginx/common/acl.conf | sudo sed -n 's/;$//p'
+			sudo sed -n 's/^allow //p;' /etc/nginx/common/htauth-acl.conf | sudo sed -n 's/;$//p'
 			[[ $list == "raw" || -n $raw ]] && echo "" || echo "${end}"
 		else
 			[[ $whitelist == true ]] && read -p "${blu}IP address to whitelist: ${end}" whitelist
 			if [[ $(ip_check $whitelist) == "true" ]]; then
-				exist=$( grep -E "^allow $whitelist;$" /etc/nginx/common/acl.conf )
+				exist=$( grep -E "^allow $whitelist;$" /etc/nginx/common/htauth-acl.conf )
 				if [[ -z $exist ]]; then
-					sudo sed -i "/deny all;/i \allow ${whitelist};" /etc/nginx/common/acl.conf
+					sudo sed -i "/deny all;/i \allow ${whitelist};" /etc/nginx/common/htauth-acl.conf
 					sudo service nginx reload
 					echo "${gre}The IP address ${blu}'$whitelist'${gre} was successfully whitelisted!${end}"
 				else
@@ -113,11 +139,11 @@ elif [[ -n $whitelist ]]; then
 				exit 1
 			fi
 		fi
-	elif [[ -n $purge && -a /etc/nginx/common/acl.conf ]]; then
+	elif [[ -n $purge && -a /etc/nginx/common/htauth-acl.conf ]]; then
 		[[ $whitelist == true ]] && read -p "${blu}IP address to remove from whitelist: ${end}" whitelist
 		if [[ $(ip_check $whitelist) == "true" ]]; then
 			# https://stackoverflow.com/questions/1797906/delete-using-a-different-delimiter-with-sed
-			sudo sed -i "\#^allow ${whitelist};#d" /etc/nginx/common/acl.conf
+			sudo sed -i "\#^allow ${whitelist};#d" /etc/nginx/common/htauth-acl.conf
 			sudo service nginx reload
 			echo "${gre}The IP address ${blu}'$whitelist'${gre} was successfully removed from whitelist!${end}"
 		else
@@ -132,8 +158,8 @@ elif [[ -n $whitelist ]]; then
 	
 elif [[ -n $list ]]; then
 	echo ""
-	if [[ -a /etc/nginx/.htpasswd ]]; then
-		cat /etc/nginx/.htpasswd | 
+	if [[ -a /etc/nginx/$authfile ]]; then
+		cat /etc/nginx/$authfile | 
 		{
 		while read line
 		do
