commands works without nginx
now some commands can work even if nginx is not installed.
wp-admin, only-error, yoast-sitemap, config-cache.

diff --git a/plugins/httpauth b/plugins/httpauth
--- a/plugins/httpauth
+++ b/plugins/httpauth
@@ -6,17 +6,16 @@ opt=$1
 # Syntax: httpauth <option>
 # Options: -add, -delete, -list, -wp-admin-on, -wp-admin-off, -whitelist, -whitelist-remove
 
-if [[ ! $(conf_read nginx) == "true" ]]; then
-	echo ""
-	echo "${red} NGINX is required to get HTTP Authentication working properly! ${end}"
-	echo ""
-	exit 1
-fi
 
 # Extract value if exist
 if [[ $opt == "-add="* || $opt == "-delete="* || $opt == "-wp-admin="* || $opt == "-whitelist="* || $opt == "-whitelist-remove="* ]]; then
 	value=$(echo "${opt}" | cut -d'=' -f 2 -s)
 	opt=$(echo "${opt}" | cut -d'=' -f 1 -s)
+fi
+
+if [[ $(conf_read nginx) != "true" && $opt =~ ^(-add|-delete|-list|-whitelist|-whitelist-remove)$ ]]; then
+	echo "${red}[ERROR] NGINX is required to get HTTP Authentication working properly! ${end}"
+	exit 1
 fi
 
 
@@ -70,23 +69,30 @@ elif [[ $opt == "-list" ]]; then
 
 	
 elif [[ $opt == "-wp-admin-on" || $opt == "-wp-admin-off" || $opt == "-wp-admin" ]]; then
-	
+	[[ $(conf_read nginx) == "true" ]] && iswpadon=$( grep -F "acl.conf;" /etc/nginx/common/wpcommon.conf )
 	if [[ $opt == "-wp-admin-on" || ( $opt == "-wp-admin" && $value == "on" ) ]]; then
-		iswpadon=$( grep -F "acl.conf;" /etc/nginx/common/wpcommon.conf )
 		if [[ -z $iswpadon ]]; then
-			sudo sed -i "/zone=one/a \  include common/acl.conf;" /etc/nginx/common/wpcommon.conf
-			sudo service nginx reload
+			if [[ $(conf_read nginx) == "true" ]]; then
+				sudo sed -i "/zone=one/a \  include common/acl.conf;" /etc/nginx/common/wpcommon.conf
+				sudo service nginx reload
+			fi
 			conf_write wp-admin-auth true
-			echo "${gre}WordPress admin authentication has been enabled! ${end}"
+			echo "${gre}WordPress Admin HTTP Authentication has been enabled! ${end}"
 		else
 			echo "${gre}HTTP Authentication for WP Admin pages is already enabled! ${end}"
 		fi
 	
 	elif [[ $opt == "-wp-admin-off" || ( $opt == "-wp-admin" && $value == "off" ) ]]; then
-		sudo sed -i "/acl.conf/d" /etc/nginx/common/wpcommon.conf
-		sudo service nginx reload
-		conf_write wp-admin-auth purged
-		echo "${gre}WordPress admin authentication has been disabled! ${end}"
+		if [[ -n $iswpadon || ( -z $iswpadon && $(conf_read nginx) != "true" ) ]]; then
+			if [[ $(conf_read nginx) == "true" ]]; then
+				sudo sed -i "/acl.conf/d" /etc/nginx/common/wpcommon.conf
+				sudo service nginx reload
+			fi
+			conf_write wp-admin-auth purged
+			echo "${gre}WordPress admin authentication has been disabled! ${end}"
+		else
+			echo "${gre}HTTP Authentication for WP Admin pages is already disabled! ${end}"
+		fi
 	else
 		echo "${red}[ERROR] Invalid option! ${end}"
 		exit 1
@@ -125,5 +131,5 @@ elif [[ $opt == "-whitelist-remove" ]]; then
 
 	
 else
-	echo "${red}Please enter a valid option!${end}"
+	echo "${red}[ERROR] Please enter a valid option!${end}"
 fi
diff --git a/plugins/log b/plugins/log
--- a/plugins/log
+++ b/plugins/log
@@ -11,7 +11,7 @@ opt=$2
 
 error() {
 	echo ""
-	echo "${red} Log file not found!!! ${end}"
+	echo "${red}[ERROR] Log file not found!!! ${end}"
 	echo ""
 	exit 1
 }
@@ -76,18 +76,18 @@ if [[ $opt == "-only-error" ]]; then
 	
 	# Global-Conf
 	if [[ -z $domain ]]; then
-		islog=$( grep -F "access_log off;" /etc/nginx/nginx.conf )
+		[[ $(conf_read nginx) == "true" ]] && islog=$( grep -F "access_log off;" /etc/nginx/nginx.conf )
 		if [[ $value == "on" ]]; then
 			if [[ -z $islog ]]; then
-				sudo sed -i '/access_log/c \	access_log off;' /etc/nginx/nginx.conf
+				[[ $(conf_read nginx) == "true" ]] && sudo sed -i '/access_log/c \	access_log off;' /etc/nginx/nginx.conf
 				conf_write global-access-log-off true
 				echo "${gre}Only-Error Log was successfully enabled (global)!${end}"
 			else	
 				echo "${red}Only-Error Log is already enabled (global)!${end}"
 			fi
 		elif [[ $value == "off" ]]; then
-			if [[ -n $islog ]]; then
-				sudo sed -i "/access_log/c \	access_log \/var\/log\/nginx\/access.log;" /etc/nginx/nginx.conf
+			if [[ -n $islog || ( -z $islog && $(conf_read nginx) != "true" ) ]]; then
+				[[ $(conf_read nginx) == "true" ]] && sudo sed -i "/access_log/c \	access_log \/var\/log\/nginx\/access.log;" /etc/nginx/nginx.conf
 				conf_write global-access-log-off purged
 				echo "${gre}Only-Error Log was successfully disabled (global)!${end}"
 			else	
@@ -98,7 +98,13 @@ if [[ $opt == "-only-error" ]]; then
 	
 	# Per site
 	if [[ -n $domain && -a /etc/nginx/sites-available/$domain ]]; then
-		islog=$( grep -F "access_log off;" /etc/nginx/sites-available/$domain )
+		if [[ $(conf_read nginx) == "true" ]]; then
+			islog=$( grep -F "access_log off;" /etc/nginx/sites-available/$domain )
+		else
+			echo "${red}[ERROR] Nginx not found! ${end}"
+			exit 1
+		fi
+		
 		if [[ $value == "on" ]]; then
 			if [[ -z $islog ]]; then
 				sudo sed -i '/access_log/c \	access_log off;' /etc/nginx/sites-available/$domain
diff --git a/plugins/webinoly b/plugins/webinoly
--- a/plugins/webinoly
+++ b/plugins/webinoly
@@ -18,7 +18,7 @@ fi
 
 
 if [[ $opt == "-update" ]]; then
-	checkver=$(wget -qO- https://api.webinoly.com/check?text=true)
+	checkver=$(wget --timeout=10 -t 1 -qO- https://api.webinoly.com/check?text=true)
 	currentver=$(conf_read app-version)
 	
 	if [[ ( -n $checkver && ${checkver//.} -gt ${currentver//.} ) || -n $value ]]; then
@@ -139,7 +139,7 @@ elif [[ $opt == "-tools-site" ]]; then
 	
 elif [[ $opt == "-login-www-data" || $opt == "-nologin-www-data" ]]; then
 	if [[ $(conf_read nginx) != "true" ]]; then
-		echo "${red}Nginx not found! ${end}"
+		echo "${red}[ERROR] Nginx not found! ${end}"
 		exit 1
 	fi
 	if [[ -n $value && ! $value =~ ^(on|off)$ ]]; then
@@ -211,19 +211,21 @@ ForceCommand internal-sftp
 
 	
 elif [[ $opt == "-config-cache" ]]; then
-	if [[ $(conf_read nginx) != "true" ]]; then
-		echo "${red} Nginx not found! ${end}"
-		exit 1
+	if [[ $(conf_read nginx) == "true" ]]; then	
+		hitline=$( grep -F "fastcgi_cache_valid 200" /etc/nginx/conf.d/fastcgi.conf )
+		hitval=$(echo "${hitline//;}" | rev | cut -d' ' -f 1 | rev)
+		inaline=$( grep -F "fastcgi_cache_path" /etc/nginx/conf.d/fastcgi.conf )
+		inactive=$(echo "${inaline//;}" | rev | cut -d' ' -f 1 | rev)
+		inaval=$(echo "${inactive}" | cut -d'=' -f 2)
+		maxsize=$(echo "${inaline}" | rev | cut -d' ' -f 2 | rev)
+		othline=$( grep -F "fastcgi_cache_valid 301 302 307 404" /etc/nginx/conf.d/fastcgi.conf )
+		othval=$(echo "${othline//;}" | rev | cut -d' ' -f 1 | rev)
+	else
+		hitval="Not yet defined"
+		inaval="Not yet defined"
+		othval="Not yet defined"
 	fi
-	
-	hitline=$( grep -F "fastcgi_cache_valid 200" /etc/nginx/conf.d/fastcgi.conf )
-	hitval=$(echo "${hitline//;}" | rev | cut -d' ' -f 1 | rev)
-	inaline=$( grep -F "fastcgi_cache_path" /etc/nginx/conf.d/fastcgi.conf )
-	inactive=$(echo "${inaline//;}" | rev | cut -d' ' -f 1 | rev)
-	inaval=$(echo "${inactive}" | cut -d'=' -f 2)
-	maxsize=$(echo "${inaline}" | rev | cut -d' ' -f 2 | rev)
-	othline=$( grep -F "fastcgi_cache_valid 301 302 307 404" /etc/nginx/conf.d/fastcgi.conf )
-	othval=$(echo "${othline//;}" | rev | cut -d' ' -f 1 | rev)
+
 	
 	if [[ -z $value ]]; then
 		echo "${gre}"
@@ -243,6 +245,7 @@ elif [[ $opt == "-config-cache" ]]; then
 		echo "FastCGI Cache Valid for Errors and Redirections (HttpCode: 301, 302, 307, 404) actual value is: $othval"
 		read -p "   Set new value: " oth
 		oth=${oth:-$othval}
+		echo ""
 	else
 		custombegin=$(echo "${value}" | cut -c-1)
 		customlast=$(echo "${value}" | rev | cut -c-1)
@@ -254,17 +257,15 @@ elif [[ $opt == "-config-cache" ]]; then
 	fi
 	
 	if [[ "$hit" =~ ^[0-9]+[smhdwMy]$ && "$ina" =~ ^[0-9]+[smhdwMy]$ && "$oth" =~ ^[0-9]+[smhdwMy]$ ]]; then
-		sudo sed -i "/fastcgi_cache_valid 200/c \fastcgi_cache_valid 200 ${hit};" /etc/nginx/conf.d/fastcgi.conf
-		sudo sed -i "/fastcgi_cache_valid 301 302 307 404/c \fastcgi_cache_valid 301 302 307 404 ${oth};" /etc/nginx/conf.d/fastcgi.conf
-		sudo sed -i "/fastcgi_cache_path/c \fastcgi_cache_path \/var\/run\/nginx-cache levels=1:2 keys_zone=WORDPRESS:50m ${maxsize} inactive=${ina};" /etc/nginx/conf.d/fastcgi.conf
+		if [[ $(conf_read nginx) == "true" ]]; then	
+			sudo sed -i "/fastcgi_cache_valid 200/c \fastcgi_cache_valid 200 ${hit};" /etc/nginx/conf.d/fastcgi.conf
+			sudo sed -i "/fastcgi_cache_valid 301 302 307 404/c \fastcgi_cache_valid 301 302 307 404 ${oth};" /etc/nginx/conf.d/fastcgi.conf
+			sudo sed -i "/fastcgi_cache_path/c \fastcgi_cache_path \/var\/run\/nginx-cache levels=1:2 keys_zone=WORDPRESS:50m ${maxsize} inactive=${ina};" /etc/nginx/conf.d/fastcgi.conf
+		fi
 		conf_write fastcgi-conf ${hit},${ina},${oth}
-		echo "${gre}"
-		echo "FastCGI Cache values has been successfully updated!"
-		echo "${end}"
+		echo "${gre}FastCGI Cache values has been successfully updated!${end}"
 	else
-		echo "${red}"
-		echo "  [ERROR] Invalid values!"
-		echo "${end}"
+		echo "${red}[ERROR] Invalid values!${end}"
 	fi
 
 	
@@ -420,7 +421,7 @@ elif [[ $opt == "-blockip" ]]; then
 			sh -c "echo -n 'deny $value;\n' >> /etc/nginx/conf.d/blockips.conf"
 			echo "${gre}The IP address ${blu}'$value'${gre} was successfully blocked!${end}"
 		else	
-			echo "${red}Please, enter a valid value!${end}"
+			echo "${red}[ERROR] Please, enter a valid value!${end}"
 		fi
 	else
 		echo "${red}[ERROR] Nginx file not found!${end}"
@@ -435,7 +436,7 @@ elif [[ $opt == "-unblockip" ]]; then
 			sed -i "\#^deny ${value};#d" /etc/nginx/conf.d/blockips.conf
 			echo "${gre}The IP address ${blu}'$value'${gre} was successfully unblocked!${end}"
 		else
-			echo "${red}Please, enter a valid value!${end}"
+			echo "${red}[ERROR] Please, enter a valid value!${end}"
 		fi
 	else
 		echo "${red}[ERROR] Nginx file not found!${end}"
@@ -453,41 +454,36 @@ elif [[ $opt == "-conf-value_"* ]]; then
 			echo "${red}Please, enter a valid value!${end}"
 		fi
 	else
-		echo "${red}Please, enter a valid variable name!${end}"
+		echo "${red}[ERROR] Please, enter a valid variable name!${end}"
 	fi
 
 
 elif [[ $opt == "-yoast-sitemap" ]]; then
-	if [[ $(conf_read nginx) != "true" ]]; then
-		echo "${red} Nginx not found! ${end}"
-		exit 1
-	fi
-	
-	ystmap=$( grep -F "# YoastSitemapStart - Yoast SEO Plugin" /etc/nginx/common/wpcommon.conf )
+	[[ $(conf_read nginx) == "true" ]] && ystmap=$( grep -F "# YoastSitemapStart - Yoast SEO Plugin" /etc/nginx/common/wpcommon.conf )
 	if [[ $value == "on" ]]; then
 		if [[ -z $ystmap ]]; then
-			sudo cat /opt/webinoly/templates/template-yoast-sitemap >> /etc/nginx/common/wpcommon.conf
+			[[ $(conf_read nginx) == "true" ]] && sudo cat /opt/webinoly/templates/template-yoast-sitemap >> /etc/nginx/common/wpcommon.conf
 			conf_write yoast-sitemap true
 			echo "${gre}Yoast Sitemap Support was successfully enabled!${end}"
 		else
 			echo "${red}Yoast Sitemap Support is already enabled!${end}"
 		fi
 	elif [[ $value == "off" ]]; then
-		if [[ -n $ystmap ]]; then
-			sudo sed -i '/YoastSitemapStart/,/YoastSitemapEnd/{/.*/d}' /etc/nginx/common/wpcommon.conf
+		if [[ -n $ystmap || ( -z $ystmap && $(conf_read nginx) != "true" ) ]]; then
+			[[ $(conf_read nginx) == "true" ]] && sudo sed -i '/YoastSitemapStart/,/YoastSitemapEnd/{/.*/d}' /etc/nginx/common/wpcommon.conf
 			conf_write yoast-sitemap purged
 			echo "${gre}Yoast Sitemap Support was successfully disabled!${end}"
 		else
 			echo "${red}Yoast Sitemap Support is already disabled!${end}"
 		fi
 	else
-		echo "${red}Please, enter a valid option to enable/disable Yoast Sitemap Support!${end}"
+		echo "${red}[ERROR] Please, enter a valid option to enable/disable Yoast Sitemap Support!${end}"
 	fi
 
 
 elif [[ $opt == "-default-site" ]]; then
 	if [[ $(conf_read nginx) != "true" ]]; then
-		echo "${red}Nginx not found! ${end}"
+		echo "${red}[ERROR] Nginx not found! ${end}"
 		exit 1
 	fi
 
@@ -541,7 +537,7 @@ elif [[ $opt == "-default-site" ]]; then
 	
 	
 else
-	echo "${red}Please enter a valid option!${end}"
+	echo "${red}[ERROR] Please enter a valid option!${end}"
 fi
 
 
