wp debug mode
Now we have the option to activate/deactivate WP debug mode and  some other improvements.

diff --git a/plugins/log b/plugins/log
--- a/plugins/log
+++ b/plugins/log
@@ -3,7 +3,7 @@
 # View logs in real time Plugins
 # Syntax: log <domain> <option>
 # Options: -wp, -error, -mail, -php o -fpm, -mysql, -only-error, -le, -ssh
-# Arguments: -lines
+# Arguments: -lines, -display
 # Notes: If no domain or option is entered, access logs are displayed.
 
 source /opt/webinoly/lib/general
@@ -131,14 +131,49 @@ elif [[ -n $domain && -a /etc/nginx/sites-available/$domain ]]; then
 	# Check if Access Log is enabled
 	islog=$( grep -F "access_log off;" /etc/nginx/sites-available/$domain )
 	if [[ -z $error && -z $wp && -n $islog ]]; then
-		echo "${red}[ERROR] Access Log for ${blu}- $domain -${red} is disabled!${end}"
+		echo "${red}[ERROR] Access Log for${blu} $domain ${red}is disabled!${end}"
 		exit 1
 	fi
 	
-	if [[ -n $error && -a /var/log/nginx/$domain.error.log ]]; then
+	# WordPress Logs
+	[[ -z $subfolder ]] && wpath="/var/www/$domain/wp-config.php" || wpath="/var/www/$domain/htdocs$subfolder/wp-config.php"
+	if [[ -n $wp && -a $wpath ]]; then
+		iswpdeb=$( grep -F "'WP_DEBUG'" $wpath | cut -f 3 -d "'" -s | cut -f 2 -d " " -s )
+		if [[ $wp == "on" ]]; then
+			if [[ $iswpdeb == "false" ]]; then
+				[[ $display == "off" ]] && dis="false" || dis="true"
+				sudo sed -i "/'WP_DEBUG'/c \define('WP_DEBUG', true );" $wpath
+				sudo sed -i "/'WP_DEBUG'/a \define('WP_DEBUG_DISPLAY', $dis );" $wpath
+				sudo sed -i "/'WP_DEBUG'/a \define('WP_DEBUG_LOG', true );" $wpath
+				echo "${gre}WordPress Debug mode for${blu} $domain ${gre}has been successfully enabled!${end}"
+			else
+				echo "${gre}WordPress Debug mode for${blu} $domain ${gre}is already enabled!${end}"
+			fi
+		elif [[ $wp == "off" ]]; then
+			if [[ $iswpdeb == "true" ]]; then
+				sudo sed -i "/'WP_DEBUG'/c \define('WP_DEBUG', false );" $wpath
+				sudo sed -i "/'WP_DEBUG_LOG'/d" $wpath
+				sudo sed -i "/'WP_DEBUG_DISPLAY'/d" $wpath
+				echo "${gre}WordPress Debug mode for${blu} $domain ${gre}has been successfully disabled!${end}"
+			else
+				echo "${gre}WordPress Debug mode for${blu} $domain ${gre}is already disabled!${end}"
+			fi
+		elif [[ -a /var/www/$domain/htdocs$subfolder/wp-content/debug.log && $iswpdeb == "true" ]]; then
+			sudo tail -f --lines=$clines /var/www/$domain/htdocs$subfolder/wp-content/debug.log
+		elif [[ $iswpdeb != "true" ]]; then
+			echo "${red}[ERROR] WordPress Debug Mode is not enabled!${end}"
+			exit 1
+		else
+			echo "${red}[ERROR] WordPress log file not found or still empty!${end}"
+			exit 1
+		fi
+	elif [[ -n $wp ]]; then
+		echo "${red}[ERROR] WordPress configuration file not found!${end}"
+		exit 1
+	
+	# Access and error logs
+	elif [[ -n $error && -a /var/log/nginx/$domain.error.log ]]; then
 		sudo tail -f --lines=$clines /var/log/nginx/$domain.error.log
-	elif [[ -n $wp && -a /var/www/$domain/htdocs/wp-content/debug.log ]]; then
-		sudo tail -f --lines=$clines /var/www/$domain/htdocs/wp-content/debug.log
 	elif [[ -a /var/log/nginx/$domain.access.log && -z $error && -z $wp ]]; then
 		sudo tail -f --lines=$clines /var/log/nginx/$domain.access.log
 	else
