yoast sitemap
Now we have support for Yoast-Sitemap per site.

diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -2,7 +2,7 @@
 
 # Site Manager Plugin (Create, delete and de/activate)
 # Syntax: site <domain> <option> <argument>
-# Options: -html, -php, -mysql, -wp, -wpsubdir, -wpsubdom, -parked, -proxy, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect
+# Options: -html, -php, -mysql, -wp, -wpsubdir, -wpsubdom, -parked, -proxy, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap
 # Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp
 
 # shopt is necessary for this kind !(html|22222) of patterns
@@ -207,7 +207,7 @@ elif [[ -n $wp && -n $domain ]]; then
 	createsite
 	sudo sed -i '/locations.conf/i \	include common/wpcommon.conf;' /etc/nginx/sites-available/$domain
 	[[ $(conf_read wp-admin-auth) == "purged" ]] && sudo httpauth -wp-admin=off -site=$domain
-
+	[[ $(conf_read yoast-sitemap) != "purged" ]] && sudo site $domain -yoast-sitemap=on
 
 # Create WP Multisite (Sub-directory)
 elif [[ -n $wpsubdir && -n $domain ]]; then
@@ -215,14 +215,16 @@ elif [[ -n $wpsubdir && -n $domain ]]; then
 	sudo sed -i '/locations.conf/i \	include common/wpsubdir.conf;' /etc/nginx/sites-available/$domain
 	sudo sed -i '/locations.conf/i \	include common/wpcommon.conf;' /etc/nginx/sites-available/$domain
 	[[ $(conf_read wp-admin-auth) == "purged" ]] && sudo httpauth -wp-admin=off -site=$domain
-
+	[[ $(conf_read yoast-sitemap) != "purged" ]] && sudo site $domain -yoast-sitemap=on
+	
 	
 # Create WP Multisite (Sub-domain)	
 elif [[ -n $wpsubdom && -n $domain ]]; then
 	createsite
 	sudo sed -i '/locations.conf/i \	include common/wpcommon.conf;' /etc/nginx/sites-available/$domain
 	[[ $(conf_read wp-admin-auth) == "purged" ]] && sudo httpauth -wp-admin=off -site=$domain
-
+	[[ $(conf_read yoast-sitemap) != "purged" ]] && sudo site $domain -yoast-sitemap=on
+	
 
 # Parked Domain
 elif [[ -n $parked && -n $domain ]]; then
@@ -438,7 +440,30 @@ elif [[ -n $cache ]]; then
 # Force www or non-www redirect (www, root, off)
 elif [[ -n $force_redirect && -a /etc/nginx/sites-available/$domain ]]; then
 	force_redirect
-	
+
+
+# Yoast Sitemap support, per site.
+elif [[ -n $yoast_sitemap && -a /etc/nginx/sites-available/$domain ]]; then
+	ystmap=$( grep -F "yoast-sitemap.conf;" /etc/nginx/sites-available/$domain )
+	if [[ $yoast_sitemap == "on" ]]; then
+		if [[ -z $ystmap ]]; then
+			sudo sed -i "/# WebinolyCustom$/a \	include common/yoast-sitemap.conf;" /etc/nginx/sites-available/$domain
+			echo "${gre}Yoast Sitemap Support was successfully enabled!${end}"
+		else
+			echo "${gre}Yoast Sitemap Support is already enabled!${end}"
+		fi
+	elif [[ $yoast_sitemap == "off" ]]; then
+		if [[ -n $ystmap ]]; then
+			sudo sed -i "/yoast-sitemap.conf;/d" /etc/nginx/sites-available/$domain
+			echo "${gre}Yoast Sitemap Support was successfully disabled!${end}"
+		else
+			echo "${gre}Yoast Sitemap Support is already disabled!${end}"
+		fi
+	else
+		echo "${red}[ERROR] Please, enter a valid option to enable/disable Yoast Sitemap Support!${end}"
+		exit 1
+	fi
+
 	
 # Catch ERROR 
 elif [[ -n $domain && ! -a /etc/nginx/sites-available/$domain ]]; then
