replace content
Option to replace content in WP sites.

diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -111,7 +111,7 @@ if [[ -n $subfolder && ! ( $subfolder =~ ^\/([A-Za-z0-9_\/\-]+)?[^\/]$ ) ]]; the
 	echo "${red}[ERROR] Please, enter a valid value for subfolder!${end}"
 	exit 1
 fi
-if [[ -n $subfolder && $type != [123] && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from ]]; then
+if [[ -n $subfolder && $type != [123] && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content ]]; then
 	echo "${red}[ERROR] Subfolder option is only supported for WordPress sites!${end}"
 	exit 1
 else
@@ -673,6 +673,7 @@ elif [[ -n $clone_from ]]; then
 	
 	if [[ -n $subfolder ]]; then
 		wpcon="/var/www/$domain/htdocs$subfolder/wp-config.php"
+		arg=" -subfolder=$subfolder"
 		
 		sudo cp /etc/nginx/apps.d/$clone_from$subname-php.conf /etc/nginx/apps.d/$domain$subname-php.conf
 		sudo cp /etc/nginx/apps.d/$clone_from$subname-wpfc.conf /etc/nginx/apps.d/$domain$subname-wpfc.conf
@@ -688,6 +689,7 @@ elif [[ -n $clone_from ]]; then
 		sudo mkdir -p /var/www/$domain/htdocs$dest
 		sudo cp -r /var/www/$clone_from/htdocs$subfolder /var/www/$domain/htdocs$dest
 	else
+		arg=""
 		wpcon="/var/www/$domain/wp-config.php"
 		sudo cp -r /var/www/$clone_from /var/www/$domain
 	fi
@@ -714,9 +716,6 @@ elif [[ -n $clone_from ]]; then
 USE $dom;
 UPDATE ${wp_dbpref}options SET option_value='http://${domain}${subfolder}' WHERE option_name='home';
 UPDATE ${wp_dbpref}options SET option_value='http://${domain}${subfolder}' WHERE option_name='siteurl';
-UPDATE ${wp_dbpref}posts SET post_content = REPLACE (post_content,'http://$clone_from','http://$domain');
-UPDATE ${wp_dbpref}posts SET post_content = REPLACE (post_content,'https://$clone_from','http://$domain');
-UPDATE ${wp_dbpref}posts SET post_content = REPLACE (post_content,'$clone_from','$domain');
 FLUSH PRIVILEGES;
 _EOF_
 	else
@@ -726,9 +725,6 @@ _EOF_
 USE $dom;
 UPDATE ${wp_dbpref}_options SET option_value='http://${domain}${subfolder}' WHERE option_name='home';
 UPDATE ${wp_dbpref}_options SET option_value='http://${domain}${subfolder}' WHERE option_name='siteurl';
-UPDATE ${wp_dbpref}posts SET post_content = REPLACE (post_content,'http://$clone_from','http://$domain');
-UPDATE ${wp_dbpref}posts SET post_content = REPLACE (post_content,'https://$clone_from','http://$domain');
-UPDATE ${wp_dbpref}posts SET post_content = REPLACE (post_content,'$clone_from','$domain');
 FLUSH PRIVILEGES;
 _EOF_
 	fi
@@ -736,8 +732,48 @@ _EOF_
 	sudo sed -i "/DB_NAME/c \define('DB_NAME', '$dom');" $wpcon
 	sudo sed -i "/DB_USER/c \define('DB_USER', '$dom');" $wpcon
 	sudo sed -i "/DB_PASSWORD/c \define('DB_PASSWORD', '$AUTOGENPASS_WPDB');" $wpcon
-	echo "${gre}Site ${blu}'$domain$subfolder'${gre} is now a successful clone of ${blu}'$clone_from$subfolder'${end}"
 	
+	if [[ $replace_content != "off" ]]; then
+		sudo site $domain -replace-content=[http://$clone_from,http://$domain]$arg > /dev/null 2>&1
+		sudo site $domain -replace-content=[https://$clone_from,http://$domain]$arg > /dev/null 2>&1
+		sudo site $domain -replace-content=[$clone_from,$domain]$arg > /dev/null 2>&1
+	fi
+	echo "${gre}Site ${blu}'$domain$subfolder'${gre} is now a successful clone of ${blu}'$clone_from$subfolder'${end}"
+
+
+elif [[ -n $replace_content && -a /etc/nginx/sites-available/$domain ]]; then
+	if [[ $(is_wp $domain $subfolder) != "true" ]]; then
+		echo "${red}[ERROR] Site${blu} $domain ${red}is not a WordPress site!${end}"
+		exit 1
+	fi
+	
+	if [[ $replace_content == true ]]; then
+		echo ""
+		read -p "${blu}Search: ${end}" search
+		read -p "${blu}Replace with: ${end}" replace
+		echo ""
+	elif [[ $(echo "${replace_content}" | cut -c-1) == "[" && $(echo "${replace_content}" | rev | cut -c-1) == "]" ]]; then
+		userdata=${replace_content:1:-1}
+		search=$(echo "${userdata}" | cut -d',' -f 1 -s)
+		replace=$(echo "${userdata}" | cut -d',' -f 2 -s)
+	fi
+	
+	if [[ -z $search || -z $replace ]]; then
+		echo "${red}[ERROR] Please, enter a valid value for search and replace!${end}"
+		exit 1
+	fi
+	
+	wp_dbdata $domain
+	query="USE $wp_dbname; UPDATE ${wp_dbpref}posts SET post_content = REPLACE (post_content,'$search','$replace'); FLUSH PRIVILEGES;"
+	
+	if [[ $wp_dbhost == "localhost" ]]; then
+		ROOT_PASS=$( echo $(conf_read mysql-root) | openssl enc -d -a -salt )
+		sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "$query"
+	else
+		sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$query"
+	fi
+	echo "${gre}Content successfully replaced in your WP site!${end}"
+
 
 # Catch ERROR 
 elif [[ -n $domain && ! -a /etc/nginx/sites-available/$domain ]]; then
