wildcard ask
Now Wildcard SSL ask if domain is empty.

diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -350,23 +350,24 @@ elif [[ ( -n $ssl_on || -n $ssl_off || -n $ssl ) && -a /etc/nginx/sites-availabl
 			fi
 		elif [[ -n $add_to_wildcard ]]; then
 			if [[ $add_to_wildcard == true ]]; then
-				echo "${red}[ERROR] Please, enter a valid wildcard SSL domain! ${end}"
+				echo "${gre}Please, enter a valid Wildcard SSL Domain! ${end}"
+				read -p "${blu}Domain: ${end}" add_to_wildcard
+				add_to_wildcard=${add_to_wildcard:-NeverMatchDotCom}
+			fi
+			
+			# Check if domain is a subdomain that can be used in the wildcard cert.
+			if [[ $domain == *.*."$add_to_wildcard" ]]; then
+				echo "${red}[ERROR] Wildcard Certs only support first-level subdomains!${end}"
 				exit 1
+			elif [[ ! -d /etc/letsencrypt/live/$add_to_wildcard ]]; then
+				echo "${red}[ERROR] Wildcard Cert not found!${end}"
+				exit 1
+			elif [[ $domain == *."$add_to_wildcard" ]]; then
+				ssl_nginx
+				echo "${gre}Your site ${blu}- $domain -${gre} have been successfully added to the ${blu}- $add_to_wildcard -${gre} wildcard cert.${end}"
 			else
-				# Check if domain is a subdomain that can be used in the wildcard cert.
-				if [[ $domain == *.*."$add_to_wildcard" ]]; then
-					echo "${red}[ERROR] Wildcard Certs only support first-level subdomains!${end}"
-					exit 1
-				elif [[ ! -d /etc/letsencrypt/live/$add_to_wildcard ]]; then
-					echo "${red}[ERROR] Wildcard Cert not found!${end}"
-					exit 1
-				elif [[ $domain == *."$add_to_wildcard" ]]; then
-					ssl_nginx
-					echo "${gre}Your site ${blu}- $domain -${gre} have been successfully added to the ${blu}- $add_to_wildcard -${gre} wildcard cert.${end}"
-				else
-					echo "${red}[ERROR] Seems like your site is not a valid subdomain!${end}"
-					exit 1
-				fi
+				echo "${red}[ERROR] Seems like your site is not a valid subdomain!${end}"
+				exit 1
 			fi
 		else
 			site_ssl_on
