new catch arg system
New method implemented in STACK command.

diff --git a/plugins/stack b/plugins/stack
--- a/plugins/stack
+++ b/plugins/stack
@@ -3,63 +3,25 @@
 # Server Stack Manager
 # Syntax: stack <option> <arguments>
 # Options: -html, -nginx, -php, -lemp, -mysql, -pma, -info, -purge-server-all, -php-ver
-# Arguments: -purge, -notools, -noptim
+# Arguments: -purge, -notools
 
 source /opt/webinoly/lib/install
 source /opt/webinoly/lib/webin
-opt=$1
-arg=$2
-
-
-# Check if user entered arg before option and correct it.
-if [[ $opt =~ ^(-purge|-notools|-noptim)$ ]]; then
-	opt=$2
-	arg=$1
-fi
-
-
-# Extract value if exist
-if [[ $opt == "-nginx="* || $opt == "-html="* || $opt == "-lemp="* || $opt == "-php="* || $opt == "-php-ver="* || $opt == "-purge-server-all="* ]]; then
-	value=$(echo "${opt}" | cut -d'=' -f 2 -s)
-	opt=$(echo "${opt}" | cut -d'=' -f 1 -s)
-fi
-if [[ $arg == "-purge="* ]]; then
-	value=$(echo "${arg}" | cut -d'=' -f 2 -s)
-	arg=$(echo "${arg}" | cut -d'=' -f 1 -s)
-fi
+check_for_parameters $@
 
 
 # FORCE - Unattended Purge
 clear_force_flag() {
 	[[ $(conf_read force-flag) == "true" ]] && conf_delete force-flag
 }
-if [[ $value == "force" && ($arg == "-purge" || $opt == "-purge-server-all" || $opt == "-php") ]]; then
-	conf_write force-flag true
-	force="1"
-fi
-if [[ $value == "keep-data" && $arg == "-purge" && $opt == "-mysql" ]]; then
+if [[ $purge == "force" || $purge_server_all == "force" || $php == "force" ]]; then
 	conf_write force-flag true
 	force="1"
 fi
 
 
-# LEMP without Optimization for testing purpose (just packages)!
-if [[ $arg == "-noptim" && $opt == "-lemp" ]]; then
-	if ! [[ $(conf_read nginx) == "true" || $(conf_read php) == "true" || $(conf_read mysql) == "true" ]]; then
-		nginx_install
-		php_install
-		mysql_install
-		echo ""
-		echo "${gre}LEMP without optimization has been installed!!! ${end}"
-		echo ""
-		messagend_install dbpass
-	else
-		echo "${red}[ERROR] Some packages are already installed!${end}"
-	fi
-
-
-# Delete some stack
-elif [[ $arg == "-purge" && ( $opt == "-html" || $opt == "-nginx" ) ]]; then
+# Delete/Purge some stack
+if [[ -n $purge && ( -n $html || -n $nginx ) ]]; then
 	api-events_update pn1
 	if [[ $(conf_read nginx) != "true" ]]; then
 		echo "${red}Nginx is not installed, hence can not be deleted! ${end}"
@@ -132,7 +94,7 @@ elif [[ $arg == "-purge" && ( $opt == "-html" || $opt == "-nginx" ) ]]; then
 	fi
 	echo ""
 	
-elif [[ $arg == "-purge" && $opt == "-php" ]]; then
+elif [[ -n $purge && -n $php ]]; then
 	api-events_update pp1
 	if [[ $(conf_read php) != "true" ]]; then
 		echo "${red}PHP is not installed, hence can not be deleted! ${end}"
@@ -191,7 +153,7 @@ elif [[ $arg == "-purge" && $opt == "-php" ]]; then
 	api-events_update pp2
 
 	
-elif [[ $arg == "-purge" && $opt == "-mysql" ]]; then
+elif [[ -n $purge && -n $mysql ]]; then
 	api-events_update pm1
 	if [[ $(conf_read mysql) != "true" ]]; then
 		echo "${red}MySQL is not installed, hence can not be deleted! ${end}"
@@ -224,7 +186,7 @@ elif [[ $arg == "-purge" && $opt == "-mysql" ]]; then
 		[[ -n $stackver && ${stackver//.} -lt 13 ]] && mysqlver="10.2"
 		
 		sudo service mysql stop
-		if [[ $value == "keep-data" ]]; then
+		if [[ $mysql == "keep-data" ]]; then
 			echo "mariadb-server-${mysqlver}	mariadb-server-${mysqlver}/postrm_remove_databases	boolean false" | debconf-set-selections
 		else
 			echo "mariadb-server-${mysqlver}	mariadb-server-${mysqlver}/postrm_remove_databases	boolean true" | debconf-set-selections
@@ -246,7 +208,7 @@ elif [[ $arg == "-purge" && $opt == "-mysql" ]]; then
 			;;
 		esac
 		
-		if [[ $value != "keep-data" ]]; then
+		if [[ $mysql != "keep-data" ]]; then
 			sudo rm -rf /etc/mysql
 			sudo rm -rf /var/lib/mysql
 		else
@@ -267,7 +229,7 @@ elif [[ $arg == "-purge" && $opt == "-mysql" ]]; then
 	echo ""
 	api-events_update pm4
 	
-elif [[ $arg == "-purge" && $opt == "-pma" ]]; then
+elif [[ -n $purge && -n $pma ]]; then
 	api-events_update pm2
 	if [[ $(conf_read mysql-tool) != "true" ]]; then
 		echo "${red} PhpMyAdmin is not installed, hence can not be deleted! ${end}"
@@ -303,23 +265,19 @@ elif [[ $arg == "-purge" && $opt == "-pma" ]]; then
 	echo ""
 	api-events_update pm3
 		
-elif [[ $arg == "-purge" && $opt == "-lemp" ]]; then
+elif [[ -n $purge && -n $lemp ]]; then
 	echo ""
 	echo "${red}If you want to remove Webinoly Stack completely from your server use the '-purge-server-all' option or remove each package individually.  ${end}"
 	echo ""
-	
-elif [[ $arg != "-purge" && $arg != "-notools" && -n "$arg" ]]; then
-	echo ""
-	echo "${red} $arg is not a valid argument! ${end}"
-	echo ""
+
 
 
 # Install some stack
-elif [[ $opt == "-html" || $opt == "-nginx" ]]; then
+elif [[ -n $html || -n $nginx ]]; then
 	if [[ $(conf_read nginx) != "true" ]]; then
 		nginx_install
 		nginx_optim
-		[[ $arg != "-notools" ]] && nginx_tool
+		[[ -z $notools ]] && nginx_tool
 		
 		echo ""
 		echo "${gre}Nginx has been successfully Optimized by Webinoly! ${end}"
@@ -332,7 +290,7 @@ elif [[ $opt == "-html" || $opt == "-nginx" ]]; then
 			echo "NGINX has been successfully Optimized by Webinoly!"
 			echo "${end}"
 		fi
-		if [[ $(conf_read nginx-tool) != "true" && $arg != "-notools" ]]; then
+		if [[ $(conf_read nginx-tool) != "true" && -z $notools ]]; then
 			nginx_tool
 			echo "${gre}"
 			echo "NGINX Tools has been re-installed!"
@@ -340,8 +298,8 @@ elif [[ $opt == "-html" || $opt == "-nginx" ]]; then
 		fi
 	fi
 	
-elif [[ $opt == "-php" ]]; then
-	if [[ $(conf_read php) != "true" || ( -n $value && $(conf_read php-v${value}) != "true" ) ]]; then
+elif [[ -n $php ]]; then
+	if [[ $(conf_read php) != "true" || ( $php != true && $(conf_read php-v${php}) != "true" ) ]]; then
 		if [[ $(conf_read nginx) != "true" && $(conf_read force-flag) != "true" ]]; then
 			echo ""
 			echo "${blu}Nginx is not installed, do you want to install it too [Y/n]?${end} "
@@ -349,14 +307,12 @@ elif [[ $opt == "-php" ]]; then
 			  answer=${answer:-y}
 			  [[ $answer = [YyNn] ]] && break
 			done
-			[[ $answer != [Nn] ]] && stack -nginx $arg
+			[[ $answer != [Nn] ]] && stack -nginx $2
 		fi
 		
-		[[ -n $value ]] && php_install $value || php_install
-		[[ -n $value && $(conf_read php-v${value}) == "true" ]] && php_optim $value
-		[[ -z $value ]] && php_optim
-		def=$(conf_read php-ver)
-		[[ $arg != "-notools" && $(conf_read php-tool) != "true" ]] && php_tool
+		[[ $php != true && $php != "force" ]] && php_install $php || php_install
+		[[ $php != true && $php != "force" && $(conf_read php-v${php}) == "true" ]] && php_optim $php || php_optim
+		[[ -z $notools && $(conf_read php-tool) != "true" ]] && php_tool
 		echo ""
 		echo "${gre}PHP has been successfully Optimized by Webinoly! ${end}"
 		echo ""
@@ -368,7 +324,7 @@ elif [[ $opt == "-php" ]]; then
 			echo "PHP has been successfully Optimized by Webinoly!"
 			echo "${end}"
 		fi
-		if [[ $(conf_read php-tool) != "true" && $arg != "-notools" ]]; then
+		if [[ $(conf_read php-tool) != "true" && -z $notools ]]; then
 			php_tool
 			echo "${gre}"
 			echo "PHP Tools has been re-installed!"
@@ -376,14 +332,14 @@ elif [[ $opt == "-php" ]]; then
 		fi
 	fi
 	
-elif [[ $opt == "-mysql" ]]; then
+elif [[ -n $mysql ]]; then
 	if [[ $(conf_read mysql) != "true" ]]; then
 		mysql_install
-		[[ $arg != "-notools" ]] && stack -pma
+		[[ -z $notools ]] && stack -pma
 		messagend_install dbpass
 	else
 		echo "${red}MySQL is already installed!${end}"
-		if [[ $(conf_read mysql-tool) != "true" && $arg != "-notools" ]]; then
+		if [[ $(conf_read mysql-tool) != "true" && -z $notools ]]; then
 			stack -pma
 			echo "${gre}"
 			echo "MySQL Tools has been re-installed!"
@@ -391,7 +347,7 @@ elif [[ $opt == "-mysql" ]]; then
 		fi
 	fi
 
-elif [[ $opt == "-pma" ]]; then
+elif [[ -n $pma ]]; then
 	if [[ $(conf_read mysql) != "true" || $(conf_read php) != "true" || $(conf_read nginx) != "true" || $(conf_read nginx-tool) != "true" ]]; then
 		echo "${red} You need to have MySQL, PHP and NGINX installed before you can install PhpMyAdmin! ${end}"
 		clear_force_flag
@@ -399,38 +355,38 @@ elif [[ $opt == "-pma" ]]; then
 	fi
 	[[ $(conf_read mysql-tool) != "true" ]] && mysql_tool || echo "${red}PhpMyAdmin is already installed!${end}"
 
-elif [[ $opt == "-lemp" ]]; then
-	[[ $value =~ ^(stable|mainline)$ ]] && stack -nginx=$value $arg || stack -nginx $arg
-	stack -php $arg
-	stack -mysql $arg
+elif [[ -n $lemp ]]; then
+	[[ $lemp =~ ^(stable|mainline)$ ]] && stack -nginx=$lemp $2 || stack -nginx $2
+	stack -php $2
+	stack -mysql $2
 	echo ""
 	echo "${gre}Nginx, PHP, MySQL (MariaDB) and some other useful tools have been installed successfully! ${end}"
 	echo ""
 	
-elif [[ $opt == "-php-ver" ]]; then
+elif [[ -n $php_ver ]]; then
 	if [[ $(conf_read multi-php) == "true" ]]; then
 		echo "${red}This command is disabled because Multi-PHP is enabled!${end}"
 		exit 0
 	fi
 	
-	if [[ -n $value && ($value == "7.3" || $value == "7.2" || $value == "7.1" || $value == "7.0" || $value == "5.6") ]]; then
-		echo "${blu}New PHP version: '$value' ${end}"
-		if [[ $(conf_read php) == "true" && $(conf_read php-ver) == $value ]]; then
-			echo "${red}PHP $value is currently installed!${end}"
+	if [[ $php_ver != true && $php_ver =~ ^(7.3|7.2|7.1|7.0|5.6)$ ]]; then
+		echo "${blu}New PHP version: '$php_ver' ${end}"
+		if [[ $(conf_read php) == "true" && $(conf_read php-ver) == $php_ver ]]; then
+			echo "${red}PHP $php_ver is currently installed!${end}"
 		elif [[ $(conf_read php) == "true" && $(conf_read mysql-tool) == "true" ]]; then
 			sudo stack -php -purge=force
-			conf_write php-ver $value
+			conf_write php-ver $php_ver
 			# force flag prevent to be questioned (Unattended) when nginx is not installed.
 			conf_write force-flag true
 			sudo stack -php
 			sudo stack -pma
 		elif [[ $(conf_read php) == "true" && $(conf_read mysql-tool) != "true" ]]; then
 			sudo stack -php -purge=force
-			conf_write php-ver $value
+			conf_write php-ver $php_ver
 			conf_write force-flag true
 			sudo stack -php
 		elif [[ $(conf_read php) != "true" && $(conf_read mysql-tool) != "true" ]]; then
-			conf_write php-ver $value
+			conf_write php-ver $php_ver
 			echo "${gre}PHP is not already installed but new version will be installed next time! ${end}"
 		fi
 		clear_force_flag
@@ -440,9 +396,9 @@ elif [[ $opt == "-php-ver" ]]; then
 
 	
 # Info & Purge-Server-All
-elif [[ $opt == "-info" ]]; then
+elif [[ -n $info ]]; then
 	system_info
-elif [[ $opt == "-purge-server-all" ]]; then
+elif [[ -n $purge_server_all ]]; then
 	echo ""
 	echo "${red} ¡ C A U T I O N !  You are about to remove Webinoly Stack completely from your server!"
 	echo " This action will remove Nginx, PHP, MySQL and all the other tools, all your sites will remain in the server but will be publicly unavailable after this action."
@@ -478,7 +434,7 @@ elif [[ $opt == "-purge-server-all" ]]; then
 		echo ""
 	fi
 else
-	echo "${red} $opt is not a valid option! ${end}"
+	echo "${red}[ERROR] Please, enter a valid option! ${end}"
 fi
 
 
