backups
Backups to AWS S3 and local backups for WP sites databases.

diff --git a/plugins/webinoly b/plugins/webinoly
--- a/plugins/webinoly
+++ b/plugins/webinoly
@@ -6,6 +6,7 @@
 # Arguments: -raw
 
 source /opt/webinoly/lib/webin
+source /opt/webinoly/lib/bkp
 check_for_parameters $@
 api-events_update wys
 
@@ -635,6 +636,48 @@ elif [[ -n $smtp ]]; then
 	fi
 	smtp_setup
 	nginx_not="true" # Nginx-Reload not-needed.
+
+
+elif [[ -n $backup ]]; then
+	check_for_nginx
+	if [[ $backup == "local" ]]; then
+		bkp_local_db
+	elif [[ $backup == "s3" && -n $list ]]; then
+		bkp_s3_list
+	elif [[ $backup == "s3" ]]; then
+		bkp_s3_profile
+	else
+		bkp_wizard
+	fi
+
+
+elif [[ -n $aws_s3_credentials ]]; then
+	if [[ $aws_s3_credentials == true ]]; then
+		echo ""
+		read -p "${blu}Access Key ID: ${end}" user
+		read -p "${blu}Secret Access Key: ${end}" pass
+		echo ""
+	elif [[ $(echo "${aws_s3_credentials}" | cut -c-1) == "[" && $(echo "${aws_s3_credentials}" | rev | cut -c-1) == "]" ]]; then
+		cred=${aws_s3_credentials:1:-1}
+		user=$(echo "${cred}" | cut -d',' -f 1 -s)
+		pass=$(echo "${cred}" | cut -d',' -f 2 -s)
+	else
+		echo "${red}[ERROR] Invalid AWS S3 Credentials!${end}"
+		exit 1
+	fi
+
+	if ! [[ -n $user && -n $pass ]]; then
+		echo "${red}[ERROR] Please, enter a valid AWS S3 Access and Secret Key!${end}"
+		exit 1
+	fi
+
+	sudo rm -rf /root/.aws/credentials
+	sudo mkdir -p /root/.aws
+	sudo touch /root/.aws/credentials
+	sudo echo "[default]
+aws_access_key_id = $user
+aws_secret_access_key = $pass" >> /root/.aws/credentials
+	echo "${gre}AWS S3 Credentials successfully added!${end}"
 
 
 else
