fixed and more
Readme updated.
SSL detection updated now that nginx ssl directive is deprecated.
Yoast sitemap now detect if nginx is installed before throw an error.
Update process now waits until background processes are finished.

diff --git a/plugins/webinoly b/plugins/webinoly
--- a/plugins/webinoly
+++ b/plugins/webinoly
@@ -409,6 +409,11 @@ elif [[ $opt == "-conf-value_"* ]]; then
 
 
 elif [[ $opt == "-yoast-sitemap"* ]]; then
+	if [[ $(conf_read nginx) != "true" ]]; then
+		echo "${red} Nginx not found! ${end}"
+		exit 1
+	fi
+	
 	ystmap=$( grep -F "# YoastSitemapStart - Yoast SEO Plugin" /etc/nginx/common/wpcommon.conf )
 	if [[ $value == "on" ]]; then
 		if [[ -z $ystmap ]]; then
