tools site and port improved
PHP purge now removes tools-site.
Tools-port check for PHP.

diff --git a/plugins/webinoly b/plugins/webinoly
--- a/plugins/webinoly
+++ b/plugins/webinoly
@@ -97,12 +97,16 @@ elif [[ -n $dbpass ]]; then
 	
 	
 elif [[ -n $tools_port ]]; then
+	check_for_php
+	oldport="$(conf_read tools-port)"
 	if [[ -a /etc/nginx/sites-available/$tools_port ]]; then
 		echo "${red}[ERROR] Port/site '$tools_port' is already in use!${end}"
 		exit 1
+	elif [[ ! -a /etc/nginx/sites-available/$oldport ]]; then
+		echo "${red}[ERROR] Site '$oldport' not found!${end}"
+		exit 1
 	fi
 	
-	oldport="$(conf_read tools-port)"
 	[[ $tools_port != true ]] && tools_port $tools_port || tools_port
 	newport="$(conf_read tools-port)"
 	if [[ $oldport != $newport && $(conf_read nginx-tool) == "true" && $(conf_read nginx) == "true" ]]; then
@@ -171,6 +175,7 @@ elif [[ -n $tools_site ]]; then
 		sudo rm -rf /etc/nginx/sites-available/$(conf_read tools-port)
 		sudo cp /opt/webinoly/templates/nginx/22222 /etc/nginx/sites-available/$(conf_read tools-port)
 		sudo sed -i "s/22222/$(conf_read tools-port)/g"  /etc/nginx/sites-available/$(conf_read tools-port)
+		conf_delete tools-site
 		echo "${gre}Tools Site settings has been reset successfully!${end}"
 	elif [[ -a /etc/nginx/sites-available/$tools_site && ! -a /etc/nginx/sites-available/$(conf_read tools-port) ]]; then
 		echo "${red}[ERROR] Tools Site is not enabled! ${end}"
