more wp functions
WP clone now works even if empty site.
Fix site deleted when cloning site with wp subfolder is empty.
Fix multisite-convert error when wp not installed.
Better check for parked sites.
Fix wp subfolder not showing warning messages when creating site.
Fix parked site error when main site is empty root site.
Fix parked site error when main site has wp in subfolders.
WP functions refactored.

diff --git a/lib/bkp b/lib/bkp
--- a/lib/bkp
+++ b/lib/bkp
@@ -42,14 +42,17 @@ bkp_local_db() {
 	fi
 	
 	if [[ -n $wp ]]; then
-		wp_conf_retrieve $wp $subfolder # Here to not ask twice for external-db data
-		if [[ $(is_wp $wp $subfolder) != "true"  ]]; then
+		if [[ ! -f /etc/nginx/sites-available/$wp ]]; then
+			echo "${red}[ERROR] Site not found!${end}"
+			exit 1
+		elif [[ $(is_wp $wp $subfolder) != "true"  ]]; then
 			echo "${red}[ERROR] Please, enter a valid WP site!${end}"
 			exit 1
 		elif [[ $(is_wp_installed $wp $subfolder) != "true"  ]]; then
 			echo "${red}[ERROR] Your WP site database is still empty!${end}"
 			exit 1
 		else
+			wp_conf_retrieve $wp $subfolder
 			local dbname=$wp_dbname
 			local dburl=$wp_dburl
 			local dbport=$wp_dbport
diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -5,6 +5,19 @@
 source /opt/webinoly/lib/site-ssl
 
 
+warning_messages() {
+	# Warning Messages
+	if [[ $warning_mes != "true" ]]; then
+		if [[ $type == [123] && $(conf_read wp-admin-auth) != "purged" && ! -s /etc/nginx/.htpasswd && ! -s /etc/nginx/apps.d/.htpasswd-$domain ]]; then
+			echo "${dim}[WARNING] HTTP Authentication Credentials not found and you may need it to complete the WordPress installation process!!${end}"
+		fi
+		if [[ $(conf_read login-www-data) != "true" && -z $forward && -z $proxy && -z $parked ]]; then
+			echo "${dim}[WARNING] Login for www-data is not enabled and you may need it to upload your site files!${end}"
+		fi
+		warning_mes="true"
+	fi
+}
+
 wp_cache_plugins() {
 	api-events_update si3
 	
@@ -469,6 +482,7 @@ _EOF_
 		wp_config_write $domain WP_CACHE_KEY_SALT \'wp_$domain$(echo $subfolder | sed "s/\//_/g")\' $subfolder
 	fi
 	
+	warning_messages
 }
 
 
@@ -659,14 +673,7 @@ createsite() {
 	sudo chown -R www-data:www-data /var/www
 	[[ $(conf_read login-www-data) == "true" ]] && sudo chown root:root /var/www
 
-	# Warning Messages
-	if [[ $type == [123] && $(conf_read wp-admin-auth) != "purged" && ! -s /etc/nginx/.htpasswd && ! -s /etc/nginx/apps.d/.htpasswd-$domain ]]; then
-		echo "${dim}[WARNING] HTTP Authentication Credentials not found and you may need it to complete the WordPress installation process!!${end}"
-	fi
-	if [[ $(conf_read login-www-data) != "true" && -z $forward && -z $proxy && -z $parked ]]; then
-		echo "${dim}[WARNING] Login for www-data is not enabled and you may need it to upload your site files!${end}"
-	fi
-
+	warning_messages
 	echo "${gre}Site${blu} $domain$subfolder ${gre}has been successfully created!${end}"
 }
 
@@ -1054,6 +1061,9 @@ parked_domain() {
 	elif [[ $(is_parked $parked) == "true" ]]; then
 		echo "${red}[ERROR] Parking a site using a parked site as main site is not allowed! ${end}"
 		exit 1
+	elif [[ $(is_empty_root_site $parked) == "true" ]]; then
+		echo "${red}[ERROR] Invalid main site!${end}"
+		exit 1
 	fi
 	
 	createsite
@@ -1074,6 +1084,10 @@ parked_domain() {
 	sudo sed -i "s/$parked/$domain/g"  /etc/nginx/sites-available/$domain
 	sudo sed -i "/include apps.d\/.*-proxy.conf;/{s/$domain/$parked/g}"  /etc/nginx/sites-available/$domain
 	sudo sed -i "/root/c \	root /var/www/$parked/htdocs;" /etc/nginx/sites-available/$domain
+	
+	# Remove any conf file, this means we will not have subfolder support for parked sites, Should it be supported?
+	sudo sed -i "/WebinolyCustom/,/WebinolyCustomEnd/ {/include apps.d\/${domain}.*conf;/d}" /etc/nginx/sites-enabled/$domain
+	
 	cusconl=$( grep -o "include /var/www/$domain/.*" /etc/nginx/sites-available/$domain | sed "s/$domain/$parked/" )
 	sed -i "/include \/var\/www\/$domain/c \	${cusconl}" /etc/nginx/sites-available/$domain
 	
@@ -1254,6 +1268,9 @@ yoast_sitemap() {
 
 
 clone_wp_site() {
+	if [[ $(is_wp_installed $clone_from $subfolder) != "true" ]]; then
+		echo "${dim}[INFO] WordPress is empty and still not configured in ${clone_from}${subfolder} site!${end}"
+	fi
 	if [[ -f /etc/nginx/sites-available/$domain && $overwrite == "on" ]]; then
 		echo "${blu}Site already exists! ${dim} Overwriting...${end}"
 		[[ -z $subfolder ]] && sudo site $domain -delete=force > /dev/null 2>&1 || sudo site $domain -subfolder=$subfolder -delete=force > /dev/null 2>&1
@@ -1530,6 +1547,9 @@ site_info() {
 wp_env_type() {
 	if [[ $(is_wp $domain $subfolder) != "true" ]]; then
 		echo "${red}[ERROR] Site${blu} $domain ${red}is not a WordPress site!${end}"
+		exit 1
+	elif [[ $(is_parked $domain) == "true" ]]; then
+		echo "${red}[ERROR] Parked sites not allowed! ${dim}(Env type should be changed in main site)${end}"
 		exit 1
 	elif ! [[ $env =~ ^(production|staging|development|local)$ ]]; then
 		echo "${red}[ERROR] Invalid value for WP environment type!${end}"
diff --git a/plugins/log b/plugins/log
--- a/plugins/log
+++ b/plugins/log
@@ -292,6 +292,11 @@ elif [[ -n $domain && -f /etc/nginx/sites-available/$domain ]]; then
 	fi
 	
 	# WordPress Logs
+	if [[ -n $wp && $(is_parked $domain) == "true" ]]; then
+		echo "${red}[ERROR] Parked sites not allowed! ${dim}(WP debug should be used in main site)${end}"
+		exit 1
+	fi
+	
 	if [[ -n $wp && $(is_wp $domain $subfolder) == "true" ]]; then
 		iswpdeb=$( is_wp_debug $domain $subfolder )
 		
diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -228,6 +228,9 @@ elif [[ -n $multisite_convert && -f /etc/nginx/sites-available/$domain ]]; then
 	if [[ $(is_wp $domain $subfolder) == "false" ]]; then
 		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is not a WP site!${end}"
 		exit 1
+	elif [[ $(is_wp_installed $domain $subfolder) != "true" ]]; then
+		echo "${red}[ERROR] WordPress site${blu} $domain$subfolder ${red}is empty and still not configured!${end}"
+		exit 1
 	elif [[ $(is_parked $domain) == "true" ]]; then
 		echo "${red}[ERROR] Multisite conversion in a parked site is not allowed!${end}"
 		exit 1
@@ -412,10 +415,7 @@ elif [[ -n $clone_from ]]; then
 		exit 1
 	fi
 	
-	if [[ $(is_wp_installed $clone_from $subfolder) != "true" ]]; then
-		echo "${red}[ERROR] Seems like WordPress is still not configured in your${blu} '${clone_from}${subfolder}' ${red}site!${end}"
-		exit 1
-	elif [[ $(is_wp_multisite $clone_from $subfolder) != "false" ]]; then
+	if [[ $(is_wp_multisite $clone_from $subfolder) != "false" ]]; then
 		echo "${red}[ERROR] WordPress Multisite can not be cloned!${end}"
 		exit 1
 	else
