top issues
- local DB backup using dbname not taking external db data saved.
- Clone WP error when multisite.
- Tools site not updated with SSL.
- Better error when deleting a WP site and mysql is not installed.
- Site list showing "false" value for root empty sites.
- added site counter in site list.

diff --git a/lib/bkp b/lib/bkp
--- a/lib/bkp
+++ b/lib/bkp
@@ -57,7 +57,21 @@ bkp_local_db() {
 			local proot=$wp_proot
 		fi
 	else
+		if [[ -n $(conf_read external-dbu) && -n $(conf_read external-dbp) && -n $(conf_read external-dbh) ]]; then
+			local uroot=$(conf_read external-dbu)
+			local proot=$( echo $(conf_read external-dbp) | openssl enc -d -a -salt )
+			local dburl=$(conf_read external-dbh)
+			[[ -n $(conf_read external-dbx) ]] && local dbport=$(conf_read external-dbx) || local dbport="3306"
+			
+			external_db="[$uroot,$proot,${dburl}:${dbport}]"
+			echo "${blu}External DB credentials found!${end}" >&2
+		fi
+		
 		if [[ -z $external_db ]]; then
+			if [[ $(check_mysql_connection localhost) != "true" ]]; then
+				echo "${red}[ERROR] Cannot connect with your database (localhost)!${end}"
+				exit 1
+			fi
 			local checkdbname=$(sudo mysqlshow --user=admin -p$ADMIN_PASS | grep -ow $dbname)
 		else
 			local dbdata=${external_db:1:-1}
diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -417,8 +417,8 @@ db_delete() {
 	[[ -z $wpconfpath ]] && return
 	[[ $wp_dbhost != "localhost" ]] && check_for_mysql_client
 	
-	if [[ ( $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) != "true" ) ]]; then
-		echo "[ERROR] Database cannot be deleted${blu} $domain ${end}"
+	if [[ ( $wp_dbhost == "localhost" &&  ( $(conf_read mysql) != "true" || $(check_mysql_connection localhost) != "true" )) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) != "true" ) ]]; then
+		echo "${red}[ERROR] Database${blu} $domain ${red}cannot be deleted!${end}"
 		return
 	fi
 	
@@ -1389,9 +1389,10 @@ list_sites() {
 		if [[ -n $outlist ]]; then
 			echo "$outlist"
 			local nonemptylist=true
+			local count=$(($count+1))
 		fi
 	done
-	[[ -z $nonemptylist && -z $raw && $list != "raw" ]] && echo "${blu}[Empty] No sites were found!${end}"
+	[[ -z $nonemptylist && -z $raw && $list != "raw" ]] && echo "${blu}[Empty] No sites were found!${end}" || echo -e "\n${blu}Found:${end} $count sites"
 	echo ""
 }
 
@@ -1413,8 +1414,9 @@ site_info() {
 		echo "${blu}SSL:${end} $(is_ssl $domain)"
 		echo "${blu}Access Logs:${end} $(is_log $domain)"
 		echo "${blu}Force Redirect:${end} $(is_force_redirect $domain)"
-		[[ $typesite != "Parked" && $typesite != "Reverse Proxy" ]] && echo "${blu}Size:${end} $(sudo du -sh /var/www/$domain | cut -d"/" -f 1 -s)"
 	fi
+	
+	[[ $typesite =~ ^(Forward|Parked|Reverse Proxy) ]] || echo "${blu}Size:${end} $(sudo du -sh /var/www/$domain | cut -d"/" -f 1 -s)"
 	
 	if [[ $typesite == "WordPress" ]]; then
 		echo ""
diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -415,6 +415,9 @@ elif [[ -n $clone_from ]]; then
 	if [[ $(is_wp_installed $clone_from) != "true" ]]; then
 		echo "${red}[ERROR] Seems like WordPress is still not configured in your${blu} '${clone_from}${subfolder}' ${red}site!${end}"
 		exit 1
+	elif [[ $(is_wp_multisite $clone_from) != "false" ]]; then
+		echo "${red}[ERROR] WordPress Multisite can not be cloned!${end}"
+		exit 1
 	else
 		clone_wp_site
 	fi
