extdb functions
Improved functions for external databases.

diff --git a/lib/bkp b/lib/bkp
--- a/lib/bkp
+++ b/lib/bkp
@@ -48,27 +48,34 @@ bkp_local_db() {
 		elif [[ $(is_wp $wp $subfolder) != "true"  ]]; then
 			echo "${red}[ERROR] Please, enter a valid WP site!${end}"
 			exit 1
+		else
+			wp_conf_retrieve $wp $subfolder
+		fi
+		
+		if [[ $wp_dbhost != "localhost" && ( -z $extdb_user || -z $extdb_pass || -z $extdb_url || -z $extdb_port ) ]]; then
+			echo "${red}[ERROR] Invalid data for External Database!${end}"
+			exit 1
+		
+		# Duplicate check: we need this only to prevent error in the next is_wp_installed
+		elif [[ $wp_dbhost != "localhost" && $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ]]; then
+			echo "${red}[ERROR] External DB Connection failed!${end}"
+			exit 1
+		elif [[ $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ]]; then
+			echo "${red}[ERROR] Localhost DB Connection failed!${end}"
+			exit 1
+			
 		elif [[ $(is_wp_installed $wp $subfolder) != "true"  ]]; then
 			echo "${red}[ERROR] Your WP site database is still empty!${end}"
 			exit 1
 		else
-			wp_conf_retrieve $wp $subfolder
 			local dbname=$wp_dbname
-			local dburl=$wp_dburl
-			local dbport=$wp_dbport
-			local uroot=$wp_uroot
-			local proot=$wp_proot
+			local extdb_url=$extdb_url
+			local extdb_port=$extdb_port
+			local extdb_user=$extdb_user
+			local extdb_pass=$extdb_pass
 		fi
 	else
-		if [[ -n $(conf_read external-dbu) && -n $(conf_read external-dbp) && -n $(conf_read external-dbh) ]]; then
-			local uroot=$(conf_read external-dbu)
-			local proot=$( echo $(conf_read external-dbp) | openssl enc -d -a -salt )
-			local dburl=$(conf_read external-dbh)
-			[[ -n $(conf_read external-dbx) ]] && local dbport=$(conf_read external-dbx) || local dbport="3306"
-			
-			external_db="[$uroot,$proot,${dburl}:${dbport}]"
-			echo "${blu}External DB credentials found!${end}" >&2
-		fi
+		check_external_db_saved
 		
 		if [[ -z $external_db ]]; then
 			if [[ $(check_mysql_connection localhost) != "true" ]]; then
@@ -77,22 +84,8 @@ bkp_local_db() {
 			fi
 			local checkdbname=$(sudo mysqlshow --user=admin -p$ADMIN_PASS | grep -ow $dbname)
 		else
-			local dbdata=${external_db:1:-1}
-			local uroot=$(echo "${dbdata}" | cut -d',' -f 1 -s)
-			local proot=$(echo "${dbdata}" | cut -d',' -f 2 -s)
-			local dbhost=$(echo "${dbdata}" | cut -d',' -f 3 -s)
-			local dburl=$(echo "$dbhost" | cut -f 1 -d ':')
-			local dbport=$(echo "$dbhost" | cut -f 2 -d ':' -s)
-		
-			if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" || -z $uroot || -z $proot || -z $dburl || -z $dbport ]]; then
-				echo "${red}[ERROR] Invalid data for External Database!${end}"
-				exit 1
-			elif [[ $(check_mysql_connection $dburl $dbport $uroot $proot) != "true" ]]; then
-				echo "${red}[ERROR] Cannot connect with your External Database!${end}"
-				exit 1
-			fi
-			
-			local checkdbname=$(sudo mysqlshow -h "$dburl" -P "$dbport" -u"$uroot" -p"$proot" | grep -ow $dbname)
+			external_db_parse
+			local checkdbname=$(sudo mysqlshow -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" | grep -ow $dbname)
 		fi
 		
 		if [[ $checkdbname != $dbname  ]]; then
@@ -119,11 +112,12 @@ bkp_local_db() {
 		exit 1
 	fi
 	
+	echo "${blu}${dim}Backup is in process, wait...${end}"
 	[[ -z $filename ]] && local filename="webinoly-backup-db_${fn}_$(date +%F)-$(date +%T).sql"
 	if [[ ( $wp_dbhost == "localhost" || -z $external_db ) && $(check_mysql_connection localhost) == "true" ]]; then
 		sudo mysqldump --user=admin --password=$ADMIN_PASS --single-transaction --lock-tables --quick --databases $dbname > $destination/$filename
-	elif [[ $(check_mysql_connection $dburl $dbport $uroot $proot) == "true" ]]; then
-		sudo mysqldump -h "$dburl" -P "$dbport" -u"$uroot" -p"$proot" --single-transaction --lock-tables --quick --databases $dbname > $destination/$filename
+	elif [[ $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) == "true" ]]; then
+		sudo mysqldump -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" --single-transaction --lock-tables --quick --databases $dbname > $destination/$filename
 	else
 		echo "${red}[ERROR] DB Connection failed!${end}"
 		exit 1
diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -221,6 +221,61 @@ check_mysql_connection() {
 }
 
 
+check_external_db_saved() {
+	if [[ -n $(conf_read external-dbh) && -n $(conf_read external-dbu) && -n $(conf_read external-dbp) && -n $(conf_read external-dbx) ]]; then
+		external_db="[$(conf_read external-dbu),$( echo $(conf_read external-dbp) | openssl enc -d -a -salt ),$(conf_read external-dbh):$(conf_read external-dbx)]"
+		[[ $(conf_read quiet) != "true" ]] && echo "${blu}${dim}External DB credentials found!${end}" >&2
+	fi
+}
+
+
+external_db_parse() {
+	if [[ -n $external_db ]]; then
+		# Prevent errors
+		if [[ ${#external_db} -lt 2 ]]; then
+			echo "${red}[ERROR] Invalid data for External Database!${end}"
+			exit 1
+		fi
+		
+		local dbdata=${external_db:1:-1}
+		local user=$(echo "${dbdata}" | cut -d',' -f 1 -s)
+		local pass=$(echo "${dbdata}" | cut -d',' -f 2 -s)
+		local host=$(echo "${dbdata}" | cut -d',' -f 3 -s)
+		local url=$(echo "$host" | cut -f 1 -d ':')
+		local port=$(echo "$host" | cut -f 2 -d ':' -s)
+		
+		if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" ]]; then
+			echo "${red}[ERROR] Invalid syntax for External Database!${end}"
+			exit 1
+		elif [[ $1 == "-nohost" && ( -z $user || -z $pass ) ]]; then
+			echo "${red}[ERROR] Invalid data for External Database!${end}"
+			exit 1
+		elif [[ $1 != "-nohost" && ( -z $user || -z $pass || -z $url || -z $port ) ]]; then
+			echo "${red}[ERROR] Invalid data for External Database!${end}"
+			exit 1
+		fi
+		
+		check_for_mysql_client
+		if [[ $(check_mysql_connection $url $port $user $pass) != "true" ]]; then
+			echo "${red}[ERROR] Cannot connect with your External Database!${end}"
+			exit 1
+		else
+			# Make it global only after verification
+			extdb_user=$user
+			extdb_pass=$pass
+			if [[ $1 != "-nohost" ]]; then
+				extdb_host=$host
+				extdb_url=$url
+				extdb_port=$port
+			fi
+		fi
+	else
+		echo "${red}[ERROR] External DB parameter not found!${end}"
+		exit 1
+	fi
+}
+
+
 wp_config_path() {
 	# If this file exist is because is WP parked
 	# We can not use is_parked here because it will cause an infinite loop (is_parked uses this function)
@@ -301,34 +356,28 @@ wp_conf_retrieve() {
 	wp_dbuser=$( wp_config_read $1 DB_USER $2 )
 	wp_dbhost=$( wp_config_read $1 DB_HOST $2 )
 	wp_dbpass=$( wp_config_read $1 DB_PASSWORD $2 )
-	wp_dburl=$(echo "$wp_dbhost" | cut -f 1 -d ':')
-	wp_dbport=$(echo "$wp_dbhost" | cut -f 2 -d ':' -s)
 	wp_dbpref=$( grep -F "table_prefix" $wp_config | cut -f 2 -d "'" -s)
+	extdb_url=$(echo "$wp_dbhost" | cut -f 1 -d ':')
+	extdb_port=$(echo "$wp_dbhost" | cut -f 2 -d ':' -s)
 	
 	[[ ${wp_dbhost,,} == "localhost" ]] && wp_dbhost=${wp_dbhost,,}
-	[[ -z $wp_dbport ]] && wp_dbport="3306"
+	[[ -z $extdb_port ]] && extdb_port="3306"
 	
 	if [[ $3 != "false" ]]; then
+		if [[ -z $external_db && -n $wp_dbhost && $wp_dbhost != "localhost" && $wp_dbhost == "$(conf_read external-dbh):$(conf_read external-dbx)" ]]; then
+			check_external_db_saved
+		elif [[ -z $external_db && -n $wp_dbhost && $wp_dbhost != "localhost" && -n $(conf_read external-dbh) && $wp_dbhost != "$(conf_read external-dbh):$(conf_read external-dbx)" ]]; then
+			echo "${dim}[INFO] External Database saved credentials found, but we cannot use it because not the same host!${end}"
+		fi
+		
 		if [[ -n $external_db ]]; then
-			local dbdata=${external_db:1:-1}
-			wp_uroot=$(echo "${dbdata}" | cut -d',' -f 1 -s)
-			wp_proot=$(echo "${dbdata}" | cut -d',' -f 2 -s)
-			if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" || -z $wp_uroot || -z $wp_proot ]]; then
-				echo "${red}[ERROR] Invalid data for External Database!${end}" >&2
-				exit 1
-			fi
-		elif [[ -n $(conf_read external-dbu) && -n $(conf_read external-dbp) && -n $wp_dbhost && $wp_dbhost != "localhost" ]]; then
-			wp_uroot=$(conf_read external-dbu)
-			wp_proot=$( echo $(conf_read external-dbp) | openssl enc -d -a -salt )
-			external_db="[$wp_uroot,$wp_proot]"
-			echo "${blu}External DB credentials found!${end}" >&2
+			external_db_parse -nohost
 		elif [[ -z $external_db && -n $wp_dbhost && $wp_dbhost != "localhost" ]]; then
 			echo "" >&2
-			echo "${gre}External DB${blu} '${wp_dburl}:${wp_dbport}' ${gre}found in${blu} $1 ${gre}(Press 'Enter' key twice to skip)" >&2
-			read -p "${blu}External DB username: " wp_uroot
-			read -p "External DB password: " wp_proot
-			
-			external_db="[$wp_uroot,$wp_proot]"
+			echo "${gre}External DB${blu} '${extdb_url}:${extdb_port}' ${gre}found in${blu} $1 ${gre}(Press 'Enter' key twice to skip)" >&2
+			read -p "${blu}External DB username: " extdb_user
+			read -p "External DB password: " extdb_pass
+			external_db="[$extdb_user,$extdb_pass,${wp_dbhost}:${wp_dbport}]"
 		fi
 	fi
 }
@@ -649,9 +698,9 @@ is_wp_multisite() {
 	if [[ $wp_dbhost == "localhost" && $(check_mysql_connection localhost) == "true" ]]; then
 		wpmu=$(sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "$dbsetup")
 		[[ -n $wpmu ]] && mutype=$(sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "$dbsetuc")
-	elif [[ $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) == "true" ]]; then
-		wpmu=$(sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup")
-		[[ -n $wpmu ]] && mutype=$(sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetuc")
+	elif [[ $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) == "true" ]]; then
+		wpmu=$(sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" -e "$dbsetup")
+		[[ -n $wpmu ]] && mutype=$(sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" -e "$dbsetuc")
 	fi
 	
 	if [[ $(echo $mutype | cut -f 2 -d " " -s) == "1" ]]; then
@@ -673,8 +722,8 @@ is_wp_installed() {
 	
 	if [[ $wp_dbhost == "localhost" && $(check_mysql_connection localhost) == "true" ]]; then
 		[[ -n $(sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "$dbsetup") ]] && echo "true" || echo "false"
-	elif [[ $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) == "true" ]]; then
-		[[ -n $(sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup") ]] && echo "true" || echo "false"
+	elif [[ $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) == "true" ]]; then
+		[[ -n $(sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" -e "$dbsetup") ]] && echo "true" || echo "false"
 	else
 		echo "false"
 	fi
@@ -833,8 +882,8 @@ UPDATE ${wp_dbpref}options SET option_value='$2' WHERE option_name='siteurl';
 FLUSH PRIVILEGES;
 _EOF_
 
-		elif [[ $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) == "true" ]]; then
-			sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" <<_EOF_
+		elif [[ $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) == "true" ]]; then
+			sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" <<_EOF_
 USE $wp_dbname;
 UPDATE ${wp_dbpref}options SET option_value='$2' WHERE option_name='home';
 UPDATE ${wp_dbpref}options SET option_value='$2' WHERE option_name='siteurl';
diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -491,7 +491,7 @@ db_delete() {
 	[[ -z $wp_config ]] && return
 	[[ $wp_dbhost != "localhost" ]] && check_for_mysql_client
 	
-	if [[ ( $wp_dbhost == "localhost" &&  ( $(conf_read mysql) != "true" || $(check_mysql_connection localhost) != "true" )) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) != "true" ) ]]; then
+	if [[ ( $wp_dbhost == "localhost" &&  ( $(conf_read mysql) != "true" || $(check_mysql_connection localhost) != "true" )) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ) ]]; then
 		echo "${red}[ERROR] Database${blu} $domain ${red}cannot be deleted!${end}"
 		return
 	fi
@@ -501,10 +501,10 @@ db_delete() {
 		sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "$dbsetup"
 		echo "${gre}Database of your site ${blu}${domain}${subfolder}${gre} has been successfully deleted! ${end}"
 	else
-		if [[ $wp_uroot == "root" && -z $wp_proot ]]; then
+		if [[ $extdb_user == "root" && -z $extdb_pass ]]; then
 			echo "${red}Action aborted, database not deleted!${end}"
 		else
-			sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup"
+			sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" -e "$dbsetup"
 			echo "${gre}Database of your site ${blu}${domain}${subfolder}${gre} has been successfully deleted! ${end}"
 		fi
 	fi
@@ -1000,6 +1000,7 @@ wp_multisite_convertion() {
 	echo "Write ${end}'quit'${blu} and press ${end}<Enter>${blu} to exit and abort this operation."
 	echo "${end}"
 	
+	conf_write quiet true
 	while [[ -z $passed || $passed == "false" ]]; do
 		if read -t0; then
 			read pas
@@ -1008,6 +1009,7 @@ wp_multisite_convertion() {
 		sleep 2
 		passed=$(is_wp_multisite $domain $subfolder)
 	done
+	conf_delete quiet
 	
 	if [[ $passed == "false" && $pas == "quit" ]]; then
 		wp_config_delete $domain WP_ALLOW_MULTISITE $subfolder
@@ -1124,6 +1126,13 @@ reverse_proxy() {
 	if [[ $proxy != true ]]; then
 		firstchar=$(echo "${proxy}" | cut -c-1)
 		lastchar=$(echo "${proxy}" | rev | cut -c-1)
+		
+		# Prevent errors
+		if [[ ${#proxy} -lt 2 ]]; then
+			echo "${red}[ERROR] Invalid data for proxy!${end}"
+			exit 1
+		fi
+		
 		proxydata=${proxy:1:-1}
 		[[ $firstchar != "[" || $lastchar != "]" ]] && proxydata=""
 	else
@@ -1353,8 +1362,8 @@ clone_wp_site() {
 		mysqldump -u admin -p$ADMIN_PASS $wp_dbname | mysql -u admin -p$ADMIN_PASS $dom
 		edit_wp_db_url $domain "http://${domain}${subfolder}" $subfolder
 	else
-		site -mysql=[$wp_dbhost,$dom,$dom,$AUTOGENPASS_WPDB,$wp_uroot,$wp_proot] > /dev/null 2>&1
-		mysqldump -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" $wp_dbname | mysql -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" $dom
+		site -mysql=[$wp_dbhost,$dom,$dom,$AUTOGENPASS_WPDB,$extdb_user,$extdb_pass] > /dev/null 2>&1
+		mysqldump -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" $wp_dbname | mysql -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" $dom
 		edit_wp_db_url $domain "http://${domain}${subfolder}" $subfolder
 	fi
 	
@@ -1379,6 +1388,12 @@ wp_replace_content() {
 		read -p "${blu}Replace with: ${end}" replace
 		echo ""
 	elif [[ $(echo "${replace_content}" | cut -c-1) == "[" && $(echo "${replace_content}" | rev | cut -c-1) == "]" ]]; then
+		# Prevent errors
+		if [[ ${#replace_content} -lt 2 ]]; then
+			echo "${red}[ERROR] Invalid data for Replace-Content!${end}"
+			exit 1
+		fi
+		
 		userdata=${replace_content:1:-1}
 		search=$(echo "${userdata}" | cut -d',' -f 1 -s)
 		replace=$(echo "${userdata}" | cut -d',' -f 2 -s)
@@ -1390,7 +1405,7 @@ wp_replace_content() {
 	fi
 	
 	wp_conf_retrieve $domain $subfolder
-	if [[ ( $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) != "true" ) ]]; then
+	if [[ ( $wp_dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $wp_dbhost != "localhost" && $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ) ]]; then
 		exit 1
 	fi
 	
@@ -1399,7 +1414,7 @@ wp_replace_content() {
 	if [[ $wp_dbhost == "localhost" ]]; then
 		sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "$query"
 	else
-		sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$query"
+		sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" -e "$query"
 	fi
 	echo "${gre}Content successfully replaced in your WP site!${end}"
 }
@@ -1597,8 +1612,8 @@ UPDATE ${wp_dbpref}options SET option_value='$index' WHERE option_name='blog_pub
 FLUSH PRIVILEGES;
 _EOF_
 		
-		elif [[ $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) == "true" ]]; then
-			sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" <<_EOF_
+		elif [[ $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) == "true" ]]; then
+			sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" <<_EOF_
 USE $wp_dbname;
 UPDATE ${wp_dbpref}options SET option_value='$index' WHERE option_name='blog_public';
 FLUSH PRIVILEGES;
diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -598,6 +598,7 @@ smtp_setup() {
 		[[ -z $mainhost && -n $default_host ]] && mainhost=$hostname
 		echo ""
 	elif [[ $(echo "${smtp}" | cut -c-1) == "[" && $(echo "${smtp}" | rev | cut -c-1) == "]" ]]; then
+		# No need for check var lenght to prevent errors, the previous condition is enough in this case.
 		userdata=${smtp:1:-1}
 		host=$(echo "${userdata}" | cut -d',' -f 1 -s)
 		user=$(echo "${userdata}" | cut -d',' -f 2 -s)
@@ -678,6 +679,7 @@ mysql_change_password() {
 		read -p "${blu}New Password: ${end}" pass
 		echo ""
 	elif [[ $(echo "${mysql_password}" | cut -c-1) == "[" && $(echo "${mysql_password}" | rev | cut -c-1) == "]" ]]; then
+		# No need for check var lenght to prevent errors, the previous condition is enough in this case.
 		userdata=${mysql_password:1:-1}
 		user=$(echo "${userdata}" | cut -d',' -f 1 -s)
 		pass=$(echo "${userdata}" | cut -d',' -f 2 -s)
@@ -1087,6 +1089,8 @@ config_fastcgi_cache() {
 	elif [[ $(echo "${config_cache}" | cut -c-1) == "[" && $(echo "${config_cache}" | rev | cut -c-1) == "]" ]]; then
 		custombegin=$(echo "${config_cache}" | cut -c-1)
 		customlast=$(echo "${config_cache}" | rev | cut -c-1)
+		
+		# No need for check var lenght to prevent errors, the previous condition is enough in this case.
 		cachedata=${config_cache:1:-1}
 			
 		hit=$(echo "${cachedata}" | cut -d',' -f 1 )
@@ -1335,6 +1339,7 @@ aws_s3_credentials() {
 		read -p "${blu}Secret Access Key: ${end}" pass
 		echo ""
 	elif [[ $(echo "${aws_s3_credentials}" | cut -c-1) == "[" && $(echo "${aws_s3_credentials}" | rev | cut -c-1) == "]" ]]; then
+		# No need for check var lenght to prevent errors, the previous condition is enough in this case.
 		cred=${aws_s3_credentials:1:-1}
 		user=$(echo "${cred}" | cut -d',' -f 1 -s)
 		pass=$(echo "${cred}" | cut -d',' -f 2 -s)
@@ -1828,34 +1833,13 @@ database_import() {
 		exit 1
 	fi
 	
-	if [[ -n $(conf_read external-dbh) && -n $(conf_read external-dbu) && -n $(conf_read external-dbp) ]]; then
-		[[ -n $(conf_read external-dbx) ]] && local exthost="$(conf_read external-dbh):$(conf_read external-dbx)" || local exthost="$(conf_read external-dbh)"
-		external_db="[$(conf_read external-dbu),$( echo $(conf_read external-dbp) | openssl enc -d -a -salt ),$exthost]"
-		echo "${blu}External DB credentials found!${end}"
-	fi
+	check_external_db_saved
 	
 	if [[ -n $external_db ]]; then
-		check_for_mysql_client
-		local dbdata=${external_db:1:-1}
-		local uroot=$(echo "${dbdata}" | cut -d',' -f 1 -s)
-		local proot=$(echo "${dbdata}" | cut -d',' -f 2 -s)
-		local dbhost=$(echo "${dbdata}" | cut -d',' -f 3 -s)
-		local dburl=$(echo "$dbhost" | cut -f 1 -d ':')
-		local dbport=$(echo "$dbhost" | cut -f 2 -d ':' -s)
-	
-		if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" || -z $uroot || -z $proot || -z $dburl || -z $dbport ]]; then
-			echo "${red}[ERROR] Invalid data for External Database!${end}"
-			exit 1
-		elif [[ $(check_mysql_connection $dburl $dbport $uroot $proot) != "true" ]]; then
-			echo "${red}[ERROR] Cannot connect with your External Database!${end}"
-			exit 1
-		fi
-	fi
-	
-	if [[ -n $external_db ]]; then
+		external_db_parse
 		echo "${dim}Wait while we import your db... ${end}"
-		sudo mysql --connect-timeout=10 -h "$dburl" -P "$dbport" -u"$uroot" -p"$proot" < $file
-		sudo mysql --connect-timeout=10 -h "$dburl" -P "$dbport" -u"$uroot" -p"$proot" -e "FLUSH PRIVILEGES;"
+		sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" < $file
+		sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" -e "FLUSH PRIVILEGES;"
 		echo "${gre}Database successfully imported!${end}"
 	elif [[ -z $external_db && $(check_mysql_connection localhost) == "true" ]]; then
 		check_for_mysql -ask
@@ -2071,39 +2055,40 @@ if (\$arg_${value}) {
 
 ext_db_save() {
 	if [[ $external_db_save == "true" ]]; then
+		read -p "${blu} Host: ${end}" host
 		read -p "${blu} User: ${end}" user
 		read -p "${blu} Password: ${end}" pass
 		
-		if [[ -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
+		if [[ -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
+			echo "${red}[ERROR] Invalid data for External Database!${end}"
+			exit 1
+		fi
+	else
+		# Prevent errors
+		if [[ ${#external_db_save} -lt 2 ]]; then
 			echo "${red}[ERROR] Invalid data for External Database!${end}"
 			exit 1
 		fi
 		
-		read -p "${blu} Host: ${end}" host
-	else
 		local dbdata=${external_db_save:1:-1}
 		local user=$(echo "${dbdata}" | cut -d',' -f 1 -s)
 		local pass=$(echo "${dbdata}" | cut -d',' -f 2 -s)
 		local host=$(echo "${dbdata}" | cut -d',' -f 3 -s)
 		
-		if [[ $(echo "${external_db_save}" | cut -c-1) != "[" || $(echo "${external_db_save}" | rev | cut -c-1) != "]" || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
+		if [[ $(echo "${external_db_save}" | cut -c-1) != "[" || $(echo "${external_db_save}" | rev | cut -c-1) != "]" || -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
 			echo "${red}[ERROR] Invalid data for External Database!${end}"
 			exit 1
 		fi
 	fi
 	
-	if [[ -n $host ]]; then
-		is_url $host -split
-		if [[ -z $url_path && $(is_url $host) =~ ^(http|https|ip|true)$ ]]; then
-			conf_write external-dbh $url_host
-			[[ -n $url_port ]] && conf_write external-dbx $url_port || conf_delete external-dbx
-		else
-			echo "${red}[ERROR] Invalid database host/port!${end}"
-			exit 1
-		fi
+	
+	is_url $host -split
+	if [[ -z $url_path && $(is_url $host) =~ ^(http|https|ip|true)$ && -n $url_host && -n $url_port ]]; then
+		conf_write external-dbh $url_host
+		conf_write external-dbx $url_port
 	else
-		conf_delete external-dbh
-		conf_delete external-dbx
+		echo "${red}[ERROR] Invalid database host/port!${end}"
+		exit 1
 	fi
 	
 	conf_write external-dbu $user
