bkp improvs
Custom filename support for import/export.
Custom destination support for export.
Blocked IPs included in export file.
Raw option support for add-db-pre lists.

diff --git a/lib/bkp b/lib/bkp
--- a/lib/bkp
+++ b/lib/bkp
@@ -95,11 +95,9 @@ bkp_local_db() {
 		
 	fi
 	
-	# Always go with default path, except if parameter is entered and empty
-	[[ $destination == "true" ]] && read -p "${gre}Destination: ${end}" destination
 	[[ -n $wp ]] && local fn=$wp || local fn=$dbname
 	
-	if [[ -z $destination || $destination == "default" ]]; then
+	if [[ -z $destination || $destination =~ ^(default|true)$ ]]; then
 		destination="$HOME/webinoly-backups/$fn"
 		sudo mkdir -p $destination
 	
@@ -211,12 +209,14 @@ bkp_s3_profile() {
 		check_duply_profile
 		
 		if [[ -s $HOME/.duply/$profile/pre ]]; then
-			echo ""
-			echo "${gre}The following lines will be executed every time just before (PRE)${blu} '$profile' ${gre}backup is run:${blu}"
+			if [[ -z $raw ]]; then
+				echo ""
+				echo "${gre}The following lines will be executed every time just before (PRE)${blu} '$profile' ${gre}backup is run:${blu}"
+			fi
 			cat $HOME/.duply/$profile/pre
-			echo "${end}"
+			[[ -z $raw ]] && echo "${end}"
 		else
-			echo "${red}[ERROR] PRE Database backups is empty!${end}"
+			[[ -z $raw ]] && echo "${red}[ERROR] PRE Database backups is empty!${end}"
 			exit 1
 		fi
 	
@@ -450,7 +450,20 @@ check_exported_conf() {
 
 
 export_server() {
-	local filename="webinoly_full_backup_$(date +%F)-$(date +%T)"
+	[[ -z $filename ]] && local filename="webinoly_full_backup_$(date +%F)-$(date +%T)"
+	
+	if [[ -z $destination || $destination =~ ^(default|true)$ ]]; then
+		destination="$HOME"
+		sudo mkdir -p $destination
+	
+	# Must start with / and can not end with /
+	elif [[ ! -d $destination && $(echo "${destination}" | cut -c-1) == "/" && $(echo "${destination}" | rev | cut -c-1) != "/" ]]; then
+		sudo mkdir -p $destination
+	fi
+	if [[ ! -d $destination || $(echo "${destination}" | rev | cut -c-1) == "/" ]]; then
+		echo "${red}[ERROR] Please, enter a valid destination path!${end}"
+		exit 1
+	fi
 	
 	# Create Temporary Files
 	sudo cp /opt/webinoly/webinoly.conf /opt/webinoly/webinoly.conf.exported
@@ -475,6 +488,7 @@ export_server() {
 	
 	[[ -f /opt/webinoly/webinoly.conf.exported ]] && local include="/opt/webinoly/webinoly.conf.exported" || local include=""
 	[[ -d /etc/nginx/apps.d ]] && local include="$include /etc/nginx/apps.d"
+	[[ -f /etc/nginx/conf.d/blockips.conf ]] && local include="$include /etc/nginx/conf.d/blockips.conf"
 	[[ -d /etc/nginx/sites-available ]] && local include="$include /etc/nginx/sites-available"
 	[[ -d /etc/nginx/sites-enabled ]] && local include="$include /etc/nginx/sites-enabled"
 	[[ -d /var/www ]] && local include="$include /var/www"
@@ -483,7 +497,7 @@ export_server() {
 	[[ -f $HOME/.aws/credentials ]] && local include="$include $HOME/.aws/credentials"
 	[[ -f /opt/webinoly/templates/source/csp_webinoly.data ]] && local include="$include /opt/webinoly/templates/source/csp_webinoly.data"
 	
-	sudo tar $exclude -Pcf $HOME/$filename $include
+	sudo tar $exclude -Pcf $destination/$filename $include
 
 	
 	# Remove Temporary Files
@@ -491,10 +505,10 @@ export_server() {
 	[[ $(conf_read mysql) == "true" && -z $skip_db ]] && sudo rm -rf /var/www/webinoly_backup_dball
 	[[ $(conf_read smtp) == "true" ]] && sudo rm -rf /var/www/webinoly_backup_smtp
 	
-	if [[ -s $HOME/$filename ]]; then
-		echo "${gre}Webinoly Complete Server Backup exported successfully!${end}${dim} ($HOME/$filename) ${end}"
+	if [[ -s $destination/$filename ]]; then
+		echo "${gre}Webinoly Complete Server Backup exported successfully!${end}${dim} ($destination/$filename) ${end}"
 	else
-		[[ -f $HOME/$filename ]] && sudo rm -rf $HOME/$filename
+		[[ -f $destination/$filename ]] && sudo rm -rf $destination/$filename
 		echo "${red}[ERROR] Unexpected error occurred while trying to export your server files!${end}"
 		exit 1
 	fi
@@ -502,7 +516,20 @@ export_server() {
 
 
 export_site() {
-	local filename="webinoly_${export}_$(date +%F)-$(date +%T)"
+	[[ -z $filename ]] && local filename="webinoly_${export}_$(date +%F)-$(date +%T)"
+	
+	if [[ -z $destination || $destination =~ ^(default|true)$ ]]; then
+		destination="$HOME"
+		sudo mkdir -p $destination
+	
+	# Must start with / and can not end with /
+	elif [[ ! -d $destination && $(echo "${destination}" | cut -c-1) == "/" && $(echo "${destination}" | rev | cut -c-1) != "/" ]]; then
+		sudo mkdir -p $destination
+	fi
+	if [[ ! -d $destination || $(echo "${destination}" | rev | cut -c-1) == "/" ]]; then
+		echo "${red}[ERROR] Please, enter a valid destination path!${end}"
+		exit 1
+	fi
 	
 	if [[ $(conf_read mysql) == "true" && $(is_wp $export) == "true" && $(is_wp_installed $export) == "true" && -z $skip_db ]]; then
 		sudo webinoly -backup=local -wp=$export -destination=/var/www/$export -filename=webinoly_backup_db > /dev/null
@@ -518,15 +545,15 @@ export_site() {
 		[[ -s $app ]] && local include="$include $app"
 	done
 	
-	sudo tar -Pcf $HOME/$filename $include
+	sudo tar -Pcf $destination/$filename $include
 	
 	# Remove temporary files
 	sudo rm -rf /var/www/$export/webinoly_backup_db
 	
-	if [[ -s $HOME/$filename ]]; then
-		echo "${gre}Webinoly Site Backup${blu} $export ${gre}exported successfully!${end}${dim} ($HOME/$filename) ${end}"
+	if [[ -s $destination/$filename ]]; then
+		echo "${gre}Webinoly Site Backup${blu} $export ${gre}exported successfully!${end}${dim} ($destination/$filename) ${end}"
 	else
-		[[ -f $HOME/$filename ]] && sudo rm -rf $HOME/$filename
+		[[ -f $destination/$filename ]] && sudo rm -rf $destination/$filename
 		echo "${red}[ERROR] Unexpected error occurred while trying to export your site!${end}"
 		exit 1
 	fi
