backup target validation
Now we check for a valid S3 url endpoint.

diff --git a/lib/bkp b/lib/bkp
--- a/lib/bkp
+++ b/lib/bkp
@@ -83,11 +83,31 @@ bkp_s3_profile() {
 			exit 1
 		fi
 		
+		# Bucket sintax validation
+		tar_scheme=$( echo $bucket | sed 's#://#|#' | cut -d'|' -f 1 -s)
+		tar_url=$( echo $bucket | sed 's#://#|#' | cut -d'|' -f 2 -s)
+		
+		# Fix URL in case was entered without scheme ej. 's3.amazonaws.com/bucket/folder'
+		if [[ -z $tar_scheme && -z $tar_url && -n $bucket ]]; then
+			tar_scheme="https"
+			tar_url=$bucket
+		fi
+		
+		# Validation
+		if ! [[ $tar_scheme =~ ^(http|https|s3)$ ]]; then
+			echo "${red}[ERROR] Invalid target/destination!${end}"
+			exit 1
+		elif [[ $( echo $tar_url | cut -d'.' -f 1 -s) != "s3" ]]; then
+			echo "${red}[ERROR] Invalid S3 path!${end}"
+			exit 1
+		fi
+		
+		
 		sudo duply $profile create
 		[[ -z $max_age ]] && max_age="1M"
 		sudo sed -i -E "/^[#]?GPG_KEY=/c GPG_KEY='disabled'" /root/.duply/$profile/conf
 		sudo sed -i -E "/^[#]?GPG_PW=/c #GPG_PW='_GPG_PASSWORD_'" /root/.duply/$profile/conf
-		sudo sed -i -E "/^[#]?TARGET=/c TARGET='$bucket'" /root/.duply/$profile/conf
+		sudo sed -i -E "/^[#]?TARGET=/c TARGET='s3://${tar_url}'" /root/.duply/$profile/conf
 		sudo sed -i -E "/^[#]?SOURCE=/c SOURCE='$source'" /root/.duply/$profile/conf
 		sudo sed -i -E "/^[#]?MAX_AGE=/c MAX_AGE=$max_age" /root/.duply/$profile/conf
 		
