code revision
Full code test and revision

diff --git a/lib/bkp b/lib/bkp
--- a/lib/bkp
+++ b/lib/bkp
@@ -122,7 +122,7 @@ bkp_s3_list() {
 		for f in /root/.duply/*
 		do 
 			[[ -d $f ]] && pro=$(echo $f | cut -f 4 -d "/" -s)
-			[[ -a $f/conf ]] && fail="" || fail="${red}(fail)${end}"
+			[[ -f $f/conf ]] && fail="" || fail="${red}(fail)${end}"
 			[[ -n $raw || $list == "raw" ]] && outlist="$pro" || outlist=" ${gre}+ $pro ${end}${fail}"
 			if [[ -n $outlist ]]; then
 				echo "$outlist"
diff --git a/plugins/stack b/plugins/stack
--- a/plugins/stack
+++ b/plugins/stack
@@ -5,7 +5,7 @@
 # Options: -html, -nginx, -php, -lemp, -mysql, -pma, -info, -purge-server-all, -php-ver
 # Arguments: -purge, -notools
 
-source /opt/webinoly/lib/webin
+source /opt/webinoly/lib/install
 check_for_parameters $@
 api-events_update sts
 
@@ -25,262 +25,260 @@ if [[ -n $purge && ( -n $html || -n $nginx ) ]]; then
 	if [[ $(conf_read nginx) != "true" ]]; then
 		echo "${gre}Nginx is not installed, hence can not be deleted! ${end}"
 		clear_force_flag
-		exit 0
-	fi
-	
-	echo ""
-	echo "${red}¡ C A U T I O N !  You are about to remove NGINX from your server!"
-	[[ $(conf_read mysql-tool) == "true" ]] && echo "phpMyAdmin will be removed too because depends on Nginx."
-	echo ""
-	
-	if [[ $(conf_read force-flag) != "true" ]]; then
-		echo " ${blu}Are you sure [y/N]? ${end}"
-		while read -r -n 1 -s answer; do
-		  answer=${answer:-n}
-		  [[ $answer = [YyNn] ]] && break
-		done
-	fi
-	
-	if [[ $answer == [Yy] || $(conf_read force-flag) == "true" ]]; then
-		if [[ $(conf_read force-flag) == "true" && $force == 1 ]]; then
-			answer="Y"
-		else
-			echo ""
-			echo "${blu}Do you want to delete your sites data directory (/var/www) [Y/n]? ${end}"
+	else
+		echo ""
+		echo "${red}¡ C A U T I O N !  You are about to remove NGINX from your server!"
+		[[ $(conf_read mysql-tool) == "true" ]] && echo "phpMyAdmin will be removed too because depends on Nginx."
+		echo ""
+		
+		if [[ $(conf_read force-flag) != "true" ]]; then
+			echo " ${blu}Are you sure [y/N]? ${end}"
 			while read -r -n 1 -s answer; do
-			  answer=${answer:-y}
+			  answer=${answer:-n}
 			  [[ $answer = [YyNn] ]] && break
 			done
 		fi
-		if [[ $answer == [Yy] ]]; then
-			[[ $(conf_read mysql-tool) == "true" ]] && stack -pma -purge=force
-			api-events_update pn2
-			site -delete-all=force
-			sudo rm -rf /var/www/$(conf_read tools-port)
-			sudo rm -rf /var/www/html
-			api-events_update pn3
+		
+		if [[ $answer == [Yy] || $(conf_read force-flag) == "true" ]]; then
+			if [[ $(conf_read force-flag) == "true" && $force == 1 ]]; then
+				answer="Y"
+			else
+				echo ""
+				echo "${blu}Do you want to delete your sites data directory (/var/www) [Y/n]? ${end}"
+				while read -r -n 1 -s answer; do
+				  answer=${answer:-y}
+				  [[ $answer = [YyNn] ]] && break
+				done
+			fi
+			if [[ $answer == [Yy] ]]; then
+				[[ $(conf_read mysql-tool) == "true" ]] && stack -pma -purge=force
+				api-events_update pn2
+				site -delete-all=force
+				sudo rm -rf /var/www/$(conf_read tools-port)
+				sudo rm -rf /var/www/html
+				api-events_update pn3
+			fi
+			
+			sudo service nginx stop
+			sudo apt -y purge nginx nginx-common
+			[[ $(conf_read nginx-ppa) == "mainline" ]] && echo | sudo add-apt-repository --remove 'ppa:nginx/development' || echo | sudo add-apt-repository --remove 'ppa:nginx/stable'
+			api-events_update pn4
+			api-events_update pn5
+			sudo apt -y purge certbot python-boto duplicity duply
+			echo | sudo add-apt-repository --remove 'ppa:certbot/certbot'
+			# Remove SSL Cron
+			if [[ -f /var/spool/cron/crontabs/root ]]; then
+				sudo sed -i '/MAILTO=/d' /var/spool/cron/crontabs/root
+				sudo sed -i '/certbot renew/d' /var/spool/cron/crontabs/root
+			fi
+			sudo apt -y autoremove
+			sudo rm $HOME/www
+			sudo rm $HOME/sites-available
+			
+			# Remove sources
+			sudo rm -rf /opt/webinoly/templates/source/default
+			
+			api-events_update pn6
+			linux_purge
+			
+			conf_write nginx purged
+			conf_write nginx-optim purged
+			conf_write nginx-tool purged
+			conf_delete server-version
+			echo ""
+			echo "${gre}Nginx has been deleted successfully! ${end}"
+			echo ""
+		else
+			echo ""
+			echo " ${gre}Action aborted!!!  ${end}"
+			echo ""
 		fi
-		
-		sudo service nginx stop
-		sudo apt -y purge nginx nginx-common
-		[[ $(conf_read nginx-ppa) == "mainline" ]] && echo | sudo add-apt-repository --remove 'ppa:nginx/development' || echo | sudo add-apt-repository --remove 'ppa:nginx/stable'
-		api-events_update pn4
-		api-events_update pn5
-		sudo apt -y purge certbot python-boto duplicity duply
-		echo | sudo add-apt-repository --remove 'ppa:certbot/certbot'
-		# Remove SSL Cron
-		if [[ -a /var/spool/cron/crontabs/root ]]; then
-			sudo sed -i '/MAILTO=/d' /var/spool/cron/crontabs/root
-			sudo sed -i '/certbot renew/d' /var/spool/cron/crontabs/root
-		fi
-		sudo apt -y autoremove
-		sudo rm $HOME/www
-		sudo rm $HOME/sites-available
-		
-		# Remove sources
-		sudo rm -rf /opt/webinoly/templates/source/default
-		
-		api-events_update pn6
-		linux_purge
-		
-		conf_write nginx purged
-		conf_write nginx-optim purged
-		conf_write nginx-tool purged
-		conf_delete server-version
-		echo ""
-		echo "${gre}Nginx has been deleted successfully! ${end}"
-		echo ""
-	else
-		echo ""
-		echo " ${gre}Action aborted!!!  ${end}"
 		echo ""
 	fi
-	echo ""
 	
 elif [[ -n $purge && -n $php ]]; then
 	api-events_update pp1
 	if [[ $(conf_read php) != "true" ]]; then
 		echo "${gre}PHP is not installed, hence can not be deleted! ${end}"
 		clear_force_flag
-		exit 0
-	fi
-
-	echo ""
-	echo "${red}¡ C A U T I O N !  You are about to remove PHP from your server!"
-	echo "This action will also remove PhpMyAdmin if its installed because depends on PHP. ${end}"
-	echo ""
-
-	if [[ $(conf_read force-flag) != "true" ]]; then
-		echo " ${blu}Are you sure [y/N]? ${end}"
-		while read -r -n 1 -s answer; do
-			answer=${answer:-n}
-			[[ $answer = [YyNn] ]] && break
-		done
-	fi
-
-	if [[ $answer == [Yy] || $(conf_read force-flag) == "true" ]]; then
-		[[ $(conf_read mysql-tool) == "true" ]] && stack -pma -purge=force
-		sudo service php*-fpm stop
-		sudo apt -y purge php*-fpm php*-curl php*-gd php*-imap php*-mcrypt php*-readline php*-common php*-recode php*-mysql php*-cli php*-mbstring php*-bcmath php*-mysql php*-opcache php*-zip php*-xml php*-soap php-imagick graphviz php-pear php-msgpack
-		sudo apt -y purge php-memcached php-memcache memcached
-		sudo apt -y purge redis-server php-redis postfix
-		echo | sudo add-apt-repository --remove 'ppa:ondrej/php'
-		echo | sudo add-apt-repository --remove 'ppa:chris-lea/redis-server'
-		sudo apt -y autoremove
-		sudo rm -rf /etc/php
-		sudo rm /opt/webinoly/templates/source/*
-
-		# Remove sources
-		sudo rm -rf /opt/webinoly/templates/source/php.ini
-		sudo rm -rf /opt/webinoly/templates/source/www.conf
-		sudo rm -rf /opt/webinoly/templates/source/main.cf
-		
-		# Remove tools-site
-		sudo rm -rf /etc/nginx/sites-available/$(conf_read tools-port)
-		sudo rm -rf /etc/nginx/sites-enabled/$(conf_read tools-port)
-		sudo rm -rf /var/www/$(conf_read tools-port)
-		conf_delete tools-site
-		
-		conf_write php purged
-		conf_write php-optim purged
-		[[ $(conf_read php-v7.4) == "true" ]] && conf_write php-v7.4 purged
-		[[ $(conf_read php-v7.3) == "true" ]] && conf_write php-v7.3 purged
-		[[ $(conf_read php-v7.2) == "true" ]] && conf_write php-v7.2 purged
-		# We need it to support and update old deprecated stacks.
-		[[ $(conf_read php-v7.1) == "true" ]] && conf_write php-v7.1 purged
-		[[ $(conf_read php-v7.0) == "true" ]] && conf_write php-v7.0 purged
-		[[ $(conf_read php-v5.6) == "true" ]] && conf_write php-v5.6 purged
-
-		if [[ $(conf_read php-tool) == "true" ]]; then
-			rm -rf /var/www/$(conf_read tools-port)/htdocs/fpm
-			rm -rf /var/www/$(conf_read tools-port)/htdocs/php
-			conf_write php-tool purged
-		fi
-
-		echo ""
-		echo "${gre}PHP has been deleted successfully! ${end}"
-		echo ""
 	else
 		echo ""
-		echo " ${gre}Action aborted!!!  ${end}"
+		echo "${red}¡ C A U T I O N !  You are about to remove PHP from your server!"
+		echo "This action will also remove phpMyAdmin if its installed because depends on PHP. ${end}"
 		echo ""
-	fi
-	echo ""
-	api-events_update pp2
 
+		if [[ $(conf_read force-flag) != "true" ]]; then
+			echo " ${blu}Are you sure [y/N]? ${end}"
+			while read -r -n 1 -s answer; do
+				answer=${answer:-n}
+				[[ $answer = [YyNn] ]] && break
+			done
+		fi
+
+		if [[ $answer == [Yy] || $(conf_read force-flag) == "true" ]]; then
+			[[ $(conf_read mysql-tool) == "true" ]] && stack -pma -purge=force
+			sudo service php*-fpm stop
+			sudo apt -y purge php*-fpm php*-curl php*-gd php*-imap php*-mcrypt php*-readline php*-common php*-recode php*-mysql php*-cli php*-mbstring php*-bcmath php*-mysql php*-opcache php*-zip php*-xml php*-soap php-imagick graphviz php-pear php-msgpack
+			sudo apt -y purge php-memcached php-memcache memcached
+			sudo apt -y purge redis-server php-redis postfix
+			echo | sudo add-apt-repository --remove 'ppa:ondrej/php'
+			echo | sudo add-apt-repository --remove 'ppa:chris-lea/redis-server'
+			sudo apt -y autoremove
+			sudo rm -rf /etc/php
+			sudo rm /opt/webinoly/templates/source/*
+
+			# Remove sources
+			sudo rm -rf /opt/webinoly/templates/source/php.ini
+			sudo rm -rf /opt/webinoly/templates/source/www.conf
+			sudo rm -rf /opt/webinoly/templates/source/main.cf
+			
+			# Remove tools-site
+			sudo rm -rf /etc/nginx/sites-available/$(conf_read tools-port)
+			sudo rm -rf /etc/nginx/sites-enabled/$(conf_read tools-port)
+			sudo rm -rf /var/www/$(conf_read tools-port)
+			conf_delete tools-site
+			
+			conf_write php purged
+			conf_write php-optim purged
+			[[ $(conf_read php-v7.4) == "true" ]] && conf_write php-v7.4 purged
+			[[ $(conf_read php-v7.3) == "true" ]] && conf_write php-v7.3 purged
+			[[ $(conf_read php-v7.2) == "true" ]] && conf_write php-v7.2 purged
+			# We need it to support and update old deprecated stacks.
+			[[ $(conf_read php-v7.1) == "true" ]] && conf_write php-v7.1 purged
+			[[ $(conf_read php-v7.0) == "true" ]] && conf_write php-v7.0 purged
+			[[ $(conf_read php-v5.6) == "true" ]] && conf_write php-v5.6 purged
+
+			if [[ $(conf_read php-tool) == "true" ]]; then
+				rm -rf /var/www/$(conf_read tools-port)/htdocs/fpm
+				rm -rf /var/www/$(conf_read tools-port)/htdocs/php
+				conf_write php-tool purged
+			fi
+
+			echo ""
+			echo "${gre}PHP has been deleted successfully! ${end}"
+			echo ""
+		else
+			echo ""
+			echo " ${gre}Action aborted!!!  ${end}"
+			echo ""
+		fi
+		echo ""
+		api-events_update pp2
+	fi
+	
 	
 elif [[ -n $purge && -n $mysql ]]; then
 	api-events_update pm1
 	if [[ $(conf_read mysql) != "true" ]]; then
 		echo "${gre}MySQL is not installed, hence can not be deleted! ${end}"
 		clear_force_flag
-		exit 0
-	fi
-	
-	echo ""
-	echo "${red}¡ C A U T I O N !  You are about to remove MySQL from your server! ${end}"
-	echo ""
-
-	if [[ $(conf_read force-flag) != "true" ]]; then
-		echo " ${blu}Are you sure [y/N]? ${end}"
-		while read -r -n 1 -s answer; do
-		  answer=${answer:-n}
-		  [[ $answer = [YyNn] ]] && break
-		done
-	fi
-	
-	if [[ $answer == [Yy] || $(conf_read force-flag) == "true" ]]; then
-		if [[ $(conf_read mysql-tool) == "true" ]]; then
-			conf_write delautopma true
-			stack -pma -purge
-			conf_delete delautopma
-		fi
-		
-		# Determine MySQL version according to stack version.
-		mysqlver=$(sudo mysql -V | cut -f 6 -d " " -s | cut -f -2 -d "." -s)
-		sudo service mysql stop
-		
-		if [[ $mysql == "keep-data" ]]; then
-			echo "mariadb-server-${mysqlver}	mariadb-server-${mysqlver}/postrm_remove_databases	boolean false" | debconf-set-selections
-		else
-			echo "mariadb-server-${mysqlver}	mariadb-server-${mysqlver}/postrm_remove_databases	boolean true" | debconf-set-selections
-		fi
-		sudo apt -y purge mariadb-server mariadb-common mysql-common
-		sudo apt -y purge mariadb-client
-		sudo apt -y purge debconf-utils
-		sudo apt -y autoremove
-		
-		# Cases with MariaDB v10.4 support
-		os_name=$(check_osname)
-		sudo add-apt-repository --remove "http://mirrors.syringanetworks.net/mariadb/repo/${mysqlver}/ubuntu"
-		case "$osname" in
-			"trusty")
-				sudo apt-key del 0xcbcb082a1bb943db
-			;;
-			"xenial"|"bionic"|"cosmic"|"disco")
-				sudo apt-key del 0xF1656F24C74CD1D8
-				
-			;;
-		esac
-		
-		if [[ $mysql != "keep-data" ]]; then
-			sudo rm -rf /etc/mysql
-			sudo rm -rf /var/lib/mysql
-			conf_delete mysql-root
-			conf_delete mysql-admin
-		else
-			echo "${blu}MySQL data was not removed.${end}"
-		fi
-		
-		conf_write mysql-client purged
-		conf_write mysql purged
-		echo ""
-		echo "${gre}MySQL has been deleted successfully! ${end}"
-		echo ""
 	else
 		echo ""
-		echo " ${gre}Action aborted!!!  ${end}"
+		echo "${red}¡ C A U T I O N !  You are about to remove MySQL from your server! ${end}"
 		echo ""
+
+		if [[ $(conf_read force-flag) != "true" ]]; then
+			echo " ${blu}Are you sure [y/N]? ${end}"
+			while read -r -n 1 -s answer; do
+			  answer=${answer:-n}
+			  [[ $answer = [YyNn] ]] && break
+			done
+		fi
+		
+		if [[ $answer == [Yy] || $(conf_read force-flag) == "true" ]]; then
+			if [[ $(conf_read mysql-tool) == "true" ]]; then
+				conf_write delautopma true
+				stack -pma -purge
+				conf_delete delautopma
+			fi
+			
+			# Determine MySQL version according to stack version.
+			mysqlver=$(sudo mysql -V | cut -f 6 -d " " -s | cut -f -2 -d "." -s)
+			sudo service mysql stop
+			
+			if [[ $mysql == "keep-data" ]]; then
+				echo "mariadb-server-${mysqlver}	mariadb-server-${mysqlver}/postrm_remove_databases	boolean false" | debconf-set-selections
+			else
+				echo "mariadb-server-${mysqlver}	mariadb-server-${mysqlver}/postrm_remove_databases	boolean true" | debconf-set-selections
+			fi
+			sudo apt -y purge mariadb-server mariadb-common mysql-common
+			sudo apt -y purge mariadb-client
+			sudo apt -y purge debconf-utils
+			sudo apt -y autoremove
+			
+			# Cases with MariaDB v10.4 support
+			os_name=$(check_osname)
+			sudo add-apt-repository --remove "http://mirrors.syringanetworks.net/mariadb/repo/${mysqlver}/ubuntu"
+			case "$osname" in
+				"trusty")
+					sudo apt-key del 0xcbcb082a1bb943db
+				;;
+				"xenial"|"bionic"|"cosmic"|"disco")
+					sudo apt-key del 0xF1656F24C74CD1D8
+					
+				;;
+			esac
+			
+			if [[ $mysql != "keep-data" ]]; then
+				sudo rm -rf /etc/mysql
+				sudo rm -rf /var/lib/mysql
+				conf_delete mysql-root
+				conf_delete mysql-admin
+			else
+				echo "${blu}MySQL data was not removed.${end}"
+			fi
+			
+			conf_write mysql-client purged
+			conf_write mysql purged
+			echo ""
+			echo "${gre}MySQL has been deleted successfully! ${end}"
+			echo ""
+		else
+			echo ""
+			echo " ${gre}Action aborted!!!  ${end}"
+			echo ""
+		fi
+		echo ""
+		api-events_update pm4
 	fi
-	echo ""
-	api-events_update pm4
+	
 	
 elif [[ -n $purge && -n $pma ]]; then
 	api-events_update pm2
 	if [[ $(conf_read mysql-tool) != "true" ]]; then
-		echo "${gre}PhpMyAdmin is not installed, hence can not be deleted! ${end}"
+		echo "${gre}phpMyAdmin is not installed, hence can not be deleted! ${end}"
 		clear_force_flag
-		exit 0
-	fi
-	
-	echo ""
-	echo "${red}¡ C A U T I O N !  You are about to remove PhpMyAdmin from your server! ${end}"
-	echo ""
-
-	if [[ $(conf_read force-flag) != "true" && $(conf_read delautopma) != "true" ]]; then
-		echo " ${blu}Are you sure [y/N]? ${end} "
-		while read -r -n 1 -s answer; do
-		  answer=${answer:-n}
-		  if [[ $answer = [YyNn] ]]; then
-			break
-		  fi
-		done
-	fi
-
-	if [[ $answer == [Yy] || $(conf_read force-flag) == "true" || $(conf_read delautopma) == "true" ]]; then
-		sudo rm -rf /var/www/$(conf_read tools-port)/htdocs/pma
-		conf_write mysql-tool purged
-		echo ""
-		echo "${gre}PhpMyAdmin has been deleted successfully! ${end}"
-		echo ""
 	else
 		echo ""
-		echo " ${gre}Action aborted!!!  ${end}"
+		echo "${red}¡ C A U T I O N !  You are about to remove phpMyAdmin from your server! ${end}"
 		echo ""
+
+		if [[ $(conf_read force-flag) != "true" && $(conf_read delautopma) != "true" ]]; then
+			echo " ${blu}Are you sure [y/N]? ${end} "
+			while read -r -n 1 -s answer; do
+			  answer=${answer:-n}
+			  if [[ $answer = [YyNn] ]]; then
+				break
+			  fi
+			done
+		fi
+
+		if [[ $answer == [Yy] || $(conf_read force-flag) == "true" || $(conf_read delautopma) == "true" ]]; then
+			sudo rm -rf /var/www/$(conf_read tools-port)/htdocs/pma
+			conf_write mysql-tool purged
+			echo ""
+			echo "${gre}phpMyAdmin has been deleted successfully! ${end}"
+			echo ""
+		else
+			echo ""
+			echo " ${gre}Action aborted!!!  ${end}"
+			echo ""
+		fi
+		echo ""
+		api-events_update pm3
 	fi
-	echo ""
-	api-events_update pm3
-		
+	
+	
 elif [[ -n $purge && -n $lemp ]]; then
 	echo "${red}If you want to remove Webinoly Stack completely from your server use the '-purge-server-all' option or remove each package individually.  ${end}"
 	exit 1
@@ -357,7 +355,7 @@ elif [[ -n $php ]]; then
 elif [[ -n $mysql ]]; then
 	if [[ $(conf_read mysql) != "true" ]]; then
 		mysql_install
-		[[ -z $notools && $(conf_read mysql) == "true" && $(conf_read php) == "true" && $(conf_read nginx) == "true" && $(conf_read nginx-tool) == "true" ]] && stack -pma || echo "${gre}PhpMyAdmin was NOT installed!${end}"
+		[[ -z $notools && $(conf_read mysql) == "true" && $(conf_read php) == "true" && $(conf_read nginx) == "true" && $(conf_read nginx-tool) == "true" ]] && stack -pma || echo "${gre}phpMyAdmin was NOT installed!${end}"
 		messagend_install
 	else
 		echo "${red}MySQL is already installed!${end}"
@@ -369,11 +367,11 @@ elif [[ -n $mysql ]]; then
 
 elif [[ -n $pma ]]; then
 	if [[ $(conf_read mysql) != "true" || $(conf_read php) != "true" || $(conf_read nginx) != "true" || $(conf_read nginx-tool) != "true" ]]; then
-		echo "${red}[ERROR] You need to have MySQL, PHP and NGINX installed before you can install PhpMyAdmin! ${end}"
+		echo "${red}[ERROR] You need to have MySQL, PHP and NGINX installed before you can install phpMyAdmin! ${end}"
 		clear_force_flag
 		exit 1
 	fi
-	[[ $(conf_read mysql-tool) != "true" ]] && mysql_tool || echo "${red}PhpMyAdmin is already installed!${end}"
+	[[ $(conf_read mysql-tool) != "true" ]] && mysql_tool || echo "${red}phpMyAdmin is already installed!${end}"
 
 elif [[ -n $lemp ]]; then
 	api-events_update st1
@@ -395,7 +393,6 @@ elif [[ -n $php_ver ]]; then
 		echo "${blu}New PHP version: '$php_ver' ${end}"
 		if [[ $(conf_read php) == "true" && $(conf_read php-ver) == $php_ver ]]; then
 			echo "${gre}PHP $php_ver is currently installed!${end}"
-			exit 0
 		elif [[ $(conf_read php) == "true" && $(conf_read mysql-tool) == "true" ]]; then
 			sudo stack -php -purge=force
 			conf_write php-ver $php_ver
@@ -419,9 +416,7 @@ elif [[ -n $php_ver ]]; then
 	fi
 
 	
-# Info & Purge-Server-All
-elif [[ -n $info ]]; then
-	system_info
+# Purge-Server-All
 elif [[ -n $purge_server_all ]]; then
 	api-events_update st2
 	echo ""
@@ -448,9 +443,9 @@ elif [[ -n $purge_server_all ]]; then
 		clear_force_flag
 		
 		# Remove remanent packages and things!
-		[[ -a /etc/ssl/certs/webinoly-blackhole.crt.pem ]] && sudo rm -rf /etc/ssl/certs/webinoly-blackhole.crt.pem
-		[[ -a /etc/ssl/private/webinoly-blackhole.key.pem ]] && sudo rm -rf /etc/ssl/private/webinoly-blackhole.key.pem
-		[[ -a /etc/ssl/dhparam.pem ]] && sudo rm -rf /etc/ssl/dhparam.pem
+		[[ -f /etc/ssl/certs/webinoly-blackhole.crt.pem ]] && sudo rm -rf /etc/ssl/certs/webinoly-blackhole.crt.pem
+		[[ -f /etc/ssl/private/webinoly-blackhole.key.pem ]] && sudo rm -rf /etc/ssl/private/webinoly-blackhole.key.pem
+		[[ -f /etc/ssl/dhparam.pem ]] && sudo rm -rf /etc/ssl/dhparam.pem
 		if [[ $(conf_read pre-packs) == true ]]; then
 			sudo apt-get -y -qq purge pwgen unzip zip > /dev/null
 			sudo apt-get -y -qq autoremove > /dev/null
