wp multisite
New command to convert from single to multisite, also we remove the old commands to create wp mu.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -129,7 +129,7 @@ conf_write() {
 }
 
 
-db_delete() {
+wp_dbdata() {
 	local domain="$1"
 	
 	# Get dbname and dbuser of a WP site
@@ -141,18 +141,36 @@ db_delete() {
 		return
 	fi
 	
-	local name=$( grep -F "DB_NAME" $wpconfpath | cut -f 4 -d "'" )
-	local user=$( grep -F "DB_USER" $wpconfpath | cut -f 4 -d "'" )
-	local host=$( grep -F "DB_HOST" $wpconfpath | cut -f 4 -d "'" )
-	local url=$(echo "$host" | cut -f 1 -d ':')
-	local port=$(echo "$host" | cut -f 2 -d ':')
+	wp_dbname=$( grep -F "DB_NAME" $wpconfpath | cut -f 4 -d "'" )
+	wp_dbuser=$( grep -F "DB_USER" $wpconfpath | cut -f 4 -d "'" )
+	wp_dbhost=$( grep -F "DB_HOST" $wpconfpath | cut -f 4 -d "'" )
+	wp_dburl=$(echo "$wp_dbhost" | cut -f 1 -d ':')
+	wp_dbport=$(echo "$wp_dbhost" | cut -f 2 -d ':')
+	
+	if [[ -n $external_db ]]; then
+		dbdata=${external_db:1:-1}
+		wp_uroot=$(echo "${dbdata}" | cut -d',' -f 1 -s)
+		wp_proot=$(echo "${dbdata}" | cut -d',' -f 2 -s)
+		if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" || -z $wp_uroot || -z $wp_proot ]]; then
+			echo "${red}[ERROR] Invalid data for External Database!${end}"
+			exit 1
+		fi
+	fi
+}
+
+
+db_delete() {
+	local domain="$1"
 	local done="0"
 	
-	dbsetup="DELETE FROM mysql.user WHERE User='$user';DROP DATABASE IF EXISTS $name;DELETE FROM mysql.db WHERE Db='$name' OR Db='$name\\_%';FLUSH PRIVILEGES;"
+	wp_dbdata $1
+	[[ -z $wpconfpath ]] && return
+	
+	dbsetup="DELETE FROM mysql.user WHERE User='$wp_dbuser';DROP DATABASE IF EXISTS $wp_dbname;DELETE FROM mysql.db WHERE Db='$wp_dbname' OR Db='$wp_dbname\\_%';FLUSH PRIVILEGES;"
 	while [[ $done != "1" ]]
 	do
 		done="1"
-		if [[ $host == "localhost" ]]; then
+		if [[ $wp_dbhost == "localhost" ]]; then
 			# Check if MySQL installed
 			if [[ ! -d /etc/mysql || $(conf_read mysql) != "true" || $(conf_read mysql-client) != "true" ]]; then
 				echo "${red}[ERROR] Seems like MySQL is not installed or Webinoly can not detect it!"
@@ -177,23 +195,14 @@ db_delete() {
 				echo "${gre}Database of your site ${blu}${domain}${subfolder}${gre} has been successfully deleted! ${end}"
 			fi
 		else
-			if [[ -n $external_db ]]; then
-				dbdata=${external_db:1:-1}
-				uroot=$(echo "${dbdata}" | cut -d',' -f 1 -s)
-				proot=$(echo "${dbdata}" | cut -d',' -f 2 -s)
-				if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" || -z $uroot || -z $proot ]]; then
-					echo "${red}[ERROR] Invalid data for External Database!${end}"
-					exit 1
-				fi
-			fi
-			if [[ -z $uroot || -z $proot ]]; then
+			if [[ -z $wp_uroot || -z $wp_proot ]]; then
 				echo ""
 				echo "${gre}External DB found in${blu} $domain ${gre}(Press 'Enter' key twice to skip and not delete)"
-				read -p "${blu}External DB root username [root]: " uroot
-				uroot=${uroot:-root}
-				read -p "External DB root password: " proot
+				read -p "${blu}External DB root username [root]: " wp_uroot
+				wp_uroot=${wp_uroot:-root}
+				read -p "External DB root password: " wp_proot
 			fi
-			if [[ $uroot == "root" && -z $proot ]]; then
+			if [[ $wp_uroot == "root" && -z $wp_proot ]]; then
 				echo "${red}Action aborted, database not deleted!"
 				continue 1;
 			else
@@ -204,7 +213,7 @@ db_delete() {
 					echo "${gre}MySQL Client has been successfully installed!${end}"
 				fi
 				
-				sudo mysql --connect-timeout=10 -h "$url" -P "$port" -u"$uroot" -p"$proot" -e "$dbsetup"
+				sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup"
 				if [ $? != "0" ]; then
 					done="0"
 					echo "${red}============================================"
@@ -373,3 +382,32 @@ is_wp_cache() {
 		echo "false"
 	fi
 }
+
+is_wp_multisite() {
+	wp_dbdata $1
+	dbsetup="SELECT * FROM information_schema.tables WHERE table_schema = '$wp_dbname' AND table_name = 'wp_sitemeta' LIMIT 1;"
+	
+	if [[ $wp_dbhost == "localhost" ]]; then
+		local ROOT_PASS=$( echo $(conf_read mysql-root) | openssl enc -d -a -salt )
+		val=$(sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "$dbsetup")
+	elif [[ -n $wp_dburl ]]; then
+		val=$(sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup")
+	fi
+	
+	[[ -n $val ]] && echo "true" || echo "false"
+}
+
+is_wp_multisite_subdomain() {
+	wp_dbdata $1
+	dbsetup="USE $wp_dbname; SELECT meta_value FROM wp_sitemeta where meta_key='subdomain_install';"
+	
+	if [[ $wp_dbhost == "localhost" ]]; then
+		local ROOT_PASS=$( echo $(conf_read mysql-root) | openssl enc -d -a -salt )
+		val=$(sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "$dbsetup")
+	elif [[ -n $wp_dburl ]]; then
+		val=$(sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup")
+	fi
+	
+	[[ $(echo $val | cut -f 2 -d " " -s) == "1" ]] && echo "true" || echo "false"
+}
+
diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -263,22 +263,65 @@ elif [[ -n $wp && -n $domain ]]; then
 		sudo sed -i "s#subfolder#$subfolder#g" /etc/nginx/apps.d/$domain$subname-wpcommon-noauth.conf
 	fi
 
-# Create WP Multisite (Sub-directory)
-elif [[ -n $wpsubdir && -n $domain ]]; then
-	createsite
-	sudo sed -i '/locations.conf/i \	include common/wpsubdir.conf;' /etc/nginx/sites-available/$domain
-	sudo sed -i '/locations.conf/i \	include common/wpcommon.conf;' /etc/nginx/sites-available/$domain
-	[[ $(conf_read wp-admin-auth) == "purged" ]] && sudo httpauth -wp-admin=off -site=$domain
-	[[ $(conf_read yoast-sitemap) != "purged" ]] && sudo site $domain -yoast-sitemap=on
+
+# Convert WP single to Multisite
+elif [[ -n $multisite_convert && -a /etc/nginx/sites-available/$domain ]]; then
+	if [[ ( -z $subfolder && $(is_wp $domain) == "false" ) || ( -n $subfolder && $(is_wp $domain $subfolder) == "false" ) ]]; then
+		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is not a WP site!${end}"
+		exit 1
+	elif [[ $(is_wp_multisite $domain) == "true" ]]; then		
+		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is already in multisite configuration!${end}"
+		exit 1
+	fi
 	
+	[[ -z $subfolder ]] && wpcon="/var/www/$domain/wp-config.php" || wpcon="/var/www/$domain/htdocs$subfolder/wp-config.php"
+	sudo sed -i "/stop editing/i \define('WP_ALLOW_MULTISITE', true);" $wpcon
+
+	echo "${blu}"
+	echo "In your WordPress dashboard, go to ${end}“Tools -> Network Setup”${blu},"
+	echo "select the type of WP Multisite installation you want (Subdomain or Subdirectory)"
+	echo "and then press the ${end}“Install”${blu} button at the bottom."
+	echo ""
+	echo "After that, you don't need to add any code lines."
+	echo "We will do it for you!"
+	echo ""
+	echo "Just press ${end}<Enter>${blu} when you are ready or press ${end}'X'${blu} to Cancel!"
+	echo "${end}"
+	while read -r -n 1 -s answer; do
+		answer=${answer:-y}
+		[[ $answer = [YyXx] ]] && break
+	done
 	
-# Create WP Multisite (Sub-domain)	
-elif [[ -n $wpsubdom && -n $domain ]]; then
-	createsite
-	sudo sed -i '/locations.conf/i \	include common/wpcommon.conf;' /etc/nginx/sites-available/$domain
-	[[ $(conf_read wp-admin-auth) == "purged" ]] && sudo httpauth -wp-admin=off -site=$domain
-	[[ $(conf_read yoast-sitemap) != "purged" ]] && sudo site $domain -yoast-sitemap=on
-	
+	passed=$(is_wp_multisite $domain)
+	if [[ $passed != "true" && $answer == [Xx] ]]; then
+		sudo sed -i "/WP_ALLOW_MULTISITE/d" $wpcon
+		echo "${red}[ERROR] Action aborted!${end}"
+		exit 1
+	elif [[ $passed != "true" && $answer != [Xx] ]]; then
+		sudo sed -i "/WP_ALLOW_MULTISITE/d" $wpcon
+		echo "${red}[ERROR] Multisite installation incomplete or not detected!${end}"
+		exit 1
+	elif [[ $passed == "true" ]]; then
+		# Multisite wp-config
+		sudo sed -i "/stop editing/i \#define('MULTISITE', true);" $wpcon
+		sudo sed -i "/stop editing/i \#define('DOMAIN_CURRENT_SITE', '$domain');" $wpcon
+		sudo sed -i "/stop editing/i \#define('PATH_CURRENT_SITE', '/');" $wpcon
+		sudo sed -i "/stop editing/i \#define('SITE_ID_CURRENT_SITE', 1);" $wpcon
+		sudo sed -i "/stop editing/i \#define('BLOG_ID_CURRENT_SITE', 1);" $wpcon
+		
+		[[ $answer == [Xx] ]] && echo "${red}Can not cancel because the installation was already done!${end}"
+		
+		if [[ $(is_wp_multisite_subdomain $domain) == "true" ]]; then
+			sudo sed -i "/stop editing/i \#define('SUBDOMAIN_INSTALL', true);" $wpcon
+			sudo sed -i "/server_name /c \	server_name $domain *.$domain;" /etc/nginx/sites-available/$domain
+			echo "${gre}Subdomain Multisite configuration has been successfully completed!${end}"
+		else
+			sudo sed -i "/stop editing/i \#define('SUBDOMAIN_INSTALL', false);" $wpcon			
+			sudo sed -i '/locations.conf/i \	include common/wpsubdir.conf;' /etc/nginx/sites-available/$domain
+			echo "${gre}Subdirectory Multisite configuration has been successfully completed!${end}"
+		fi
+	fi
+
 
 # Parked Domain
 elif [[ -n $parked && -n $domain ]]; then
