builder
New smart builder with a lot of improvements.
- Build profiles support.
- multi-php removed.
- tools-site created since nginx instead of php.
- tools packages are now independent.
- internal api updated.
- new official ppa for redis.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -139,9 +139,43 @@ check_for_nginx() {
 		exit 1
 	fi
 }
-check_for_nginx_tool() {
-	if [[ $(conf_read nginx) != "true"  || $(conf_read nginx-optim) != "true" || $(conf_read nginx-tool) != "true" ]]; then
-		echo "${red}[ERROR] NGINX Tools are required and not found! ${end}"
+check_for_nginx_tool_ssl() {
+	check_for_nginx
+	if [[ $(conf_read nginx-tool-ssl) != "true" && $1 == "-ask" ]]; then
+		echo "${red}"
+		echo "+ Let's Encrypt Not Found!"
+		echo "${blu}Do you want to install it now? [y/N]? ${end}"
+		while read -r -n 1 -s answer; do
+			answer=${answer:-n}
+			echo ""
+			[[ $answer = [YyNn] ]] && break
+		done
+		
+		[[ $answer == [Yy] ]] && sudo stack -letsencrypt
+	fi
+	
+	if [[ $(conf_read nginx-tool-ssl) != "true" ]]; then
+		echo "${red}[ERROR] Let's Encrypt is required and not found! ${end}"
+		exit 1
+	fi
+}
+check_for_nginx_tool_bkp() {
+	check_for_nginx
+	if [[ $(conf_read nginx-tool-bkp) != "true" && $1 == "-ask" ]]; then
+		echo "${red}"
+		echo "+ BackUp packages Not Found!"
+		echo "${blu}Do you want to install it now? [y/N]? ${end}"
+		while read -r -n 1 -s answer; do
+			answer=${answer:-n}
+			echo ""
+			[[ $answer = [YyNn] ]] && break
+		done
+		
+		[[ $answer == [Yy] ]] && sudo stack -backups
+	fi
+	
+	if [[ $(conf_read nginx-tool-bkp) != "true" ]]; then
+		echo "${red}[ERROR] BackUp packages are required and not found! ${end}"
 		exit 1
 	fi
 }
@@ -164,9 +198,43 @@ check_for_php() {
 		exit 1
 	fi
 }
-check_for_php_tool() {
-	if [[ $(conf_read php) != "true"  || $(conf_read php-optim) != "true" || $(conf_read php-tool) != "true" ]]; then
-		echo "${red}[ERROR] PHP Tools are required and not found! ${end}"
+check_for_php_tool_postfix() {
+	check_for_php
+	if [[ $(conf_read php-tool-postfix) != "true" && $1 == "-ask" ]]; then
+		echo "${red}"
+		echo "+ Postfix Not Found!"
+		echo "${blu}Do you want to install it now? [y/N]? ${end}"
+		while read -r -n 1 -s answer; do
+			answer=${answer:-n}
+			echo ""
+			[[ $answer = [YyNn] ]] && break
+		done
+		
+		[[ $answer == [Yy] ]] && sudo stack -postfix
+	fi
+	
+	if [[ $(conf_read php-tool-postfix) != "true" ]]; then
+		echo "${red}[ERROR] Postfix is required and not found! ${end}"
+		exit 1
+	fi
+}
+check_for_php_tool_redis() {
+	check_for_php
+	if [[ $(conf_read php-tool-redis) != "true" && $1 == "-ask" ]]; then
+		echo "${red}"
+		echo "+ Redis Not Found!"
+		echo "${blu}Do you want to install it now? [y/N]? ${end}"
+		while read -r -n 1 -s answer; do
+			answer=${answer:-n}
+			echo ""
+			[[ $answer = [YyNn] ]] && break
+		done
+		
+		[[ $answer == [Yy] ]] && sudo stack -redis
+	fi
+	
+	if [[ $(conf_read php-tool-redis) != "true" ]]; then
+		echo "${red}[ERROR] Redis is required and not found! ${end}"
 		exit 1
 	fi
 }
@@ -193,7 +261,7 @@ check_for_mysql_client() {
 	if [[ $(conf_read mysql-client) != "true" ]]; then
 		echo "${gre}MySQL Client is not installed and we need it to stablish a connection with your external server.${end}"
 		echo "${dim}Wait while we install MySQL Client...${end}"
-		mysql_client_install > /dev/null 2>&1 &
+		sudo stack -mysql=client > /dev/null 2>&1 &
 		wait $!
 		echo "${gre}MySQL Client has been successfully installed!${end}"
 	fi
@@ -442,48 +510,10 @@ wp_conf_retrieve() {
 }
 
 
-pre_install() {
-	sudo apt -qq update
-	if [[ $(conf_read pre-packs) != true ]]; then
-		# Check for missing essential packages
-		api-events_update i1
-		sudo apt -y -qq install dialog
-		sudo apt -y -qq install software-properties-common
-		sudo apt -y -qq install pwgen
-		sudo apt -y -qq install unzip
-		sudo apt -y -qq install zip
-		conf_write pre-packs true
-		api-events_update i2
-	fi
-}
-
-
 # Remove Installation Files
 app_purge() {
 	sudo rm $HOME/webinoly.tar
 	sudo rm -rf /opt/webinoly/usr
-}
-
-
-mysql_client_install() {
-	api-events_update im2
-	if [[ -n $(conf_read mysql-ver) && $(check_mysql_version $(conf_read mysql-ver)) == "true" ]]; then
-		echo "${gre}MySQL version '$(conf_read mysql-ver)' is set as default.${end}"
-	else
-		# Default MySQL version
-		conf_write mysql-ver $mysql_default
-	fi
-	local ver=$(conf_read mysql-ver)
-	
-	# https://downloads.mariadb.org/mariadb/repositories/
-	sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
-	sudo add-apt-repository "deb [arch=amd64,arm64,ppc64el] http://mirrors.syringanetworks.net/mariadb/repo/${ver}/ubuntu $(check_osname) main"
-	
-	pre_install
-	sudo apt -y install mariadb-client
-	conf_write mysql-client true
-	echo "${gre}MySQL Client has been successfully installed!${end}"
-	api-events_update im3
 }
 
 
@@ -1478,4 +1508,3 @@ help_message() {
 	echo "${dim}Link: https://webinoly.com/documentation/ ${end}"
 	echo ""
 }
-
diff --git a/lib/verify b/lib/verify
--- a/lib/verify
+++ b/lib/verify
@@ -313,8 +313,8 @@ if [[ $(conf_read nginx-optim) == "true" ]]; then
 	fi
 fi
 
-# NGINX Tools
-if [[ $(conf_read nginx-tool) == "true" ]]; then
+# NGINX tools site
+if [[ $(conf_read nginx) == "true" ]]; then
 	if [[ ! -f /etc/nginx/sites-available/$(conf_read tools-port) && $(conf_read php) == "true" ]]; then
 		echo "- [ERROR] File: /etc/nginx/sites-available/$(conf_read tools-port) not found!"
 		ver_two_err="1"
@@ -332,7 +332,7 @@ if [[ $(conf_read nginx-tool) == "true" ]]; then
 		ver_two_err="1"
 	fi
 fi
-if [[ $(conf_read nginx-tool) != "true" && -n $(conf_read tools-port) ]]; then
+if [[ $(conf_read nginx) != "true" && -n $(conf_read tools-port) ]]; then
 	if [[ -f /etc/nginx/sites-available/$(conf_read tools-port) || -d /var/www/$(conf_read tools-port) ]]; then
 		echo "${dim}- [WARNING] Seems like Nginx Tools are enabled but Webinoly can not detect it!${end}${red}"
 		ver_two_war="1"
@@ -350,7 +350,7 @@ if [[ -n $(conf_read tools-site) && ! -L /etc/nginx/sites-enabled/$(conf_read to
 fi
 
 # NGINX Conf check
-if [[ $(conf_read nginx) != "true" && ( $(conf_read nginx-optim) == "true" || $(conf_read nginx-tool) == "true" ) ]]; then
+if [[ $(conf_read nginx) != "true" && $(conf_read nginx-optim) == "true" ]]; then
 	echo "${dim}- [WARNING] NGINX Configuration corrupted!${end}${red}"
 	ver_two_war="1"
 fi
@@ -412,7 +412,7 @@ if [[ $(conf_read php-optim) == "true" ]]; then
 fi
 
 # PHP Tools
-if [[ $(conf_read php-tool) == "true" && $(conf_read nginx) == "true" ]]; then
+if [[ $(conf_read php) == "true" && $(conf_read nginx) == "true" ]]; then
 	if [[ ! -f /var/www/$(conf_read tools-port)/htdocs/status ]]; then
 		echo "- [ERROR] File: /var/www/$(conf_read tools-port)/htdocs/ping not found!"
 		ver_three_err="1"
@@ -426,7 +426,7 @@ if [[ $(conf_read php-tool) == "true" && $(conf_read nginx) == "true" ]]; then
 		ver_three_err="1"
 	fi
 fi
-if [[ $(conf_read php-tool) != "true" && $(conf_read nginx) == "true" ]]; then
+if [[ $(conf_read php) != "true" && $(conf_read nginx) == "true" ]]; then
 	if [[ -f /var/www/$(conf_read tools-port)/htdocs/status ]]; then
 		echo "${dim}- [WARNING] Seems like PHP Tools are enabled but Webinoly can not detect it!${end}${red}"
 		ver_three_war="1"
@@ -438,7 +438,7 @@ if [[ $(conf_read php-tool) != "true" && $(conf_read nginx) == "true" ]]; then
 fi
 
 # PHP Conf check
-if [[ $(conf_read php) != "true" && ( $(conf_read php-optim) == "true" || $(conf_read php-tool) == "true" ) ]]; then
+if [[ $(conf_read php) != "true" && $(conf_read php-optim) == "true" ]]; then
 	echo "${dim}- [WARNING] PHP Configuration corrupted!${end}${red}"
 	ver_three_war="1"
 fi
@@ -501,16 +501,16 @@ if [[ $(conf_read mysql) == "true" ]]; then
 	fi
 fi
 
-if [[ $(conf_read mysql) != "true" && $(conf_read mysql-tool) == "true" ]]; then
+if [[ $(conf_read mysql) != "true" && $(conf_read mysql-tool-pma) == "true" ]]; then
 	echo "${dim}- [WARNING] MySQL Configuration corrupted!${end}${red}"
 	ver_four_war="1"
 fi
 
 # MySQL Tools
-if [[ ! -d /var/www/$(conf_read tools-port)/htdocs/pma && $(conf_read mysql-tool) == "true" ]]; then
+if [[ ! -d /var/www/$(conf_read tools-port)/htdocs/pma && $(conf_read mysql-tool-pma) == "true" ]]; then
 	echo "- [ERROR] Folder: /var/www/$(conf_read tools-port)/htdocs/pma not found!"
 	ver_four_err="1"
-elif [[ ( -d /var/www/$(conf_read tools-port)/htdocs/pma || -d /usr/share/phpmyadmin ) && $(conf_read mysql-tool) != "true" ]]; then
+elif [[ ( -d /var/www/$(conf_read tools-port)/htdocs/pma || -d /usr/share/phpmyadmin ) && $(conf_read mysql-tool-pma) != "true" ]]; then
 	echo "${dim}- [WARNING] Seems like MySQL Tools (PhpMyAdmin) are enabled but Webinoly can not detect it!${end}${red}"
 	ver_four_war="1"
 fi
@@ -561,15 +561,15 @@ if ! systemctl is-active --quiet mysql && [[ $(conf_read mysql) == "true" ]]; th
 	echo "- [ERROR] MySQL (MariaDB) service not running!"
 	ver_five_err="1"
 fi
-if ! systemctl is-active --quiet redis-server && [[ $(conf_read php-tool) == "true" ]]; then
+if ! systemctl is-active --quiet redis-server && [[ $(conf_read php-tool-redis) == "true" ]]; then
 	echo "- [ERROR] Redis service not running!"
 	ver_five_err="1"
 fi
-if ! systemctl is-active --quiet memcached && [[ $(conf_read php-tool) == "true" ]]; then
+if ! systemctl is-active --quiet memcached && [[ $(conf_read php-tool-memcached) == "true" ]]; then
 	echo "- [ERROR] Memcached service not running!"
 	ver_five_err="1"
 fi
-if ! systemctl is-active --quiet postfix && [[ $(conf_read php-tool) == "true" ]]; then
+if ! systemctl is-active --quiet postfix && [[ $(conf_read php-tool-postfix) == "true" ]]; then
 	echo "- [ERROR] Postfix service not running!"
 	ver_five_err="1"
 fi
@@ -655,21 +655,21 @@ ver_seven_err="0"
 ver_seven_war="0"
 
 # Web Tools
-if [[ $(conf_read php-tool) == "true" ]]; then
-	if [[ ! -d /etc/redis ]]; then
-		echo "- [ERROR] Folder: /etc/redis not found!"
-		ver_seven_err="1"
-	fi
-	if [[ ! -d /etc/postfix ]]; then
-		echo "- [ERROR] Folder: /etc/postfix not found!"
-		ver_seven_err="1"
-	fi
+if [[ $(conf_read php-tool-redis) == "true" && ! -d /etc/redis ]]; then
+	echo "- [ERROR] Folder: /etc/redis not found!"
+	ver_seven_err="1"
 fi
-if [[ $(conf_read nginx-tool) == "true" ]]; then
+if [[ $(conf_read php-tool-redis) == "true" && ! -d /etc/postfix ]]; then
+	echo "- [ERROR] Folder: /etc/postfix not found!"
+	ver_seven_err="1"
+fi
+if [[ $(conf_read nginx-tool-ssl) == "true" ]]; then
 	if [[ ! -f /usr/bin/duplicity ]]; then
 		echo "- [ERROR] File: /usr/bin/duplicity not found!"
 		ver_seven_err="1"
 	fi
+fi
+if [[ $(conf_read nginx-tool-bkp) == "true" ]]; then
 	if [[ ! -f /usr/bin/duply ]]; then
 		echo "- [ERROR] File: /usr/bin/duply not found!"
 		ver_seven_err="1"
