minor fixes
better check for localhost and better stack check before PMA install.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -56,6 +56,12 @@ check_for_php() {
 		exit 1
 	fi
 }
+check_for_mysql() {
+	if [[ $(conf_read mysql) != "true" ]]; then
+		echo "${red}[ERROR] MySQL is required and not found! ${end}"
+		exit 1
+	fi
+}
 
 
 conf_read() {
