wp data
Check for parked because not supported.
Localhost convertion to lowercase to avoid problems.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -150,6 +150,12 @@ conf_write() {
 wp_dbdata() {
 	local domain="$1"
 	
+	# Check for WP parked, domain mapping is common for instance.
+	if [[ $(is_parked $domain) == "true" ]]; then
+		echo "${red}[ERROR] Parked sites are not supported!${end}"
+		exit 1
+	fi
+	
 	# Get dbname and dbuser of a WP site
 	if [[ -a /var/www/$domain/htdocs$subfolder/wp-config.php ]]; then
 		wpconfpath="/var/www/$domain/htdocs$subfolder/wp-config.php"
@@ -166,9 +172,11 @@ wp_dbdata() {
 	wp_dbport=$(echo "$wp_dbhost" | cut -f 2 -d ':' -s)
 	wp_dbpref=$( grep -F "table_prefix" $wpconfpath | cut -f 2 -d "'" -s)
 	
+	[[ ${wp_dbhost,,} == "localhost" ]] && wp_dbhost=${wp_dbhost,,}
+	
 	if [[ -z $external_db && -n $wp_dbhost && $wp_dbhost != "localhost" ]]; then
 		echo ""
-		echo "${gre}External DB found in${blu} $domain ${gre}(Press 'Enter' key twice to skip and not delete)"
+		echo "${gre}External DB found in${blu} $domain ${gre}(Press 'Enter' key twice to skip)"
 		read -p "${blu}External DB root username [root]: " wp_uroot
 		wp_uroot=${wp_uroot:-root}
 		read -p "External DB root password: " wp_proot
diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -744,8 +744,11 @@ elif [[ -n $replace_content && -a /etc/nginx/sites-available/$domain ]]; then
 	if [[ $wp_dbhost == "localhost" ]]; then
 		ROOT_PASS=$( echo $(conf_read mysql-root) | openssl enc -d -a -salt )
 		sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "$query"
-	else
+	elif [[ -n $wp_dbhost ]]; then
 		sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$query"
+	else
+		echo "${red}[ERROR] Invalid WP database host!${end}"
+		exit 1
 	fi
 	echo "${gre}Content successfully replaced in your WP site!${end}"
 
