custom cache
FastCGI for PHP sites, same way and capabilities as WP cache was implemented.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -622,9 +622,11 @@ is_php() {
 	# $1 = domain, $2 = subfolder
 	if [[ -f /etc/nginx/sites-available/$1 ]]; then
 		local isphp=$(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -E " common/phpx?\.conf;")
+		[[ -n $2 ]] && local subn=$(echo $2 | sed "s/\//_/g")
 		
-		if [[ -n $2 && $(is_wp $1 $2) == "false" ]]; then
-			local subn=$(echo $2 | sed "s/\//_/g")
+		if [[ -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -E " apps.d/$1$subn-phpcache.conf;") ]]; then
+			echo "true"
+		elif [[ -n $2 && $(is_wp $1 $2) == "false" ]]; then
 			if [[ -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -E " apps\.d/$1$subn-phpx?\.conf;") ]]; then
 				echo "true"
 			else
@@ -681,7 +683,9 @@ is_wp() {
 is_wp_cache() {
 	# $1 = domain, $2 = WP subfolder
 	[[ -n $2 ]] && local subn=$(echo $2 | sed "s/\//_/g")
-	if [[ -z $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F " common/wpfc.conf;") ]]; then
+	if [[ -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -E " apps.d/$1$subn-wpcache.conf;") ]]; then
+		echo "true"
+	elif [[ -z $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F " common/wpfc.conf;") ]]; then
 		echo "true"
 	elif [[ -n $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/# WebinolyCustom/,$p' /etc/nginx/sites-available/$1 | grep -F "$1$subn-wpfc.conf;") ]]; then
 		echo "true"
@@ -689,6 +693,22 @@ is_wp_cache() {
 		echo "false"
 	fi
 }
+is_cache() {
+	# $1 = domain, $2 = WP subfolder
+	[[ -n $2 ]] && local subn=$(echo $2 | sed "s/\//_/g")
+	if [[ -z $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -F " common/wpfc.conf;") ]]; then
+		echo "wp"
+	elif [[ -n $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/# WebinolyCustom/,$p' /etc/nginx/sites-available/$1 | grep -F "$1$subn-wpfc.conf;") ]]; then
+		echo "wp"
+	elif [[ -z $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/WebinolyNginxServerStart/,$p' /etc/nginx/sites-available/$1 | grep -E " apps.d/$1-(wp|php)cache.conf;") ]]; then
+		echo "custom"
+	elif [[ -n $2 && -f /etc/nginx/sites-available/$1 && -n $(sed -n -e '/# WebinolyCustom/,$p' /etc/nginx/sites-available/$1 | grep -E "$1$subn-(wp|php)cache.conf;") ]]; then
+		echo "custom"
+	else
+		echo "false"
+	fi
+}
+
 
 is_wp_multisite() {
 	wp_conf_retrieve $1 $2
@@ -980,4 +1000,282 @@ check_var() {
 	fi
 	echo $out
 }
+
+
+config_fastcgi_cache() {
+	# This function is used alone by webinoly command.
+	# For a particular site you can use it as follows:
+	#Example: config_fastcgi_cache -site
+	#Example: config_fastcgi_cache -site [1h,1d,1m]
+	
+	if [[ $1 == "-site" && -f /etc/nginx/sites-available/$domain ]]; then
+		if [[ $(is_wp $domain $subfolder) == "true" && -f /etc/nginx/apps.d/$domain$subname-wpcache.conf ]]; then
+			local timefile="/etc/nginx/apps.d/$domain$subname-wpcache.conf"
+		elif [[ $(is_php $domain $subfolder) == "true" && -f /etc/nginx/apps.d/$domain$subname-phpcache.conf ]]; then
+			local timefile="/etc/nginx/apps.d/$domain$subname-phpcache.conf"
+		else
+			echo "${red}[ERROR] Unexpected internal error! (Wrong sitetype for custom cache)${end}"
+			exit 1
+		fi
+		
+		local mainfile="/etc/nginx/conf.d/webinoly.conf"
+		local config_cache=$2
+	else
+		local timefile="/etc/nginx/conf.d/fastcgi.conf"
+		local mainfile="/etc/nginx/conf.d/fastcgi.conf"
+	fi
+	
+
+	if [[ $(conf_read nginx) == "true" ]]; then	
+		hitline=$( grep -F "fastcgi_cache_valid 200" $timefile )
+		hitval=$(echo "${hitline//;}" | rev | cut -d' ' -f 1 | rev)
+		inaline=$( grep -F "fastcgi_cache_path" $mainfile )
+		inactive=$(echo "${inaline//;}" | rev | cut -d' ' -f 1 | rev)
+		inaval=$(echo "${inactive}" | cut -d'=' -f 2)
+		maxsize=$(echo "${inaline}" | rev | cut -d' ' -f 2 | rev)
+		othline=$( grep -F "fastcgi_cache_valid 301 302 303 307 308 404 410 451" $timefile )
+		othval=$(echo "${othline//;}" | rev | cut -d' ' -f 1 | rev)
+	elif [[ -n $(conf_read fastcgi-conf) ]]; then
+		hitval=$( echo $(conf_read fastcgi-conf) | cut -d',' -f 1 -s )
+		inaval=$( echo $(conf_read fastcgi-conf) | cut -d',' -f 2 -s )
+		othval=$( echo $(conf_read fastcgi-conf) | cut -d',' -f 3 -s )
+	else
+		hitval="Not yet defined"
+		inaval="Not yet defined"
+		othval="Not yet defined"
+	fi
+
+	
+	if [[ $config_cache == true ]]; then
+		echo "${gre}"
+		echo "**********************************************************************"
+		echo "*************     Set FastCGI Cache new time values     **************"
+		echo "*****  Example: 30d = 30days  |  3h = 3hours  |  5m = 5minutes  ******"
+		echo "**********************************************************************"
+		echo "${blu}"
+		echo "FastCGI Cache Valid for Pages (HttpCode: 200) actual value is: $hitval"
+		read -p "   Set new value: " hit
+		hit=${hit:-$hitval}
+		echo ""
+		echo "Purge Cache for inactive pages actual value is: $inaval"
+		read -p "   Set new value: " ina
+		ina=${ina:-$inaval}
+		echo ""
+		echo "FastCGI Cache Valid for Errors and Redirections (301 302 303 307 308 404 410 451) actual value is: $othval"
+		read -p "   Set new value: " oth
+		oth=${oth:-$othval}
+		echo ""
+	elif [[ $(echo "${config_cache}" | cut -c-1) == "[" && $(echo "${config_cache}" | rev | cut -c-1) == "]" ]]; then
+		custombegin=$(echo "${config_cache}" | cut -c-1)
+		customlast=$(echo "${config_cache}" | rev | cut -c-1)
+		
+		# No need for check var lenght to prevent errors, the previous condition is enough in this case.
+		cachedata=${config_cache:1:-1}
+			
+		hit=$(echo "${cachedata}" | cut -d',' -f 1 )
+		ina=$(echo "${cachedata}" | cut -d',' -f 2 )
+		oth=$(echo "${cachedata}" | cut -d',' -f 3 )
+	else
+		echo "${red}[ERROR] Please enter a valid value!${end}"
+		exit 1
+	fi
+	
+	if [[ "$hit" =~ ^[0-9]+[smhdwMy]$ && "$ina" =~ ^[0-9]+[smhdwMy]$ && "$oth" =~ ^[0-9]+[smhdwMy]$ ]]; then
+		if [[ $(conf_read nginx) == "true" ]]; then	
+			[[ $1 == "-site" ]] && local path="/run/nginx-cache/$(echo $domain | sed 's/[^0-9A-Za-z]/_/g')$subname" || local path="/run/nginx-cache"
+			local cachepath=$(grep -F "fastcgi_cache_path $path " $mainfile)
+			local newcachepath=$(echo $cachepath | sed "s/ inactive=.*[a-z]/ inactive=$ina/")
+			
+			if [[ -n $cachepath && -n $newcachepath ]]; then
+				sudo sed -i "s#$cachepath#$newcachepath#" $mainfile
+			else
+				echo "${red}[ERROR] Unexpected error! (Cache configuration corrupted)${end}"
+				exit 1
+			fi
+			
+			sudo sed -i "/fastcgi_cache_valid 200/c \fastcgi_cache_valid 200 ${hit};" $timefile
+			sudo sed -i "/fastcgi_cache_valid 301 302 /c \fastcgi_cache_valid 301 302 303 307 308 404 410 451 ${oth};" $timefile
+			sudo sed -i '/^fastcgi_/s/^/	/' $timefile
+		fi
+		
+		[[ $1 == "-site" ]] || conf_write fastcgi-conf ${hit},${ina},${oth}
+		echo "${gre}FastCGI Cache values has been successfully updated!${end}"
+	else
+		echo "${red}[ERROR] Invalid values!${end}"
+		exit 1
+	fi
+}
+
+
+custom_cache_global() {
+	# This function is used alone by webinoly command.
+	# For a particular site you can use it as follows:
+	# Example: custom_cache_global -site
+	
+	if [[ $1 == "-site" && -f /etc/nginx/sites-available/$domain ]]; then
+		if [[ ( $(is_wp $domain $subfolder) == "true" && -f /etc/nginx/apps.d/$domain$subname-wpcache.conf ) || ( $(is_php $domain $subfolder) == "true" && -f /etc/nginx/apps.d/$domain$subname-phpcache.conf )]]; then
+			local confile="/etc/nginx/apps.d/${domain}${subname}-site_custom_cache.conf"
+			local mark="_$(echo $domain | sed "s/[^0-9A-Za-z]/_/g")${subname}"
+		else
+			echo "${red}[ERROR] Custom cache not found! ${dim}(Must be enabled at least once before you can add these custom rules)${end}"
+			exit 1
+		fi
+	else
+		local confile="/etc/nginx/apps.d/global_custom_cache.conf"
+	fi
+	
+	
+	
+	if [[ -n $list ]]; then
+		[[ -n $raw || $list == "raw" ]] && echo "" || echo "${gre}"
+		
+		if [[ -f $confile ]]; then
+			[[ -n $query_string_never_cache ]] && local id="NeverCacheQueryString"
+			[[ -n $query_string_cache ]] && local id="CacheQueryString"
+			[[ -n $skip_cookie_cache ]] && local id="CacheSkipCookie"
+			[[ -n $skip_cache ]] && local id="CacheSkipURL"
+			
+			local isem=$(sudo sed -n "/# Value: /{h;d;}; H; /# $id/{x;p;}" $confile)
+			
+			if [[ -n $raw || $list == "raw" ]]; then
+				sudo sed -n "/# Value: /{h;d;}; H; /# $id/{x;p;}" $confile | sed -n '/# Value:/p' | sed 's/# Value: //g'
+			else
+				sudo sed -n "/# Value: /{h;d;}; H; /# $id/{x;p;}" $confile | sed -n '/# Value:/p' | sed 's/# Value: /+ /g'
+			fi
+		fi
+		[[ -z $isem && -z $raw && $list != "raw" ]] && echo "${blu}[Empty] No Cache Rules were found!${end}"
+	
+		[[ -n $raw || $list == "raw" ]] && echo "" || echo "${end}"
+	elif [[ -n $delete ]]; then
+		echo ""
+		[[ $skip_cache == "true" ]] && read -p "${blu}Cache Skip URL to delete: ${end}" skip_cache
+		[[ $skip_cookie_cache == "true" ]] && read -p "${blu}Cache Skip Cookie to delete: ${end}" skip_cookie_cache
+		[[ $query_string_cache == "true" ]] && read -p "${blu}Cache Query String to delete: ${end}" query_string_cache
+		[[ $query_string_never_cache == "true" ]] && read -p "${blu}Never Cache this Query String to delete: ${end}" query_string_never_cache
+		if [[ -z $query_string_cache && -z $query_string_never_cache && -z $skip_cache && -z $skip_cookie_cache ]]; then
+			echo "${red}[ERROR] Please, enter a valid value!${end}"
+			exit 1
+		fi
+		
+		if [[ -f $confile ]]; then
+			[[ -n $query_string_never_cache ]] && local value=$query_string_never_cache
+			[[ -n $query_string_cache ]] && local value=$query_string_cache
+			[[ -n $skip_cookie_cache ]] && local value=$skip_cookie_cache
+			[[ -n $skip_cache ]] && local value=$skip_cache
+			
+			sudo sed -Ei "/^# Value: $(escaped_string $value)( .*)?$/,/^# CacheRuleEnd/{/.*/d}" $confile
+			[[ ! -s $confile ]] && sudo rm $confile
+		fi
+		echo "${gre}Cache rule successfully removed!${end}"
+	else
+		echo ""
+		[[ $skip_cache == "true" ]] && read -p "${blu}Cache Skip URL: ${end}" skip_cache
+		[[ $skip_cookie_cache == "true" ]] && read -p "${blu}Cache Skip Cookie: ${end}" skip_cookie_cache
+		[[ $query_string_cache == "true" ]] && read -p "${blu}Cache Query String: ${end}" query_string_cache
+		[[ $query_string_never_cache == "true" ]] && read -p "${blu}Never Cache this Query String: ${end}" query_string_never_cache
+		echo ""
+		
+		if [[ -z $query_string_cache && -z $query_string_never_cache && -z $skip_cache && -z $skip_cookie_cache ]]; then
+			echo "${red}[ERROR] Please, enter a valid value!${end}"
+			exit 1
+		elif [[ -n $regex && ( -n $query_string_cache || -n $query_string_never_cache ) ]]; then
+			echo "${red}[ERROR] Regex not allowed for Query-String custom rules!${end}"
+			exit 1
+		elif [[ $skip_cache == "/" && -z $regex ]]; then
+			echo "${red}[ERROR] Root folder not allowed, use regex or disable site cache!${end}"
+			exit 1
+		elif [[ -n $regex ]] && ! [[ $regex =~ ^(sensitive|insensitive)$ ]]; then
+			echo "${red}[ERROR] Invalid regex value!${end}"
+			exit 1
+		elif [[ -z $regex &&  -n $skip_cache && $(is_url_path $skip_cache) != "true" ]]; then
+			echo "${red}[ERROR] Invalid URL!${end}"
+			exit 1
+		elif [[ -z $regex && -n $skip_cookie_cache ]] && ! [[ $skip_cookie_cache =~ ^([\]A-Za-z0-9_\/\.:\!\*\'\[\(\)\;@\&\=\+\$\,\?#\~\%\-]+)?$ ]]; then
+			echo "${red}[ERROR] Invalid Cookie String!${end}"
+			exit 1
+		elif [[ -z $regex && -n $query_string_cache ]] && ! [[ $query_string_cache =~ ^([\]A-Za-z0-9_\/\.:\!\*\'\[\(\)\;@\&\=\+\$\,\?#\~\%\-]+)?$ ]]; then
+			echo "${red}[ERROR] Invalid Query String!${end}"
+			exit 1
+		elif [[ -z $regex && -n $query_string_never_cache ]] && ! [[ $query_string_never_cache =~ ^([\]A-Za-z0-9_\/\.:\!\*\'\[\(\)\;@\&\=\+\$\,\?#\~\%\-]+)?$ ]]; then
+			echo "${red}[ERROR] Invalid Query String!${end}"
+			exit 1
+		fi
+		
+		if [[ ! -f $confile ]]; then
+			sudo touch $confile
+			sudo chmod 644 $confile
+			sudo chown -R root:root $confile
+		fi
+		
+		[[ -n $query_string_never_cache ]] && local value=$query_string_never_cache
+		[[ -n $query_string_cache ]] && local value=$query_string_cache
+		[[ -n $skip_cookie_cache ]] && local value=$skip_cookie_cache
+		[[ -n $skip_cache ]] && local value=$skip_cache
+		
+		local exist=$( grep -E "^# Value: $(escaped_string $value)( .*)?$" $confile )
+		
+		if [[ -z $exist ]]; then
+			if [[ $regex == "sensitive" ]]; then
+				sign="~"
+				code="$value (Regex)"
+			elif [[ $regex == "insensitive" ]]; then
+				sign="~*"
+				code="$value (Regex)"
+			else
+				sign="="
+				code="$value"
+			fi
+			
+			if [[ -n $query_string_never_cache ]]; then
+				echo "# Value: $code
+# NeverCacheQueryString
+if (\$arg_${value}) {
+	set \$skip_cache${mark} 1;
+}
+# CacheRuleEnd" >> $confile
+			elif [[ -n $skip_cookie_cache ]]; then
+				echo "# Value: $code
+# CacheSkipCookie
+if (\$http_cookie $sign $value) {
+	set \$skip_cache${mark} 1;
+}
+# CacheRuleEnd" >> $confile
+			elif [[ -n $query_string_cache ]]; then
+				# Sed can not write when file is empty
+				[[ ! -s $confile ]] && echo ' ' >> $confile
+				sudo sed -i "1i # Value: $code\n# CacheQueryString\nif (\$arg_${value}) {\n	set \$skip_cache${mark} 0;\n}\n# CacheRuleEnd" $confile
+			elif [[ -n $skip_cache ]]; then
+				[[ ! -s $confile ]] && echo ' ' >> $confile
+				sudo sed -i "1i # Value: $code\n# CacheSkipURL\nif (\$request_uri $sign $value) {\n	set \$skip_cache${mark} 1;\n}\n# CacheRuleEnd" $confile
+			fi
+			
+			# Last verification
+			if ! sudo nginx -t > /dev/null 2>&1; then
+				if [[ $1 == "-site" && -n $subfolder ]]; then
+					[[ -n $query_string_never_cache ]] && sudo site $domain -subfolder=$subfolder -cache=custom -query-string-never-cache=$query_string_never_cache -delete > /dev/null 2>&1
+					[[ -n $query_string_cache ]] && sudo site $domain -subfolder=$subfolder -cache=custom -query-string-cache=$query_string_cache -delete > /dev/null 2>&1
+					[[ -n $skip_cookie_cache ]] && sudo site $domain -subfolder=$subfolder -cache=custom -skip-cookie-cache=$skip_cookie_cache -delete > /dev/null 2>&1
+					[[ -n $skip_cache ]] && sudo site $domain -subfolder=$subfolder -cache=custom -skip-cache=$skip_cache -delete > /dev/null 2>&1
+				elif [[ $1 == "-site" ]]; then
+					[[ -n $query_string_never_cache ]] && sudo site $domain -cache=custom -query-string-never-cache=$query_string_never_cache -delete > /dev/null 2>&1
+					[[ -n $query_string_cache ]] && sudo site $domain -cache=custom -query-string-cache=$query_string_cache -delete > /dev/null 2>&1
+					[[ -n $skip_cookie_cache ]] && sudo site $domain -cache=custom -skip-cookie-cache=$skip_cookie_cache -delete > /dev/null 2>&1
+					[[ -n $skip_cache ]] && sudo site $domain -cache=custom -skip-cache=$skip_cache -delete > /dev/null 2>&1
+				else
+					[[ -n $query_string_never_cache ]] && sudo webinoly -query-string-never-cache=$query_string_never_cache -delete > /dev/null 2>&1
+					[[ -n $query_string_cache ]] && sudo webinoly -query-string-cache=$query_string_cache -delete > /dev/null 2>&1
+					[[ -n $skip_cookie_cache ]] && sudo webinoly -skip-cookie-cache=$skip_cookie_cache -delete > /dev/null 2>&1
+					[[ -n $skip_cache ]] && sudo webinoly -skip-cache=$skip_cache -delete > /dev/null 2>&1
+				fi
+				echo "${red}[ERROR] Seems like you are using some invalid Nginx values or characters!${end}"
+				exit 1
+			fi
+			
+			echo "${gre}Cache rule successfully added!${end}"
+		else
+			echo "${gre}Cache rule already exists!${end}"
+		fi
+	fi
+}
+
 
diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -583,6 +583,12 @@ deletesite() {
 	sudo rm -rf /etc/nginx/sites-enabled/$domain
 	sudo rm -rf /var/www/$domain
 	
+	# In case of custom cache
+	if [[ -f /etc/nginx/conf.d/webinoly.conf ]]; then
+		sudo sed -i "/^fastcgi_cache_path \/run\/nginx-cache\/$(echo $domain | sed 's/[^0-9A-Za-z]/_/g').*/d" /etc/nginx/conf.d/webinoly.conf
+		[[ ! -s /etc/nginx/conf.d/webinoly.conf ]] && sudo rm /etc/nginx/conf.d/webinoly.conf
+	fi
+	
 	echo "${gre}Site${blu} $domain ${gre}has been successfully deleted!${end}"
 }
 
@@ -1180,25 +1186,53 @@ reverse_proxy() {
 
 
 wp_cache() {
-	if [[ $cache == "off" && -f /etc/nginx/sites-available/$domain ]]; then
+	if [[ $cache == "off" ]]; then
 		api-events_update si9
-		if [[ -n $subfolder && $(is_wp_cache $domain $subfolder) == "true" ]]; then
+		if [[ $(is_cache $domain $subfolder) == "custom" ]]; then			
+			if [[ $(conf_read php-info) != "false" && $(is_wp $domain $subfolder) != "true" ]]; then
+				if [[ -z $subfolder ]]; then
+					sudo sed -i "/apps.d\/$domain$subname-.*cache.conf;/c \	include common/phpx.conf;" /etc/nginx/sites-available/$domain
+				elif [[ -n $subfolder && -f /etc/nginx/apps.d/$domain$subname-phpx.conf ]]; then
+					sudo sed -i "/apps.d\/$domain$subname-.*cache.conf;/c \	include apps.d/$domain$subname-phpx.conf;" /etc/nginx/sites-available/$domain
+				elif [[ -n $subfolder && ! -f /etc/nginx/apps.d/$domain$subname-phpx.conf ]]; then
+					# Try with the other PHP option
+					if [[ -n $subfolder && -f /etc/nginx/apps.d/$domain$subname-php.conf ]]; then
+						sudo sed -i "/apps.d\/$domain$subname-.*cache.conf;/c \	include apps.d/$domain$subname-php.conf;" /etc/nginx/sites-available/$domain
+					else
+						echo "${red}[ERROR] PHP Configuration file not found!${end}"
+						exit 1
+					fi
+				fi
+			else
+				# WP sites are forced to take this option
+				if [[ -z $subfolder ]]; then
+					sudo sed -i "/apps.d\/$domain$subname-.*cache.conf;/c \	include common/php.conf;" /etc/nginx/sites-available/$domain
+				elif [[ -n $subfolder && -f /etc/nginx/apps.d/$domain$subname-php.conf ]]; then
+					sudo sed -i "/apps.d\/$domain$subname-.*cache.conf;/c \	include apps.d/$domain$subname-php.conf;" /etc/nginx/sites-available/$domain
+				elif [[ -n $subfolder && ! -f /etc/nginx/apps.d/$domain$subname-php.conf ]]; then
+					# Try with the other PHP option (except if site is WP)
+					if [[ -n $subfolder && -f /etc/nginx/apps.d/$domain$subname-phpx.conf && $(is_wp $domain $subfolder) != "true" ]]; then
+						sudo sed -i "/apps.d\/$domain$subname-.*cache.conf;/c \	include apps.d/$domain$subname-phpx.conf;" /etc/nginx/sites-available/$domain
+					else
+						echo "${red}[ERROR] PHP Configuration file not found!${end}"
+						exit 1
+					fi
+				fi
+			fi
+			
+			echo "${gre}Custom FastCGI Cache in${blu} $domain ${gre}has been disabled!${end}"
+		elif [[ -n $subfolder && $(is_cache $domain $subfolder) == "wp" ]]; then
 			sudo sed -i "/apps.d\/$domain$subname-wpfc.conf;/c \	include apps.d/$domain$subname-php.conf;" /etc/nginx/sites-available/$domain
 			echo "${gre}FastCGI Cache in${blu} $domain$subfolder ${gre}has been disabled!${end}"
-		elif [[ $(is_wp_cache $domain) == "true" ]]; then
+		elif [[ $(is_cache $domain) == "wp" ]]; then
 			sudo sed -i '/common\/wpfc.conf/c \	include common/php.conf;' /etc/nginx/sites-available/$domain
 			echo "${gre}FastCGI Cache in${blu} $domain ${gre}has been disabled!${end}"
 		else
-			if [[ $(is_wp $domain $subfolder) == "false" ]]; then
-				echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is not a WP site!${end}"
-				exit 1
-			else
-				echo "${gre}FastCGI Cache is already disabled on your site${blu} $domain${end}"
-			fi
+			echo "${gre}FastCGI Cache is already disabled on your site${blu} $domain${end}"
 		fi	
-	elif [[ $cache == "on" && -f /etc/nginx/sites-available/$domain ]]; then
+	elif [[ $cache == "on" ]]; then
 		api-events_update si8
-		if [[ $(is_wp $domain $subfolder) == "true" && $(is_wp_cache $domain $subfolder) == "false" ]]; then
+		if [[ $(is_wp $domain $subfolder) == "true" && $(is_cache $domain $subfolder) == "false" ]]; then
 			[[ -z $subfolder ]] && sudo sed -i '/ common\/php.conf/c \	include common/wpfc.conf;' /etc/nginx/sites-available/$domain
 			[[ -n $subfolder ]] && sudo sed -i "/ apps.d\/$domain$subname-php.conf;/c \	include apps.d/$domain$subname-wpfc.conf;" /etc/nginx/sites-available/$domain
 			if [[ $(is_parked $domain) == "false" && ( ! -d /var/www/$domain/htdocs$subfolder/wp-content/plugins/nginx-helper || ! -d /var/www/$domain/htdocs$subfolder/wp-content/plugins/redis-cache ) ]]; then
@@ -1229,6 +1263,91 @@ wp_cache() {
 			else
 				echo "${gre}FastCGI Cache is already enabled on your site${blu} $domain$subfolder${end}"
 			fi
+		fi
+	elif [[ $cache == "custom" ]]; then
+		if [[ $(is_wp $domain $subfolder) == "true" ]]; then
+			local fn="wpcache"
+		elif [[ $(is_php $domain $subfolder) == "true"  ]]; then
+			local fn="phpcache"
+		else
+			echo "${red}[ERROR] Custom Cache only supported for PHP and WordPress sites!${end}"
+			exit 1
+		fi
+		
+		[[ -z $reset ]] && api-events_update si8
+		
+		if [[ -n $reset ]]; then
+			if [[ $(is_cache $domain $subfolder) == "custom" ]]; then
+				echo "${red}[ERROR] Cannot remove the Custom Cache configuration file because is currently in use!${end}"
+				exit 1
+			elif [[ -f /etc/nginx/apps.d/$domain$subname-${fn}.conf ]]; then
+				sudo rm /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i "/^fastcgi_cache_path \/run\/nginx-cache\/$(echo $domain | sed 's/[^0-9A-Za-z]/_/g')${subname} .*/d" /etc/nginx/conf.d/webinoly.conf
+				[[ -f /etc/nginx/conf.d/webinoly.conf && ! -s /etc/nginx/conf.d/webinoly.conf ]] && sudo rm /etc/nginx/conf.d/webinoly.conf
+				echo "${gre}Custom FastCGI Cache configuration file has been successfully removed! ${end}"
+			else
+				echo "${gre}Custom FastCGI Cache configuration file not found! ${end}"
+			fi
+		elif [[ -n $query_string_never_cache || $query_string_cache || $skip_cache || -n $skip_cookie_cache ]]; then
+			custom_cache_global -site
+		elif [[ $(is_cache $domain $subfolder) == "false" ]]; then
+			[[ -z $subfolder ]] && sudo sed -i "/ common\/php.conf/c \	include apps.d/$domain$subname-${fn}.conf;" /etc/nginx/sites-available/$domain
+			[[ -z $subfolder ]] && sudo sed -i "/ common\/phpx.conf/c \	include apps.d/$domain$subname-${fn}.conf;" /etc/nginx/sites-available/$domain
+			[[ -n $subfolder ]] && sudo sed -i "/ apps.d\/$domain$subname-php.conf;/c \	include apps.d/$domain$subname-${fn}.conf;" /etc/nginx/sites-available/$domain
+			[[ -n $subfolder ]] && sudo sed -i "/ apps.d\/$domain$subname-phpx.conf;/c \	include apps.d/$domain$subname-${fn}.conf;" /etc/nginx/sites-available/$domain
+			
+			# Creates the custom Webinoly Cache File (.cnf) only if not exists.
+			if [[ ! -f /etc/nginx/apps.d/$domain$subname-${fn}.conf ]]; then
+				sudo touch /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo chmod 644 /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo chown -R root:root /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				
+				if [[ ! -f /etc/nginx/conf.d/webinoly.conf ]]; then
+					sudo touch /etc/nginx/conf.d/webinoly.conf
+					sudo chmod 644 /etc/nginx/conf.d/webinoly.conf
+					sudo chown -R root:root /etc/nginx/conf.d/webinoly.conf
+				fi
+				
+				# Cache Size for custom cache will be half of the global value by default
+				local cachesize=$(($(grep -F "fastcgi_cache_path " /etc/nginx/conf.d/fastcgi.conf | grep -Eo "max_size=.*m" | cut -d "=" -f 2 -s | grep -Eo "[0-9]+")/2))
+				[[ -n $cachesize && $cachesize =~ ^[0-9]+$ && $cachesize -gt 0 ]] || local cachesize=90
+				
+				local dom=$(echo $domain | sed "s/[^0-9A-Za-z]/_/g")
+				echo "fastcgi_cache_path /run/nginx-cache/${dom}${subname} levels=1:2 keys_zone=${dom}${subname}:50m max_size=${cachesize}m inactive=7d;" >> /etc/nginx/conf.d/webinoly.conf
+				
+				echo -e "# Webinoly Custom FastCGI Cache File \n" >> /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo cat /etc/nginx/common/wpfc.conf >> /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i '/# WPFC NGINX CONFIGURATION/,/# Use cached or actual file if they exists/{/.*/d}' /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i '/fastcgi_cache WORDPRESS;/r /etc/nginx/conf.d/fastcgi.conf' /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i '/# FastCGI cache settings/,/fastcgi_cache_path /{/.*/d}' /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i "/fastcgi_cache WORDPRESS;/c \	fastcgi_cache ${dom}${subname};" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i "s/ \$skip_cache/ \$skip_cache_${dom}${subname}/g" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i '/^fastcgi_/s/^/	/' /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				
+				sudo sed -i "/^# Webinoly Custom FastCGI Cache File /a include apps.d/${domain}${subname}*site_custom_cache.conf;" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				sudo sed -i "/^# Webinoly Custom FastCGI Cache File /a set \$skip_cache_${dom}${subname} 0;" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				
+				if [[ -n $subfolder ]]; then
+					sudo sed -i "/^location \/ {/c location $subfolder/ {" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+					sudo sed -i "/^location ~\* /c location ~* $subfolder/\.*\\\.php\$ {" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+					sudo sed -i "s#/index.php#$subfolder/index.php#" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+					[[ $(is_wp $domain $subfolder) == "true" ]] && sudo sed -i "/^# Webinoly Custom FastCGI Cache File /a include apps.d/$domain$subname-wpcommon.conf;" /etc/nginx/apps.d/$domain$subname-${fn}.conf
+				fi
+				
+				echo "${gre}${dim}A new FastCGI Cache configuration file has been created!${end}"
+			else
+				echo "${gre}${dim}FastCGI Cache configuration file found!${end}"
+			fi
+			
+			[[ -n $times && $times != "true" ]] && config_fastcgi_cache -site $times
+			
+			echo "${gre}"
+			echo "Custom FastCGI Cache in${blu} $domain$subfolder ${gre}has been successfully enabled! "
+			echo "${end}"
+		elif [[ -n $times ]]; then	
+			config_fastcgi_cache -site $times
+		else
+			echo "${gre}FastCGI Cache is already enabled on your site${blu} $domain$subfolder${end}"
 		fi
 	else
 		echo "${red}[ERROR] Invalid value for cache! ${end}"
