domain mapping
Fixed issue when SSL is enabled in main site.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -415,22 +415,6 @@ wp_conf_retrieve() {
 		fi		
 	fi
 	
-	# Force WP blogID
-	if [[ -n $force_wp_blog_id && $3 != "false" && $force_wp_blog_id =~ ^[0-9]+$ ]]; then
-		wp_dbpref="${wp_dbpref}${force_wp_blog_id}_"
-		wp_blogid=${force_wp_blog_id}
-		local dbsetup="SELECT * FROM information_schema.tables WHERE table_schema = '$wp_dbname' AND table_name = '${wp_dbpref}options' LIMIT 1;"
-		force_wp_blog_id="" # Cleared to prevent interference when this function is called multiple times
-		
-		if [[ -n $(sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "$dbsetup") ]]; then
-			echo "${blu}${dim}WordPress blog ID (${wp_dbpref}) found and validated in a WP Multisite Network!${end}" >&2
-		else
-			echo "${red}${dim}[ERROR] WordPress blog ID (${wp_dbpref}) not found!${end}" >&2
-			wp_dbpref=""
-			wp_blogid=""
-		fi
-	fi
-	
 	
 	if [[ $2 != "false" ]]; then
 		if [[ -z $external_db && -n $wp_dbhost && $wp_dbhost != "localhost" && $wp_dbhost == "$(conf_read external-dbh):$(conf_read external-dbx)" ]]; then
@@ -1004,10 +988,24 @@ email_update() {
 
 edit_wp_db_url_multisite() {
 	#Subfolder is not allowed here because is not needed, parked and force-www are not allowed in subfolders.
-	#Example: edit_wp_db_url_multisite olddomain.com newdomain.com
+	#Example: edit_wp_db_url_multisite olddomain.com newdomain.com 2
+	# $3 - WP BlogID to force
 	
-	if [[ -n $1 && -n $2 && $(is_wp_multisite $1) =~ ^(subdomain|subdirectory)$ ]]; then
-		wp_conf_retrieve $1 true true
+	if [[ -n $1 && -n $2 && -n $3 && $3 =~ ^[0-9]+$ && $(is_wp_multisite $1) =~ ^(subdomain|subdirectory)$ ]]; then
+		wp_conf_retrieve $1 true false
+		
+		# Force WP blogID
+		local wp_dbpref="${wp_dbpref}${3}_"
+		local wp_blogid=$3
+		local dbsetup="SELECT * FROM information_schema.tables WHERE table_schema = '$wp_dbname' AND table_name = '${wp_dbpref}options' LIMIT 1;"
+		if [[ -n $(sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS -e "$dbsetup") ]]; then
+			echo "${blu}${dim}WordPress blog ID (${wp_dbpref}) found and validated in a WP Multisite Network!${end}" >&2
+		else
+			echo "${red}${dim}[ERROR] WordPress blog ID (${wp_dbpref}) not found!${end}" >&2
+			wp_dbpref=""
+			wp_blogid=""
+		fi
+		
 		if [[ -n $wp_dbhost && -n $wp_dbname && -n $wp_dbpref_main && -n $wp_blogid ]]; then
 			if [[ $wp_dbhost == "localhost" && $(check_mysql_connection localhost) == "true" ]]; then
 				sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS <<_EOF_
