delete site improved
Now we have the new "external-db" option to pass user and password  for external DB's, also work for delete-all.
Now we have support for keep-db option when deleting a site.
Delete-all now use the same delete function.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -55,9 +55,14 @@ db_delete() {
 				echo "${gre}Database of your site ${blu}${domain}${gre} has been successfully deleted! ${end}"
 			fi
 		else
-			if [[ $dbdatadel == "true" ]]; then
-				local uroot=$(echo "${dbdata}" | cut -d',' -f 3 -s)
-				local proot=$(echo "${dbdata}" | cut -d',' -f 4 -s)
+			if [[ -n $external_db ]]; then
+				dbdata=${external_db:1:-1}
+				uroot=$(echo "${dbdata}" | cut -d',' -f 1 -s)
+				proot=$(echo "${dbdata}" | cut -d',' -f 2 -s)
+				if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" || -z $uroot || -z $proot ]]; then
+					echo "${red}[ERROR] Invalid data for External Database!${end}"
+					exit 1
+				fi
 			fi
 			if [[ -z $uroot || -z $proot ]]; then
 				echo ""
@@ -67,7 +72,7 @@ db_delete() {
 				read -p "External DB root password: " proot
 			fi
 			if [[ $uroot == "root" && -z $proot ]]; then
-				echo "${red} Action aborted, database not deleted!"
+				echo "${red}Action aborted, database not deleted!"
 				continue 1;
 			else
 				if [[ $(conf_read mysql-client) != "true" ]]; then
