db roles
Now we have a command to set the default role.
Also, dbrole can be assigned when a site is created.
Fixed, duplicated lines in wp-config.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -350,7 +350,7 @@ wp_config_write() {
 	if [[ -n $path && -n $(wp_config_read $1 $2 $4) ]]; then
 		sudo sed -i "/$(grep -iE "^define[ ]?\([ ]?[\"'\'']$2[\"'\''].*$" $path)/c \define('$2', $3);" $path
 	elif [[ -n $path ]]; then
-		sudo sed -i "/stop editing/i \define('$2', $3);" $path
+		sudo sed -i "/ stop editing! /i \define('$2', $3);" $path
 	fi
 }
 
@@ -1003,22 +1003,35 @@ _EOF_
 }
 
 
+db_role_check() {
+	if ! [[ $1 =~ ^(basic|limited|extra|complete|full|all|grant)$ ]]; then
+		echo "${red}[ERROR] Please, enter a valid database role!${end}"
+		[[ -n $db_role ]] && db_role=""
+		[[ $2 == "unattended" ]] && echo "${dim}We will use the default db role!${end}" || exit 1
+	elif [[ $1 == "basic" ]]; then
+		echo "${dim}[WARNING] You have set basic privileges for your databases. Some sites, like WordPress, could NOT work properly!${end}"
+	fi
+}
 db_user_role() {
 	# Can't be used on not global users: FILE,REPLICATION CLIENT,REPLICATION SLAVE,PROCESS,SHOW DATABASES,CREATE USER,RELOAD,GRANT,SUPER,SHUTDOWN
 	# FILE Privilege not supported by external DB's: http://cloudofnines.blogspot.com/2014/09/in-rds-instances-file-privilege-for.html
 	# AWS RDS Reference: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.MasterAccounts.html
 	# ALL PRIVILEGES not supported for external DB's.
 	
-	if [[ $(conf_read dbrole) == "all" ]]; then
+	[[ -z $db_role ]] && db_role=$(conf_read dbrole)
+	
+	if [[ $db_role == "all" ]]; then
 		local priv="ALL PRIVILEGES"
-	elif [[ $(conf_read dbrole) == "basic" ]]; then
+	elif [[ $db_role == "basic" ]]; then
 		local priv="SELECT,INSERT,UPDATE,DELETE"
-	elif [[ $(conf_read dbrole) == "limited" ]]; then
+	elif [[ $db_role == "limited" ]]; then
 		local priv="SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER"
-	elif [[ $(conf_read dbrole) == "extra" ]]; then
+	elif [[ $db_role == "extra" ]]; then
 		local priv="SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,LOCK TABLES"
-	elif [[ $(conf_read dbrole) == "complete" ]]; then
+	elif [[ $db_role == "complete" ]]; then
 		local priv="SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,EXECUTE,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,EVENT,TRIGGER"
+	elif [[ $db_role == "grant" ]]; then
+		local priv="SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,EXECUTE,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,EVENT,TRIGGER,REFERENCES,LOCK TABLES,GRANT OPTION"
 	else # full (DEFAULT)
 		local priv="SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,EXECUTE,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,EVENT,TRIGGER,REFERENCES,LOCK TABLES"
 	fi
