better site check
Now we have an option to check for nginx and php including tools and optim.
Subfolder option now check if subfolder exists.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -69,6 +69,12 @@ check_for_nginx() {
 		exit 1
 	fi
 }
+check_for_nginx_tool() {
+	if [[ $(conf_read nginx) != "true"  || $(conf_read nginx-optim) != "true" || $(conf_read nginx-tool) != "true" ]]; then
+		echo "${red}[ERROR] NGINX Tools are required and not found! ${end}"
+		exit 1
+	fi
+}
 check_for_php() {
 	if [[ $(conf_read php) != "true" && $1 == "-ask" ]]; then
 		echo "${red}"
@@ -85,6 +91,12 @@ check_for_php() {
 	
 	if [[ $(conf_read php) != "true" ]]; then
 		echo "${red}[ERROR] PHP is required and not found! ${end}"
+		exit 1
+	fi
+}
+check_for_php_tool() {
+	if [[ $(conf_read php) != "true"  || $(conf_read php-optim) != "true" || $(conf_read php-tool) != "true" ]]; then
+		echo "${red}[ERROR] PHP Tools are required and not found! ${end}"
 		exit 1
 	fi
 }
diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -110,9 +110,11 @@ fi
 if [[ -n $subfolder && ! ( $subfolder =~ ^\/([A-Za-z0-9_\/\-]+)?[^\/]$ ) ]]; then
 	echo "${red}[ERROR] Please, enter a valid value for subfolder!${end}"
 	exit 1
-fi
-if [[ -n $subfolder && $type != [123] && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content ]]; then
+elif [[ -n $subfolder && $type != [123] && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content ]]; then
 	echo "${red}[ERROR] Subfolder option is only supported for WordPress sites!${end}"
+	exit 1
+elif [[ -n $subfolder && ( -n $delete || -n $cache || -n $yoast_sitemap || -n $multisite_convert || -n $clone_from || -n $replace_content ) && ! -d /var/www/$domain/htdocs$subfolder ]]; then
+	echo "${red}[ERROR] Subfolder not found!${end}"
 	exit 1
 else
 	subname=$(echo $subfolder | sed "s/\//_/g")
@@ -523,6 +525,9 @@ elif [[ -n $ssl ]]; then
 	elif [[ $ssl == "off" && ! -a /etc/nginx/sites-available/$domain && -a /etc/letsencrypt/live/$domain/cert.pem ]]; then
 		echo "${red}[WARNING] SSL Orphan-Cert found and will be revoked automatically!${end}"
 		ssl_revoke
+	elif [[ -n $domain && ! -f /etc/nginx/sites-available/$domain ]]; then
+		echo "${red}[ERROR] Domain not found! ${end}"
+		exit 1
 	else
 		echo "${red}[ERROR] Invalid value for SSL command! ${end}"
 		exit 1
