Check distro name
Check distro name before Webinoly and MariaDB installation.

diff --git a/lib/general b/lib/general
--- a/lib/general
+++ b/lib/general
@@ -69,11 +69,32 @@ db_delete() {
 }
 
 
+check_osname() {
+	local distr=`echo $(lsb_release -i | cut -d':' -f 2)`
+	local osver=`echo $(lsb_release -c | cut -d':' -f 2)`
+	if ! [[ $distr == "Ubuntu" && $osver =~ ^(trusty|xenial|zesty|artful)$ ]]; then
+		echo "${red}" >&2
+		echo "****************************************************************************" >&2
+		echo "****  This OS is not supported by Webinoly and could not work properly  ****" >&2
+		echo "****************************************************************************" >&2
+		echo "${end}" >&2
+	fi
+	echo $osver
+}
+
+
 mysql_client_install() {
-	# Install alternative repos for MariaDB
-	sudo apt-get -y install software-properties-common
-	sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
-	sudo add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirrors.syringanetworks.net/mariadb/repo/10.2/ubuntu xenial main'
+	local osname=$(check_osname)
+	# Cases with MariaDB v10.2 support
+	case "$osname" in
+		"trusty")
+			sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
+		;;
+		"xenial"|"zesty"|"artful")
+			sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
+		;;
+	esac
+	sudo add-apt-repository "deb [arch=amd64,i386,ppc64el] http://mirrors.syringanetworks.net/mariadb/repo/10.2/ubuntu $osname main"
 	sudo apt-get update
 	sudo apt-get -y install mariadb-client
 	conf_write mysql-client true
diff --git a/weby b/weby
--- a/weby
+++ b/weby
@@ -4,6 +4,20 @@
 # This script is designed to install latest Webinoly.
 webyversion="1.1.0-beta"
 
+
+# Check OS support
+distr=`echo $(lsb_release -i | cut -d':' -f 2)`
+osver=`echo $(lsb_release -c | cut -d':' -f 2)`
+if ! [[ $distr == "Ubuntu" && $osver =~ ^(xenial)$ ]]; then
+	echo "$(tput setaf 1)"
+	echo "****************************************************************************"
+	echo "****  This OS is not supported by Webinoly and could not work properly  ****"
+	echo "****************************************************************************"
+	echo "$(tput sgr0)"
+	read -p "Press [Enter] key to continue..."
+fi
+
+
 if [[ -n "$1" ]]; then
 	setup="$1"
 else
@@ -67,7 +81,7 @@ conf_write app-version $webyversion
 
 # Check for missing essential packages
 sudo apt-get -qq update
-sudo apt-get -y -qq install software-properties-common python-software-properties
+sudo apt-get -y -qq install software-properties-common python-software-properties pwgen unzip
 
 
 #  NGINX Installation
