ssl
ssl blocked in forwared sites.

diff --git a/lib/install b/lib/install
--- a/lib/install
+++ b/lib/install
@@ -19,6 +19,10 @@ if [[ $(conf_read db-engine) == "mysql" && $ram -lt 1 ]]; then
 	echo "${red}[ERROR] MySQL is set as database engine!${dim} (Not enough RAM: ${ramb}MB)"
 	echo "You should consider MariaDB instead for small servers under 2GB.${end}"
 	exit 1
+elif [[ $(conf_read db-engine) == "mysql" && $(cpu_arch) == "ARM" ]]; then
+	echo "${red}[ERROR] MySQL is set as database engine!${dim} (ARM processors are not supported by MySQL)${end}"
+	echo "${red}You should consider MariaDB instead for ARM servers.${end}"
+	exit 1
 fi
 
 
