better checks
Forwared sites should not be allowed in parked, redirection manager and protected paths.
Fixed error in parked when main site not exists.

diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -828,6 +828,11 @@ redirection_manager() {
 		fi
 		echo "${gre}Redirection successfully removed!${end}"
 	else
+		if [[ $(is_forward $domain) == "true" ]]; then
+			echo "${red}[ERROR] Forwarded domains are not allowed!${end}"
+			exit 1
+		fi
+		
 		# Default values
 		[[ -z $http_code ]] && http_code="302"
 		[[ $regex == "true" ]] && regex="sensitive"
@@ -1088,8 +1093,8 @@ parked_domain() {
 	if [[ ! -f /etc/nginx/sites-available/$parked ]]; then
 		echo "${red}[ERROR] Main site domain not found! ${end}"
 		exit 1
-	elif ! [[ $(is_html $parked) == "true" || $(is_php $parked) == "true" || $(is_wp $parked) == "true" ]]; then
-		echo "${red}[ERROR] Site type not supported as parked (HTML, PHP and WP)! ${end}"
+	elif [[ $(is_forward $parked) == "true" ]]; then
+		echo "${red}[ERROR] Parked site cannot point to a forwarded site! ${end}"
 		exit 1
 	elif [[ $(is_parked $parked) == "true" ]]; then
 		echo "${red}[ERROR] Parking a site using a parked site as main site is not allowed! ${end}"
diff --git a/plugins/httpauth b/plugins/httpauth
--- a/plugins/httpauth
+++ b/plugins/httpauth
@@ -202,6 +202,11 @@ elif [[ -n $whitelist ]]; then
 
 elif [[ -n $path && -n $domain ]]; then
 	if [[ -z $purge ]]; then
+		if [[ $(is_forward $domain) == "true" ]]; then
+			echo "${red}[ERROR] Forwarded domains are not allowed!${end}"
+			exit 1
+		fi
+		
 		[[ $path == true ]] && read -p "${blu}Path to protect: ${end}" path
 		
 		# Check for reserved paths.
