testing
Small fixes.

diff --git a/lib/site-ssl b/lib/site-ssl
--- a/lib/site-ssl
+++ b/lib/site-ssl
@@ -79,6 +79,9 @@ site_ssl_on() {
 	if [[ -n $manual && $manual != "http" && $manual != "dns" ]]; then
 		echo "${red}[ERROR] Invalid value for manual option!${end}"
 		exit 1
+	elif [[ $(is_forward $domain) == "true" && -z $internal_path ]]; then
+		echo "${red}[ERROR] SSL for forwarded sites are only supported with the 'internal-path' option.${end}"
+		exit 1
 	elif [[ ! -d /var/www/$path/htdocs && -z $root_path && -z $manual && $(is_forward $domain) != "true" && -z $internal_path ]]; then
 		echo "${red}[ERROR] Seems like you are trying to request an SSL Certificate for a Parked/Mapped Domain."
 		echo "Please, use the '-root=domain.com' parameter to specify the main domain."
