better url validation
URL Validation improved in SMTP, Backup,  ExternalDB, Proxy sites and redirection manager.

diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -43,26 +43,6 @@ wp_cache_plugins() {
 	sudo chown -R www-data:www-data /var/www/$domain/htdocs$subfolder/wp-content/plugins
 }
 
-domain_check() {
-	local din="$1"
-	
-	# Only numerals 0-9, basic Latin letters, both lowercase and uppercase, hyphen.
-	[[ $din =~ ^[\.0-9A-Za-z\-]+$ ]] || domfail="true"
-	
-	# Check Lenght
-	[[ ${#din} -gt 67 ]] && domfail="true"
-	
-	# Can not start or end with a hyphen
-	[[ $(echo "${din}" | cut -c-1) == "-" || $(echo "${din}" | rev | cut -c-1) == "-" ]] && domfail="true"
-
-	# Can not contain two points together and can not start or end with a point
-	[[ $din == *..* || $(echo "${din}" | cut -c-1) == "." || $(echo "${din}" | rev | cut -c-1) == "." ]] && domfail="true"
-	
-	# First check if valid TLD
-	[[ $count == 1 ]] && echo "${red}[WARNING] Domain name is not a valid TLD (Top Level Domain).${end}"
-	
-	[[ $domfail == "true" ]] && echo "${red}[WARNING] Domain names can only contain letters, numbers or a hyphen; can not start or end with a hyphen and can be up to 67 characters long.${end}"
-}
 
 dbword_check() {
 	local win="$1"
@@ -168,12 +148,25 @@ wpinstall() {
 			done="1"
 			# Ask DB data or suggest default values
 			echo ""
-			[[ $type == [2345] ]] || read -p "Database Host [localhost]:" dbhost
+			[[ $type == [2345] ]] || read -p "Database Host [localhost]: " dbhost
 			dbhost=${dbhost:-localhost}
 			[[ ${dbhost,,} == "localhost" && $setupmysql == [yY] ]] && check_for_mysql
 			
 			# Check if localhost or external DB
 			if [[ $dbhost != "localhost" && $setupmysql == [yY] ]]; then
+				local dburl=$(echo "$dbhost" | cut -f 1-2 -d ':')
+				local dbport=$(echo "$dbhost" | cut -f 3 -d ':' -s)
+				
+				# Default external DB port
+				[[ -z $dbport && -n $dburl ]] && dbport="3306"
+				
+				# External DB validation
+				if ! [[ $dbport =~ ^[0-9]+$ && $dbport -ge 0 && $dbport -le 65535 && ( $(is_url $dburl) == "true" || $(ip_check $dburl) == "true" ) ]]; then
+					echo "${red}[ERROR] Invalid database host/port!${blu}"
+					done="0"
+					continue 1
+				fi
+				
 				if [[ $(conf_read mysql-client) != "true" ]]; then
 					echo "${gre}MySQL Client is not installed and we need it to stablish a connection with your external server."
 					echo "Wait while we install MySQL Client... installing!!!${end}"
@@ -189,9 +182,6 @@ wpinstall() {
 					local dburoot=${dburoot:-root}
 					local dbproot=${dbproot:-nodefined}
 				fi
-				
-				local dburl=$(echo "$dbhost" | cut -f 1 -d ':')
-				local dbport=$(echo "$dbhost" | cut -f 2 -d ':')
 			fi
 			
 			# ************* Ask for DB Name and validate data *************** #
@@ -499,6 +489,7 @@ db_delete() {
 						[[ $answer = [YyNn] ]] && break
 					done
 					[[ $answer  == [Nn] ]] && done="1"
+					[[ $answer  == [Yy] ]] && wp_dbdata $1
 				else
 					echo "${gre}Database of your site ${blu}${domain}${subfolder}${gre} has been successfully deleted! ${end}"
 				fi
@@ -583,9 +574,15 @@ deletesite() {
 
 createsite() {
 	api-events_update si1
+	
+	# First check if valid TLD
+	[[ $count == 1 ]] && echo "${red}[WARNING] Domain name is not a valid TLD (Top Level Domain).${end}"
+	
 	# Check domain and then prevent reserved characters for file names.
-	domain_check $domain
-	domain=$(echo $domain | sed "s/[^\.0-9A-Za-z\-]/_/g" | sed "s/^[\.]/_/g" | sed "s/\.\./_/g")
+	if [[ $(is_domain $domain) != "true" ]]; then
+		echo "${red}[ERROR] Domain names can only contain letters, numbers or a hyphen; can not start or end with a hyphen or period or having two periods together, and can be up to 67 characters long.${end}"
+		exit 1
+	fi
 	
 	# Check for reserved domain names
 	if [[ $domain == "default" ]]; then
@@ -787,11 +784,11 @@ redirection_manager() {
 		elif ! [[ $http_code =~ ^(301|302|303|307|308|410|444|451)$ ]]; then
 			echo "${red}[ERROR] Invalid redirection HTTP Code!${end}"
 			exit 1
-		elif ! [[ $from =~ ^\/([A-Za-z0-9_\/\.\-]+)?$ ]]; then
-			echo "${red}[ERROR] Please, enter a valid from/to redirection path!${end}"
+		elif [[ $(is_url_path $from) != "true" ]]; then
+			echo "${red}[ERROR] Please, enter a valid 'FROM' redirection path!${end}"
 			exit 1
-		elif [[ -n $to ]] && ! [[ $to =~ ^[A-Za-z0-9_\/\.\-:]+$ ]]; then
-			echo "${red}[ERROR] Please, enter a valid from/to redirection path!${end}"
+		elif [[ -n $to && $(is_url_path $to) != "true" && $(is_url $to) != "true" ]]; then
+			echo "${red}[ERROR] Please, enter a valid 'TO' redirection path!${end}"
 			exit 1
 		fi
 		
@@ -1041,7 +1038,7 @@ reverse_proxy() {
 		fi
 		
 		
-		if ! [[ -n $proxydata && $firstchar == "[" && $lastchar == "]" && -n $rphost ]]; then
+		if ! [[ -n $proxydata && $firstchar == "[" && $lastchar == "]" && -n $rphost && ( $(is_url $rphost) == "true" || $(ip_check $rphost) == "true" || $rphost == "localhost" ) ]]; then
 			echo "${red}[ERROR] Please, enter a valid host and port!${end}"
 			exit 1
 		fi
diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -594,6 +594,9 @@ smtp_setup() {
 	if [[ -z $user || -z $pass || -z $host || -z $mainhost || ! -f /etc/nginx/sites-available/$mainhost ]]; then
 		echo "${red}[ERROR] Invalid SMTP data!${end}"
 		exit 1
+	elif [[ $(is_url $host) != "true" && $(ip_check $host) != "true" ]]; then
+		echo "${red}[ERROR] Invalid SMTP host!${end}"
+		exit 1
 	fi
 	
 	[[ ! -f /opt/webinoly/templates/source/main.cf ]] && sudo cp -p /etc/postfix/main.cf /opt/webinoly/templates/source/
