ssl ask
Now we ask if LE is not installed, instead of error.

diff --git a/lib/site-ssl b/lib/site-ssl
--- a/lib/site-ssl
+++ b/lib/site-ssl
@@ -77,8 +77,19 @@ site_ssl_on() {
 	
 	# Check if Letsencrypt is installed
 	if [[ $(conf_read nginx-tool) != "true" || ! -a /usr/bin/letsencrypt ]]; then
-		echo "${red}[ERROR] Seems like Let's Encrypt tool is not installed!${end}"
-		exit 1
+		echo "${red}Seems like Let's Encrypt tool is not installed!"
+		echo "${blu}Do you want to install it now? [y/N]? ${end}"
+		while read -r -n 1 -s answer; do
+			answer=${answer:-n}
+			echo ""
+			[[ $answer = [YyNn] ]] && break
+		done
+		
+		[[ $answer == [Yy] ]] && sudo stack -nginx=force
+		if [[ $(conf_read nginx-tool) != "true" || ! -a /usr/bin/letsencrypt ]]; then
+			echo "${red}[ERROR] Let's Encrypt is required and not found! ${end}"
+			exit 1
+		fi
 	fi
 
 	echo "${gre}"
