redirection regex
Redirection manager now have support for regex.

diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -757,19 +757,23 @@ redirection_manager() {
 			isred=$( grep -P "^# RedirectFrom: " /etc/nginx/apps.d/$domain-nginx.conf )
 			sudo sed -n '/RedirectFrom/{h;d;}; H; /To:/{x;p;}' /etc/nginx/apps.d/$domain-nginx.conf | sed '/# To:/ s/$/\n/' | sed 's/^# //'
 		fi
-		[[ -z $isred && -z $raw && $list != "raw" ]] && echo "${blu}[Empty] No profiles were found!${end}"
+		[[ -z $isred && -z $raw && $list != "raw" ]] && echo "${blu}[Empty] No redirections were found!${end}"
 	
 		[[ -n $raw || $list == "raw" ]] && echo "" || echo "${end}"
 	elif [[ -n $delete ]]; then
 		echo ""
-		[[ -z $from ]] && read -p "${blu}Redirect 'from path' to delete: ${end}" from
+		[[ -z $from || $from == "true" ]] && read -p "${blu}Redirect 'from path' to delete: ${end}" from
 		if [[ -z $from ]]; then
 			echo "${red}[ERROR] Please, enter a valid 'from' path!${end}"
 			exit 1
 		fi
 		
 		if [[ -f /etc/nginx/apps.d/$domain-nginx.conf ]]; then
-			sudo sed -i "/^# RedirectFrom: $(echo $from | sed "s#/#\\\/#g")/,/^# RedirectEnd/{/.*/d}" /etc/nginx/apps.d/$domain-nginx.conf
+			# SED need escaped characters: Put a backslash before $.*/[\]^
+			local escaped_path=$(echo $from | sed "s#/#\\\/#g" | sed "s/\./\\\./g" | sed "s/\\$/\\\\$/g" | sed "s/\*/\\\*/g" | sed "s/\\\/\\\\/g" | sed "s/\[/\\\[/g" | sed "s/\]/\\\]/g" | sed "s/\^/\\\^/g")
+		
+			sudo sed -i "/^# RedirectFrom: $escaped_path/,/^# RedirectEnd/{/.*/d}" /etc/nginx/apps.d/$domain-nginx.conf
+			
 			if [[ ! -s /etc/nginx/apps.d/$domain-nginx.conf ]]; then
 				sudo rm /etc/nginx/apps.d/$domain-nginx.conf
 				sudo sed -i "/$domain-nginx.conf;/d" /etc/nginx/sites-available/$domain
@@ -777,21 +781,28 @@ redirection_manager() {
 		fi
 		echo "${gre}Redirection successfully removed!${end}"
 	else
-		# Default type
+		# Default values
 		[[ -z $http_code ]] && http_code="302"
+		[[ $regex == "true" ]] && regex="sensitive"
 		
 		echo ""
-		[[ -z $from ]] && read -p "${blu}Redirect from: ${end}" from
-		[[ -z $to ]] && ! [[ $http_code =~ ^(410|444|451)$ ]] && read -p "${blu}Redirect to: ${end}" to
+		[[ -z $from || $from == "true" ]] && read -p "${blu}Redirect from: ${end}" from
+		[[ -z $to || $to == "true" ]] && ! [[ $http_code =~ ^(410|444|451)$ ]] && read -p "${blu}Redirect to: ${end}" to
 		echo ""
 		
 		if [[ -z $from || ( -z $to && $http_code =~ ^(301|302|303|307|308)$ ) ]]; then
 			echo "${red}[ERROR] Please, enter a valid from/to redirection path!${end}"
 			exit 1
+		elif [[ $from == "/" ]]; then
+			echo "${red}[ERROR] Root folder redirection is not allowed, use the 'domain forwarding' feature if want to redirect a complete domain!${end}"
+			exit 1
 		elif ! [[ $http_code =~ ^(301|302|303|307|308|410|444|451)$ ]]; then
 			echo "${red}[ERROR] Invalid redirection HTTP Code!${end}"
 			exit 1
-		elif [[ $(is_url_path $from) != "true" ]]; then
+		elif [[ -n $regex ]] && ! [[ $regex =~ ^(sensitive|insensitive|longest)$ ]]; then
+			echo "${red}[ERROR] Invalid regex value!${end}"
+			exit 1
+		elif [[ -z $regex && $(is_url_path $from) != "true" ]]; then
 			echo "${red}[ERROR] Please, enter a valid 'FROM' redirection path!${end}"
 			exit 1
 		elif [[ -n $to && $(is_url_path $to) != "true" ]] && ! [[ $(is_url $to) =~ ^(http|https)$ ]]; then
@@ -811,6 +822,15 @@ redirection_manager() {
 			if [[ $exact == true ]]; then
 				sign="= "
 				code="$from (Exact)"
+			elif [[ $regex == "sensitive" ]]; then
+				sign="~ "
+				code="$from (Regex)"
+			elif [[ $regex == "insensitive" ]]; then
+				sign="~* "
+				code="$from (Regex)"
+			elif [[ $regex == "longest" ]]; then
+				sign="^~ "
+				code="$from (Regex)"
 			else
 				sign=""
 				code="$from"
@@ -834,6 +854,14 @@ location $sign$from {
 			
 			vconf=$( grep -E "include apps.d/$domain-nginx.conf;" /etc/nginx/sites-available/$domain )
 			[[ -z $vconf ]] && sudo sed -i "/# WebinolyCustom$/a \	include apps.d/$domain-nginx.conf;" /etc/nginx/sites-available/$domain
+			
+			# Last verification
+			if ! sudo nginx -t > /dev/null 2>&1; then
+				sudo site $domain -redirection -from=$from -delete > /dev/null 2>&1
+				echo "${red}[ERROR] Seems like you are using some invalid Nginx values or characters!${end}"
+				exit 1
+			fi
+			
 			echo "${gre}Redirection successfully added!${end}"
 		else
 			echo "${gre}Redirection already exists!${end}"
