multisite convert improved
Improvements

diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -432,6 +432,83 @@ _EOF_
 }
 
 
+db_delete() {
+	local domain="$1"
+	local done="0"
+	
+	wp_dbdata $1
+	[[ -z $wpconfpath ]] && return
+	
+	dbsetup="DELETE FROM mysql.user WHERE User='$wp_dbuser';DROP DATABASE IF EXISTS $wp_dbname;DELETE FROM mysql.db WHERE Db='$wp_dbname' OR Db='$wp_dbname\\_%';FLUSH PRIVILEGES;"
+	while [[ $done != "1" ]]
+	do
+		done="1"
+		if [[ $wp_dbhost == "localhost" ]]; then
+			# Check if MySQL installed
+			if [[ ! -d /etc/mysql || $(conf_read mysql) != "true" || $(conf_read mysql-client) != "true" ]]; then
+				echo "${red}[ERROR] Seems like MySQL is not installed or Webinoly can not detect it!"
+				echo " - Database can not be deleted -${blu} $domain ${end}"
+				return
+			fi
+			local ROOT_PASS=$( echo $(conf_read mysql-root) | openssl enc -d -a -salt )
+			sudo mysql --connect-timeout=10 --user=root -p$ROOT_PASS -e "$dbsetup"
+			if [ $? != "0" ]; then
+				done="0"
+				echo "${red}============================================"
+				echo "    [Error]: Database delete failed."
+				echo "============================================"
+				echo ""
+				echo "${blu}  Retry [Y/n]? "
+				while read -r -n 1 -s answer; do
+					answer=${answer:-y}
+					[[ $answer = [YyNn] ]] && break
+				done
+				[[ $answer  == [Nn] ]] && done="1"
+			else
+				echo "${gre}Database of your site ${blu}${domain}${subfolder}${gre} has been successfully deleted! ${end}"
+			fi
+		else
+			if [[ -z $wp_uroot || -z $wp_proot ]]; then
+				echo ""
+				echo "${gre}External DB found in${blu} $domain ${gre}(Press 'Enter' key twice to skip and not delete)"
+				read -p "${blu}External DB root username [root]: " wp_uroot
+				wp_uroot=${wp_uroot:-root}
+				read -p "External DB root password: " wp_proot
+			fi
+			if [[ $wp_uroot == "root" && -z $wp_proot ]]; then
+				echo "${red}Action aborted, database not deleted!"
+				continue 1;
+			else
+				if [[ $(conf_read mysql-client) != "true" ]]; then
+					echo "${gre}MySQL Client is not installed and we need it to stablish a connection with your Database."
+					echo "Wait while we install MySQL Client... installing!!!${end}"
+					mysql_client_install > /dev/null 2>&1 &
+					echo "${gre}MySQL Client has been successfully installed!${end}"
+				fi
+				
+				sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" -e "$dbsetup"
+				if [ $? != "0" ]; then
+					done="0"
+					echo "${red}============================================"
+					echo "    [Error]: Database delete failed."
+					echo "============================================"
+					echo ""
+					echo "${blu}  Retry [Y/n]? "
+					while read -r -n 1 -s answer; do
+						answer=${answer:-y}
+						[[ $answer = [YyNn] ]] && break
+					done
+					[[ $answer  == [Nn] ]] && done="1"
+				else
+					echo "${gre}Database of your site ${blu}${domain}${subfolder}${gre} has been successfully deleted! ${end}"
+				fi
+			fi
+			echo "${end}"
+		fi
+	done
+	
+}
+
 
 deletesite() {
 	if [[ $domain == $(conf_read tools-site) || $domain == $(conf_read default-site) ]]; then
diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -2,7 +2,7 @@
 
 # Site Manager Plugin (Create, delete and de/activate)
 # Syntax: site <domain> <option> <argument>
-# Options: -html, -php, -mysql, -wp, -wpsubdir, -wpsubdom, -parked, -proxy, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap
+# Options: -html, -php, -mysql, -wp, -wpsubdir, -wpsubdom, -parked, -proxy, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap, -multisite-convert
 # Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder
 
 # shopt is necessary for this kind !(html|22222) of patterns
@@ -261,6 +261,8 @@ elif [[ -n $wp && -n $domain ]]; then
 		sudo sed -i "s#subfolder#$subfolder#g" /etc/nginx/apps.d/$domain$subname-locations.conf
 		sudo sed -i "s#subfolder#$subfolder#g" /etc/nginx/apps.d/$domain$subname-wpcommon.conf
 		sudo sed -i "s#subfolder#$subfolder#g" /etc/nginx/apps.d/$domain$subname-wpcommon-noauth.conf
+		
+		[[ $(conf_read yoast-sitemap) != "purged" ]] && sudo site $domain -yoast-sitemap=on -subfolder=$subfolder
 	fi
 
 
@@ -269,7 +271,7 @@ elif [[ -n $multisite_convert && -a /etc/nginx/sites-available/$domain ]]; then
 	if [[ ( -z $subfolder && $(is_wp $domain) == "false" ) || ( -n $subfolder && $(is_wp $domain $subfolder) == "false" ) ]]; then
 		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is not a WP site!${end}"
 		exit 1
-	elif [[ $(is_wp_multisite $domain) == "true" ]]; then		
+	elif [[ $(is_wp_multisite $domain) =~ ^(subdomain|subdirectory)$ ]]; then		
 		echo "${red}[ERROR] Site${blu} $domain$subfolder ${red}is already in multisite configuration!${end}"
 		exit 1
 	fi
@@ -285,40 +287,45 @@ elif [[ -n $multisite_convert && -a /etc/nginx/sites-available/$domain ]]; then
 	echo "After that, you don't need to add any code lines."
 	echo "We will do it for you!"
 	echo ""
-	echo "Just press ${end}<Enter>${blu} when you are ready or press ${end}'X'${blu} to Cancel!"
+	echo "${gre}Waiting... we will automatically finish the multisite configuration after you do the install in the WP dashboard!${blu}"
+	echo "Write ${end}'quit'${blu} and press ${end}<Enter>${blu} to exit and abort this operation."
 	echo "${end}"
-	while read -r -n 1 -s answer; do
-		answer=${answer:-y}
-		[[ $answer = [YyXx] ]] && break
+	
+	while [[ -z $passed || $passed == "false" ]]; do
+		if read -t0; then
+			read pas
+			[[ $pas == "quit" ]] && break
+		fi
+		sleep 2
+		passed=$(is_wp_multisite $domain)
 	done
 	
-	passed=$(is_wp_multisite $domain)
-	if [[ $passed != "true" && $answer == [Xx] ]]; then
+	if [[ $passed == "false" && $pas == "quit" ]]; then
 		sudo sed -i "/WP_ALLOW_MULTISITE/d" $wpcon
 		echo "${red}[ERROR] Action aborted!${end}"
 		exit 1
-	elif [[ $passed != "true" && $answer != [Xx] ]]; then
-		sudo sed -i "/WP_ALLOW_MULTISITE/d" $wpcon
-		echo "${red}[ERROR] Multisite installation incomplete or not detected!${end}"
-		exit 1
-	elif [[ $passed == "true" ]]; then
+	elif [[ $passed =~ ^(subdomain|subdirectory)$ ]]; then
 		# Multisite wp-config
-		sudo sed -i "/stop editing/i \#define('MULTISITE', true);" $wpcon
-		sudo sed -i "/stop editing/i \#define('DOMAIN_CURRENT_SITE', '$domain');" $wpcon
-		sudo sed -i "/stop editing/i \#define('PATH_CURRENT_SITE', '/');" $wpcon
-		sudo sed -i "/stop editing/i \#define('SITE_ID_CURRENT_SITE', 1);" $wpcon
-		sudo sed -i "/stop editing/i \#define('BLOG_ID_CURRENT_SITE', 1);" $wpcon
+		sudo sed -i "/stop editing/i \define('MULTISITE', true);" $wpcon
+		sudo sed -i "/stop editing/i \define('DOMAIN_CURRENT_SITE', '$domain');" $wpcon
+		sudo sed -i "/stop editing/i \define('PATH_CURRENT_SITE', '/');" $wpcon
+		sudo sed -i "/stop editing/i \define('SITE_ID_CURRENT_SITE', 1);" $wpcon
+		sudo sed -i "/stop editing/i \define('BLOG_ID_CURRENT_SITE', 1);" $wpcon
 		
-		[[ $answer == [Xx] ]] && echo "${red}Can not cancel because the installation was already done!${end}"
+		[[ $pas == "quit" ]] && echo "${red}Can not cancel because the installation was already done!${end}"
 		
-		if [[ $(is_wp_multisite_subdomain $domain) == "true" ]]; then
+		if [[ $passed == "subdomain" ]]; then
 			sudo sed -i "/stop editing/i \#define('SUBDOMAIN_INSTALL', true);" $wpcon
 			sudo sed -i "/server_name /c \	server_name $domain *.$domain;" /etc/nginx/sites-available/$domain
 			echo "${gre}Subdomain Multisite configuration has been successfully completed!${end}"
-		else
+		elif [[ $passed == "subdirectory" ]]; then
 			sudo sed -i "/stop editing/i \#define('SUBDOMAIN_INSTALL', false);" $wpcon			
 			sudo sed -i '/locations.conf/i \	include common/wpsubdir.conf;' /etc/nginx/sites-available/$domain
 			echo "${gre}Subdirectory Multisite configuration has been successfully completed!${end}"
+		else
+			sudo sed -i "/WP_ALLOW_MULTISITE/d" $wpcon
+			echo "${red}[ERROR] Multisite installation incomplete or not detected!${end}"
+			exit 1
 		fi
 	fi
 
