better check for apps.d
Now we have better check to avoid conflict with blocks in Nginx apps.d, specially with redirections and protected paths.

diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -790,7 +790,10 @@ redirection_manager() {
 		[[ -z $to || $to == "true" ]] && ! [[ $http_code =~ ^(410|444|451)$ ]] && read -p "${blu}Redirect to: ${end}" to
 		echo ""
 		
-		if [[ -z $from || ( -z $to && $http_code =~ ^(301|302|303|307|308)$ ) ]]; then
+		if [[ -n $( grep -E "^# Path: ${from}( \([Exact]+\))?$" /etc/nginx/apps.d/$domain-nginx.conf ) ]]; then
+			echo "${red}[ERROR] Protected paths are not allowed for redirections!${end}"
+			exit 1
+		elif [[ -z $from || ( -z $to && $http_code =~ ^(301|302|303|307|308)$ ) ]]; then
 			echo "${red}[ERROR] Please, enter a valid from/to redirection path!${end}"
 			exit 1
 		elif [[ $from == "/" ]]; then
@@ -817,12 +820,11 @@ redirection_manager() {
 			sudo chown -R root:root /etc/nginx/apps.d/$domain-nginx.conf
 		fi
 		
-		exist=$( grep -E "^# RedirectFrom: ${from}$" /etc/nginx/apps.d/$domain-nginx.conf )
-		if [[ -z $exist ]]; then
-			if [[ $exact == true ]]; then
-				sign="= "
-				code="$from (Exact)"
-			elif [[ $regex == "sensitive" ]]; then
+		local exist=$( grep -E "^# RedirectFrom: ${from}( \([Regx]+\))?$" /etc/nginx/apps.d/$domain-nginx.conf )
+		local exists=$( grep -E "^# RedirectFrom: ${from}( \(Exact\))$" /etc/nginx/apps.d/$domain-nginx.conf )
+		# Can have both at the same time, one exact and another.
+		if [[ ( -z $exists && $exact == "true" ) || ( -z $exists && -z $exist ) || ( -n $exists && -z $exist && -z $exact ) ]]; then
+			if [[ $regex == "sensitive" ]]; then
 				sign="~ "
 				code="$from (Regex)"
 			elif [[ $regex == "insensitive" ]]; then
@@ -831,6 +833,9 @@ redirection_manager() {
 			elif [[ $regex == "longest" ]]; then
 				sign="^~ "
 				code="$from (Regex)"
+			elif [[ $exact == true ]]; then
+				sign="= "
+				code="$from (Exact)"
 			else
 				sign=""
 				code="$from"
diff --git a/plugins/httpauth b/plugins/httpauth
--- a/plugins/httpauth
+++ b/plugins/httpauth
@@ -216,6 +216,11 @@ elif [[ -n $path && -n $domain ]]; then
 			echo "${red}[ERROR] HTTP Authentication is not allowed in subfolders (only root '/' is allowed) for Reverse Proxy sites!${end}"
 			exit 1
 		elif [[ $path =~ ^\/([A-Za-z0-9_\/\.\-]+)?$ ]]; then
+			if [[ -n $( grep -E "^# RedirectFrom: ${path}( \([RegxEact]+\))?$" /etc/nginx/apps.d/$domain-nginx.conf ) ]]; then
+				echo "${red}[ERROR] A redirection was found for this path, you better should protect the final destination!${end}"
+				exit 1
+			fi
+			
 			if [[ ! -f /etc/nginx/apps.d/$domain-nginx.conf ]]; then
 				sudo touch /etc/nginx/apps.d/$domain-nginx.conf
 				sudo chmod 644 /etc/nginx/apps.d/$domain-nginx.conf
@@ -246,6 +251,14 @@ location $sign$path {
 				
 				vconf=$( grep -E "include apps.d/$domain-nginx.conf;" /etc/nginx/sites-available/$domain )
 				[[ -z $vconf ]] && sudo sed -i "/# WebinolyCustom$/a \	include apps.d/$domain-nginx.conf;" /etc/nginx/sites-available/$domain
+				
+				# Last verification
+				if ! sudo nginx -t > /dev/null 2>&1; then
+					sudo httpauth $domain -path=$path -purge > /dev/null 2>&1
+					echo "${red}[ERROR] Seems like you are using some invalid Nginx values or characters!${end}"
+					exit 1
+				fi
+				
 				echo "${gre}This path ${blu}'$path'${gre} was successfully protected!${end}"
 			else
 				echo "${gre}Path: ${blu}'$path'${gre} is already protected!${end}"
