wp env
WordPress environment type support.

diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -1216,6 +1216,11 @@ yoast_sitemap() {
 
 
 clone_wp_site() {
+	if [[ -f /etc/nginx/sites-available/$domain && $overwrite == "on" ]]; then
+		echo "${blu}Site already exists! ${dim} Overwriting...${end}"
+		[[ -z $subfolder ]] && sudo site $domain -delete=force > /dev/null 2>&1 || sudo site $domain -subfolder=$subfolder -delete=force > /dev/null 2>&1
+	fi
+	
 	if [[ -n $subfolder ]]; then
 		local wpcon="/var/www/$domain/htdocs$subfolder/wp-config.php"
 		
@@ -1223,7 +1228,6 @@ clone_wp_site() {
 		sudo cp /etc/nginx/apps.d/$clone_from$subname-wpfc.conf /etc/nginx/apps.d/$domain$subname-wpfc.conf
 		sudo cp /etc/nginx/apps.d/$clone_from$subname-wpcommon.conf /etc/nginx/apps.d/$domain$subname-wpcommon.conf
 		sudo cp /etc/nginx/apps.d/$clone_from$subname-wpcommon-noauth.conf /etc/nginx/apps.d/$domain$subname-wpcommon-noauth.conf
-		sudo cp /etc/nginx/apps.d/$clone_from$subname-locations.conf /etc/nginx/apps.d/$domain$subname-locations.conf
 		sudo cp /etc/nginx/apps.d/$clone_from$subname-yoast-sitemap.conf /etc/nginx/apps.d/$domain$subname-yoast-sitemap.conf
 		
 		sudo sed -i "s/$clone_from/$domain/g" /etc/nginx/apps.d/$domain$subname-php.conf
@@ -1283,7 +1287,9 @@ clone_wp_site() {
 		replace_content="[https://www.$clone_from,https://$domain]" && wp_replace_content > /dev/null 2>&1
 	fi
 	
-	echo "${gre}Site ${blu}'$domain$subfolder'${gre} is now a successfull clone of ${blu}'$clone_from$subfolder'${end}"
+	echo "${gre}Site${blu} $domain$subfolder ${gre}is now a successfull clone of${blu} $clone_from$subfolder ${end}"
+	[[ -n $env && -z $subfolder ]] && sudo site $domain -env=$env
+	[[ -n $env && -n $subfolder ]] && sudo site $domain -env=$env -subfolder=$subfolder
 }
 
 
@@ -1436,5 +1442,70 @@ site_info() {
 		echo "${blu}Forwarded to:${end} $(grep "return 301 " /etc/nginx/sites-available/$domain | cut -d " " -f 3 -s | cut -d "$" -f 1 -s)"
 	fi
 	echo ""
+}
+
+
+wp_env_type() {
+	if [[ $(is_wp $domain $subfolder) != "true" ]]; then
+		echo "${red}[ERROR] Site${blu} $domain ${red}is not a WordPress site!${end}"
+		exit 1
+	elif ! [[ $env =~ ^(production|staging|development|local)$ ]]; then
+		echo "${red}[ERROR] Invalid value for WP environment type!${end}"
+		exit 1
+	fi
+	
+	[[ -z $subfolder ]] && local wpath="/var/www/$domain/wp-config.php" || local wpath="/var/www/$domain/htdocs$subfolder/wp-config.php"
+	[[ -n $( grep -F "'WP_ENVIRONMENT_TYPE'" $wpath ) ]] && sudo sed -i "/'WP_ENVIRONMENT_TYPE'/d" $wpath
+	
+	if [[ $env == "production" ]]; then
+		local index="1"
+		[[ -n $cache ]] && wp_cache
+	else
+		local index="0"
+		sudo sed -i "/stop editing/i \define('WP_ENVIRONMENT_TYPE', '$env');" $wpath
+		if [[ -n $cache ]]; then
+			wp_cache
+		elif [[ $(is_wp_cache $domain $subfolder) == "true" ]]; then
+			cache="off"
+			wp_cache
+		fi
+	fi
+	
+	# Not change WP debug when invoked from LOG command
+	if [[ -z $skip_debug ]]; then
+		if [[ $env =~ ^(production|staging)$ && $(is_wp_debug $domain $subfolder) == "true" ]]; then
+			[[ -z $subfolder ]] && log $domain -wp=off || log $domain -wp=off -subfolder=$subfolder
+		elif [[ $env =~ ^(development|local)$ && $(is_wp_debug $domain $subfolder) != "true" ]]; then
+			[[ -z $subfolder ]] && log $domain -wp=on || log $domain -wp=on -subfolder=$subfolder
+		fi
+	fi
+	
+	# WordPress Reading Settings: Discourage Search Engines
+	wp_dbdata $domain
+	
+	if [[ $(is_wp_installed $domain) == "true" ]]; then
+		if [[ $wp_dbhost == "localhost" && $(check_mysql_connection localhost) == "true" ]]; then
+			sudo mysql --connect-timeout=10 --user=admin -p$ADMIN_PASS <<_EOF_
+USE $wp_dbname;
+UPDATE ${wp_dbpref}options SET option_value='$index' WHERE option_name='blog_public';
+FLUSH PRIVILEGES;
+_EOF_
+		
+		elif [[ $(check_mysql_connection $wp_dburl $wp_dbport $wp_uroot $wp_proot) == "true" ]]; then
+			sudo mysql --connect-timeout=10 -h "$wp_dburl" -P "$wp_dbport" -u"$wp_uroot" -p"$wp_proot" <<_EOF_
+USE $wp_dbname;
+UPDATE ${wp_dbpref}options SET option_value='$index' WHERE option_name='blog_public';
+FLUSH PRIVILEGES;
+_EOF_
+		
+		else
+			local index=""
+		fi
+		
+		[[ $index == "0" ]] && echo "${gre}Discourage Search Engines WP option has been enabled for${blu} $domain$subfolder ${gre}site!${end}"
+		[[ $index == "1" ]] && echo "${gre}Discourage Search Engines WP option has been disabled for${blu} $domain$subfolder ${gre}site!${end}"
+	fi
+	
+	echo "${gre}WordPress Environment Type has been set successfully!${end}"
 }
 
diff --git a/plugins/site b/plugins/site
--- a/plugins/site
+++ b/plugins/site
@@ -2,8 +2,8 @@
 
 # Site Manager Plugin (Create, delete and de/activate)
 # Syntax: site <domain> <option> <argument>
-# Options: -html, -php, -mysql, -wp, -parked, -proxy, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap, -multisite-convert, -clone-from, -replace-content, -redirection, -forward, -info
-# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex, -manual
+# Options: -html, -php, -mysql, -wp, -parked, -proxy, -on, -off, -delete, -delete-all, -list, -cache, -ssl, -force-redirect, -yoast-sitemap, -multisite-convert, -clone-from, -replace-content, -redirection, -forward, -info, -env
+# Arguments: -cache, -root, -root-path, -subdomain, -ignore-ssl, -wildcard, -raw, -external-db, -revoke, -ssl-crt, -ssl-key, -ssl-ocsp, -subfolder, -from, -to, -http-code, -regex, -manual, -overwrite
 
 # shopt is necessary for this kind !(html|22222) of patterns
 shopt -s extglob
@@ -84,13 +84,16 @@ fi
 if [[ -n $subfolder && ! ( $subfolder =~ ^\/([A-Za-z0-9_\/\-]+)?[^\/]$ ) ]]; then
 	echo "${red}[ERROR] Please, enter a valid value for subfolder!${end}"
 	exit 1
-elif [[ -n $subfolder && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content && -z $wp && -z $html && -z $php && -z $mysql && -z $proxy ]]; then
+elif [[ -n $subfolder && -z $delete && -z $cache && -z $yoast_sitemap && -z $multisite_convert && -z $clone_from && -z $replace_content && -z $wp && -z $html && -z $php && -z $mysql && -z $proxy && -z $env ]]; then
 	echo "${red}[ERROR] Subfolder option not supported!${end}"
 	exit 1
 elif [[ -n $subfolder && ( -n $cache || -n $yoast_sitemap || -n $multisite_convert || -n $replace_content ) && ! -d /var/www/$domain/htdocs$subfolder ]]; then
 	echo "${red}[ERROR] Subfolder not found!${end}"
 	exit 1
 elif [[ -n $subfolder && -n $clone_from && ! -d /var/www/$clone_from/htdocs$subfolder ]]; then
+	echo "${red}[ERROR] Subfolder not found!${end}"
+	exit 1
+elif [[ -n $subfolder && -z $clone_from && -n $env && ! -d /var/www/$domain/htdocs$subfolder ]]; then
 	echo "${red}[ERROR] Subfolder not found!${end}"
 	exit 1
 else
@@ -171,6 +174,7 @@ elif [[ -n $wp && -n $domain ]]; then
 		sudo sed -i '/locations.conf/i \	include common/wpcommon.conf;' /etc/nginx/sites-available/$domain
 		[[ $(conf_read wp-admin-auth) == "purged" ]] && sudo httpauth $domain -wp-admin=off > /dev/null 2>&1
 		[[ $(conf_read yoast-sitemap) == "true" ]] && sudo site $domain -yoast-sitemap=on > /dev/null 2>&1
+		[[ -n $env ]] && sudo site $domain -env=$env
 	else
 		if [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && $type == [123] && $(is_subfolder $domain $subfolder) != "false" ]]; then
 			echo "${red}[ERROR] Subfolder${blu} $subfolder ${red}already exists!${end}"
@@ -182,6 +186,7 @@ elif [[ -n $wp && -n $domain ]]; then
 		fi
 		
 		wp_subfolder
+		[[ -n $env ]] && sudo site $domain -env=$env -subfolder=$subfolder
 	fi
 
 
@@ -329,10 +334,6 @@ elif [[ -n $ssl ]]; then
 		exit 1
 	fi
 
-# FastCGI Cache
-elif [[ -n $cache ]]; then
-	wp_cache
-
 
 # Force www or non-www redirect (www, root, off)
 elif [[ -n $force_redirect && -f /etc/nginx/sites-available/$domain ]]; then
@@ -349,10 +350,10 @@ elif [[ -n $clone_from ]]; then
 	if [[ ! -f /etc/nginx/sites-available/$clone_from ]]; then
 		echo "${red}[ERROR] Site/domain ${blu}'$clone_from'${red} not found!${end}"
 		exit 1
-	elif [[ -f /etc/nginx/sites-available/$domain && -z $subfolder ]]; then
+	elif [[ -f /etc/nginx/sites-available/$domain && -z $subfolder && $overwrite != "on" ]]; then
 		echo "${red}[ERROR] Can not create site${blu} $domain ${red}because already exists!${end}"
 		exit 1
-	elif [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && -d /var/www/$domain/htdocs$subfolder ]]; then
+	elif [[ -f /etc/nginx/sites-available/$domain && -n $subfolder && -d /var/www/$domain/htdocs$subfolder && $overwrite != "on" ]]; then
 		echo "${red}[ERROR] Subfolder ${blu}'$subfolder'${red} already exists!${end}"
 		exit 1
 	elif [[ $(is_wp $clone_from $subfolder) != "true" ]]; then
@@ -385,6 +386,17 @@ elif [[ -n $replace_content && -f /etc/nginx/sites-available/$domain ]]; then
 		wp_replace_content
 	fi
 
+
+# WordPress Environment Type
+elif [[ -n $env && -f /etc/nginx/sites-available/$domain ]]; then
+	wp_env_type
+	nginx_not="true" # Nginx-Reload not-needed.
+	
+
+# FastCGI Cache
+elif [[ -n $cache ]]; then
+	wp_cache
+	
 
 # List Sites
 elif [[ -n $list && -z $redirection ]]; then
