external db
Fixed some issues with DB creation when external db credentials are saved.
Fixed infinite loop in WP site creation when db connection fails.
Fixed error when trying to delete a WP site and db conection fails.

diff --git a/lib/sites b/lib/sites
--- a/lib/sites
+++ b/lib/sites
@@ -213,12 +213,19 @@ wpinstall() {
 			fi
 			
 			# Check for MySQL Connection
-			if [[ ( $dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $dbhost != "localhost" && $(check_mysql_connection $dburl $dbport $dburoot $dbproot) != "true" ) ]]; then
+			if [[ -n $retry && $retry -ge 3 ]]; then
+				setupmysql="N"
+				echo "${red}[ERROR] Database creation failed after 3 retries! ${blu}"
+			elif [[ ( $dbhost == "localhost" && $(check_mysql_connection localhost) != "true" ) || ( $dbhost != "localhost" && $(check_mysql_connection $dburl $dbport $dburoot $dbproot) != "true" ) ]]; then
 				# Reset variables
 				local dburl=""
 				local dbport=""
 				local dburoot=""
 				local dbproot=""
+				
+				# Prevent infinite loops, just 3 intents!
+				[[ -z $retry ]] && local retry=0
+				local retry=$(($retry+1))
 				
 				# While loop
 				done="0"
diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -1351,6 +1351,11 @@ database_import() {
 	
 	if [[ -n $external_db ]]; then
 		external_db_parse
+		if [[ $(check_mysql_connection $extdb_url $extdb_port $extdb_user $extdb_pass) != "true" ]]; then
+			echo "${red}[ERROR] Cannot connect with your External Database!${end}"
+			exit 1
+		fi
+		
 		echo "${dim}Wait while we import your db... ${end}"
 		sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" < $file
 		sudo mysql --connect-timeout=10 -h "$extdb_url" -P "$extdb_port" -u"$extdb_user" -p"$extdb_pass" -e "FLUSH PRIVILEGES;"
