verify
Better checks!

diff --git a/lib/verify b/lib/verify
--- a/lib/verify
+++ b/lib/verify
@@ -358,6 +358,11 @@ if [[ $(conf_read nginx) == "true" ]]; then
 fi
 
 # NGINX Optim
+if [[ $(conf_read nginx) == "true" && $(conf_read nginx-optim) != "true" ]]; then
+	echo "- [ERROR] Nginx is installed but not optimized by Webinoly!"
+	local ver_two_err="1"
+fi
+
 if [[ $(conf_read nginx-optim) == "true" ]]; then
 	if [[ ! -f /etc/nginx/fastcgi_params ]]; then
 		echo "- [ERROR] File: /etc/nginx/fastcgi_params not found!"
@@ -496,9 +501,6 @@ if [[ -z $critical_mode ]]; then
 	fi
 
 	# Check for Tools and Default site.
-	if [[ $(conf_read default-site) != "blackhole" ]]; then
-		echo "${blu}${dim}- [INFO] Setting the Nginx default site/response to 'blackhole' is highly recommended!${end}${red}"
-	fi
 	if [[ -n $(conf_read default-site) && ! ( $(conf_read default-site) =~ ^(default|blackhole)$ ) && ! -L /etc/nginx/sites-enabled/$(conf_read default-site) ]]; then
 		echo "${dim}- [WARNING] Default site is set but not found or is not enabled!${end}${red}"
 		local ver_two_war="1"
@@ -518,13 +520,6 @@ if [[ -z $critical_mode ]]; then
 		echo "${blu}${dim}- [INFO] HTTP Authentication Credentials not found to access the server tools on port $(conf_read tools-port).${end}${red}"
 	fi
 	
-	# HTTP Headers
-	if [[ $(conf_read nginx-optim) == "true" && -z $(conf_read header-csp) ]]; then
-		echo "${blu}${dim}- [INFO] Setting a Content-Security-Policy Header is highly recommended!${end}${red}"
-	fi
-	if [[ $(conf_read nginx-optim) == "true" && $(conf_read header-xssp) == "true" ]]; then
-		echo "${blu}${dim}- [INFO] X-XSS Header is no longer recommended, use a strong CSP instead!${end}${red}"
-	fi
 
 	if [[ $(conf_read nginx) == "true" ]]; then
 		# Webinoly Stack version
@@ -540,6 +535,22 @@ if [[ -z $critical_mode ]]; then
 		elif [[ $(($(sudo nginx -v 2>&1 | cut -d'.' -f 2 -s)%2)) == 0 && $(conf_read nginx-ppa) != "stable" && -n $(conf_read nginx-ppa) ]]; then
 			echo "- [ERROR] Nginx Branch in Configuration File is corrupted!"
 			local ver_two_err="1"
+		fi
+		
+		# Blackhole is always a good idea!
+		if [[ $(conf_read default-site) != "blackhole" ]]; then
+			echo "${blu}${dim}- [INFO] Setting the Nginx default site/response to 'blackhole' is highly recommended!${end}${red}"
+		fi
+		
+		# HTTP Headers
+		if [[ -z $(conf_read header-csp) ]]; then
+			echo "${blu}${dim}- [INFO] Setting a Content-Security-Policy Header is highly recommended!${end}${red}"
+		fi
+		if [[ $(conf_read header-xssp) == "true" ]]; then
+			echo "${blu}${dim}- [INFO] X-XSS Header is no longer recommended, use a strong CSP instead!${end}${red}"
+		fi
+		if [[ -n $(conf_read header-xfo) && $(conf_read header-xfo) != "sameorigin" && $(conf_read header-xfo) != "off" ]]; then
+			echo "${blu}${dim}- [INFO] X-XSS Header is no longer recommended, use a strong CSP instead!${end}${red}"
 		fi
 	fi
 
@@ -596,6 +607,11 @@ if [[ $(conf_read php) == "true" ]]; then
 fi
 
 # PHP Optim
+if [[ $(conf_read php) == "true" && $(conf_read php-optim) != "true" ]]; then
+	echo "- [ERROR] PHP is installed but not optimized by Webinoly!"
+	local ver_three_err="1"
+fi
+
 if [[ $(conf_read php-optim) == "true" ]]; then
 	if [[ ! -f /etc/php/$(conf_read php-ver)/fpm/php-fpm.conf ]]; then
 		echo "- [ERROR] File: /etc/php/$(conf_read php-ver)/fpm/php-fpm.conf not found!"
@@ -673,8 +689,8 @@ if [[ -z $critical_mode ]]; then
 		elif [[ $ver_php_ver =~ ^(5.6|7.0|7.1|7.2|7.3|7.4|8.0)$ ]]; then
 			echo "${dim}- [WARNING] You have an obsolete PHP version installed (${ver_php_ver}) that not even receive security updates!${end}${red}"
 			local ver_three_war="1"
-		#elif [[ $ver_php_ver == "8.1" ]]; then
-		#	echo "${blu}${dim}- [INFO] PHP v8.2 or later is recommended to get an optimal perfomance! (Current: ${ver_php_ver}) ${end}${red}"
+		elif [[ $ver_php_ver == "8.1" ]]; then
+			echo "${blu}${dim}- [INFO] PHP v8.2 or later is recommended to get an optimal perfomance! (Current: ${ver_php_ver}) ${end}${red}"
 		fi
 		
 		# Security check...
@@ -788,6 +804,13 @@ if [[ $(conf_read mysql) == "true" ]]; then
 	fi
 fi
 
+# MySQL Optim
+if [[ $(conf_read mysql) == "true" && $(conf_read mysql-optim) != "true" ]]; then
+	echo "- [ERROR] MySQL/MariaDB is installed but not optimized by Webinoly!"
+	local ver_four_err="1"
+fi
+
+
 if [[ -z $critical_mode ]]; then
 	# MySQL RAM requirements!
 	if [[ $(conf_read db-engine) == "mysql" && $ram -lt 2 ]]; then
@@ -802,15 +825,26 @@ if [[ -z $critical_mode ]]; then
 			local ver_four_war="1"
 		fi
 		
-		# MySQL and MariaDB can be mixed, don't worry!
-		if ! [[ $ver_mysql_ver =~ ^(8.0|8.4|10.0|10.1|10.2|10.3|10.4|10.5|10.6|10.11|11.4)$ ]]; then
-			echo "${dim}- [WARNING] Unknown MySQL/MariaDB version! (${ver_mysql_ver}) ${end}${red}"
-			local ver_four_war="1"
-		elif [[ $ver_mysql_ver =~ ^(10.0|10.1|10.2|10.3|10.4)$ ]]; then
-			echo "${dim}- [WARNING] You have an obsolete MariaDB version (${ver_mysql_ver}) installed that not even receive security updates!${end}${red}"
-			local ver_four_war="1"
-		elif [[ $ver_mysql_ver =~ ^(10.5)$ ]]; then
-			echo "${blu}${dim}- [INFO] MariaDB v10.6 or later is recommended to get an optimal perfomance! (Current: ${ver_mysql_ver}) ${end}${red}"
+		if [[ $(conf_read db-engine) == "mysql" ]]; then
+			if ! [[ $ver_mysql_ver =~ ^(8.0|8.4)$ ]]; then
+				echo "${dim}- [WARNING] Unknown MySQL version! (${ver_mysql_ver}) ${end}${red}"
+				local ver_four_war="1"
+			#elif [[ $ver_mysql_ver =~ ^(8.0)$ ]]; then
+			#	echo "${dim}- [WARNING] You have an obsolete MySQL version (${ver_mysql_ver}) installed that not even receive security updates!${end}${red}"
+			#	local ver_four_war="1"
+			elif [[ $ver_mysql_ver =~ ^(8.0)$ ]]; then
+				echo "${blu}${dim}- [INFO] MySQL v8.4 is recommended to get an optimal perfomance! (Current: ${ver_mysql_ver}) ${end}${red}"
+			fi
+		else
+			if ! [[ $ver_mysql_ver =~ ^(10.0|10.1|10.2|10.3|10.4|10.5|10.6|10.11|11.4)$ ]]; then
+				echo "${dim}- [WARNING] Unknown MariaDB version! (${ver_mysql_ver}) ${end}${red}"
+				local ver_four_war="1"
+			elif [[ $ver_mysql_ver =~ ^(10.0|10.1|10.2|10.3|10.4)$ ]]; then
+				echo "${dim}- [WARNING] You have an obsolete MariaDB version (${ver_mysql_ver}) installed that not even receive security updates!${end}${red}"
+				local ver_four_war="1"
+			elif [[ $ver_mysql_ver =~ ^(10.5)$ ]]; then
+				echo "${blu}${dim}- [INFO] MariaDB v10.6 or later is recommended to get an optimal perfomance! (Current: ${ver_mysql_ver}) ${end}${red}"
+			fi
 		fi
 	fi
 
@@ -883,6 +917,18 @@ fi
 if [[ $(conf_read php) == "true" ]] && ! systemctl is-active --quiet php$(conf_read php-ver)-fpm; then
 	echo "- [ERROR] PHP service not running!"
 	local ver_five_err="1"
+elif [[ $(conf_read php) == "true" ]]; then
+	# Webinoly PHP Conf depends on these native route of symlinks!
+	if [[ ! -L /run/php/php-fpm.sock ]]; then
+		echo "- [ERROR] PHP Socket route/symlink is broken or not found! (/run/php/php-fpm.sock)"
+		local ver_five_err="1"
+	elif [[ ! -L /etc/alternatives/php-fpm.sock ]]; then
+		echo "- [ERROR] PHP Socket route/symlink is broken or not found! (/etc/alternatives/php-fpm.sock)"
+		local ver_five_err="1"
+	elif [[ ! -S /run/php/php$(conf_read php-ver)-fpm.sock ]]; then
+		echo "- [ERROR] PHP Socket not found! (/run/php/php$(conf_read php-ver)-fpm.sock)"
+		local ver_five_err="1"
+	fi
 fi
 if [[ $(conf_read mysql) == "true" ]] && ! systemctl is-active --quiet mysql; then
 	echo "- [ERROR] MySQL/MariaDB service not running!"
