external-db
External-DB improvements.
Support added to: clone-wp, replace-content, import-db, local-backup.

diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -1677,10 +1677,33 @@ database_import() {
 		echo "${red}[ERROR] Please, enter a valid file path!${end}"
 		exit 1
 	fi
+
+	if [[ -n $external_db ]]; then
+		check_for_mysql_client
+		local dbdata=${external_db:1:-1}
+		local uroot=$(echo "${dbdata}" | cut -d',' -f 1 -s)
+		local proot=$(echo "${dbdata}" | cut -d',' -f 2 -s)
+		local dbhost=$(echo "${dbdata}" | cut -d',' -f 3 -s)
+		local dburl=$(echo "$dbhost" | cut -f 1 -d ':')
+		local dbport=$(echo "$dbhost" | cut -f 2 -d ':' -s)
 	
-	local ADMIN_PASS=$( echo $(conf_read mysql-admin) | openssl enc -d -a -salt )
-	sudo mysql -u admin -p$ADMIN_PASS < $file
-	
-	echo "${gre}Database successfully imported!${end}"
+		if [[ $(echo "${external_db}" | cut -c-1) != "[" || $(echo "${external_db}" | rev | cut -c-1) != "]" || -z $uroot || -z $proot || -z $dburl || -z $dbport ]]; then
+			echo "${red}[ERROR] Invalid data for External Database!${end}"
+			exit 1
+		fi
+		
+		sudo mysql --connect-timeout=10 -h "$dburl" -P "$dbport" -u"$uroot" -p"$proot" < $file
+	else
+		check_for_mysql -ask
+		local ADMIN_PASS=$( echo $(conf_read mysql-admin) | openssl enc -d -a -salt )
+		sudo mysql -u admin -p$ADMIN_PASS < $file
+	fi
+
+	if [[ $? == 0 ]]; then
+		echo "${gre}Database successfully imported!${end}"
+	else
+		echo "${red}[ERROR] A connection can not be established with MySQL!${end}"
+		exit 1
+	fi	
 }
 
