db import
now we can import a database file into mysql

diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -1671,5 +1671,16 @@ dd_install() {
 }
 
 
-
+database_import() {
+	[[ -z $file ]] && read -p "${blu}SQL file path to import: ${end}" file
+	if [[ -z $file || ! -f $file ]]; then
+		echo "${red}[ERROR] Please, enter a valid file path!${end}"
+		exit 1
+	fi
+	
+	local ADMIN_PASS=$( echo $(conf_read mysql-admin) | openssl enc -d -a -salt )
+	sudo mysql -u admin -p$ADMIN_PASS < $file
+	
+	echo "${gre}Database successfully imported!${end}"
+}
 
