improvements
Purge support for external-db-save.
Duply profiles now have set max_fullbkp_age.
Verify process fixed.

diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -150,10 +150,6 @@ webinoly_verify() {
 			echo "[ERROR] File: /etc/nginx/nginx.conf not found!"
 			error="1"
 		fi
-		if [[ ! -f /etc/nginx/fastcgi.conf ]]; then
-			echo "[ERROR] File: /etc/nginx/fastcgi.conf not found!"
-			error="1"
-		fi
 	fi
 	if [[ $(conf_read nginx) != "true" ]]; then
 		if [[ -f /etc/nginx/nginx.conf ]]; then
@@ -351,11 +347,7 @@ webinoly_verify() {
 			echo "[ERROR] File: /usr/bin/duply not found!"
 			error="1"
 		fi
-		if [[ ! -L /usr/bin/letsencrypt ]]; then
-			echo "[ERROR] File: /usr/bin/letsencrypt not found!"
-			error="1"
-		fi
-		if [[ ! -f /usr/bin/certbot ]]; then
+		if [[ ! -L /usr/bin/certbot ]]; then
 			echo "[ERROR] File: /usr/bin/certbot not found!"
 			error="1"
 		fi
@@ -2049,46 +2041,54 @@ if (\$arg_${value}) {
 
 
 ext_db_save() {
-	if [[ $external_db_save == "true" ]]; then
-		read -p "${blu} Host: ${end}" host
-		read -p "${blu} User: ${end}" user
-		read -p "${blu} Password: ${end}" pass
-		
-		if [[ -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
-			echo "${red}[ERROR] Invalid data for External Database!${end}"
-			exit 1
-		fi
+	if [[ $external_db_save == "purge" || -n $purge ]]; then
+		conf_delete external-dbu
+		conf_delete external-dbp
+		conf_delete external-dbh
+		conf_delete external-dbx
+		echo "${gre}External DB data successfully removed!${end}"
 	else
-		# Prevent errors
-		if [[ ${#external_db_save} -lt 2 ]]; then
-			echo "${red}[ERROR] Invalid data for External Database!${end}"
+		if [[ $external_db_save == "true" ]]; then
+			read -p "${blu} Host: ${end}" host
+			read -p "${blu} User: ${end}" user
+			read -p "${blu} Password: ${end}" pass
+			
+			if [[ -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
+				echo "${red}[ERROR] Invalid data for External Database!${end}"
+				exit 1
+			fi
+		else
+			# Prevent errors
+			if [[ ${#external_db_save} -lt 2 ]]; then
+				echo "${red}[ERROR] Invalid data for External Database!${end}"
+				exit 1
+			fi
+			
+			local dbdata=${external_db_save:1:-1}
+			local user=$(echo "${dbdata}" | cut -d',' -f 1 -s)
+			local pass=$(echo "${dbdata}" | cut -d',' -f 2 -s)
+			local host=$(echo "${dbdata}" | cut -d',' -f 3 -s)
+			
+			if [[ $(echo "${external_db_save}" | cut -c-1) != "[" || $(echo "${external_db_save}" | rev | cut -c-1) != "]" || -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
+				echo "${red}[ERROR] Invalid data for External Database!${end}"
+				exit 1
+			fi
+		fi
+		
+		
+		is_url $host -split
+		if [[ -z $url_path && $(is_url $host) =~ ^(http|https|ip|true)$ && -n $url_host && -n $url_port ]]; then
+			conf_write external-dbh $url_host
+			conf_write external-dbx $url_port
+		else
+			echo "${red}[ERROR] Invalid database host/port!${end}"
 			exit 1
 		fi
 		
-		local dbdata=${external_db_save:1:-1}
-		local user=$(echo "${dbdata}" | cut -d',' -f 1 -s)
-		local pass=$(echo "${dbdata}" | cut -d',' -f 2 -s)
-		local host=$(echo "${dbdata}" | cut -d',' -f 3 -s)
+		conf_write external-dbu $user
+		conf_write external-dbp $( echo $pass | openssl enc -a -salt )
 		
-		if [[ $(echo "${external_db_save}" | cut -c-1) != "[" || $(echo "${external_db_save}" | rev | cut -c-1) != "]" || -z $host || -z $user || -z $pass || $user =~ [:]+ || $pass =~ [:]+ ]]; then
-			echo "${red}[ERROR] Invalid data for External Database!${end}"
-			exit 1
-		fi
+		echo "${gre}External DB data successfully saved!${end}"
 	fi
-	
-	
-	is_url $host -split
-	if [[ -z $url_path && $(is_url $host) =~ ^(http|https|ip|true)$ && -n $url_host && -n $url_port ]]; then
-		conf_write external-dbh $url_host
-		conf_write external-dbx $url_port
-	else
-		echo "${red}[ERROR] Invalid database host/port!${end}"
-		exit 1
-	fi
-	
-	conf_write external-dbu $user
-	conf_write external-dbp $( echo $pass | openssl enc -a -salt )
-	
-	echo "${gre}External DB data successfully saved!${end}"
 }
 
