aws iam roles
S3 backups now have support for IAM roles.

diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -1196,22 +1196,28 @@ aws_s3_credentials() {
 		cred=${aws_s3_credentials:1:-1}
 		user=$(echo "${cred}" | cut -d',' -f 1 -s)
 		pass=$(echo "${cred}" | cut -d',' -f 2 -s)
+	elif [[ $aws_s3_credentials == "awsiamrole" ]]; then
+		conf_write awsiamrole true
+		sudo rm -rf $HOME/.aws
 	else
 		echo "${red}[ERROR] Invalid AWS S3 Credentials!${end}"
 		exit 1
 	fi
 
-	if ! [[ -n $user && -n $pass ]]; then
-		echo "${red}[ERROR] Please, enter a valid AWS S3 Access and Secret Key!${end}"
-		exit 1
+	if [[ $aws_s3_credentials != "awsiamrole" ]]; then
+		if [[ -z $user || -z $pass ]]; then
+			echo "${red}[ERROR] Please, enter a valid AWS S3 Access and Secret Key!${end}"
+			exit 1
+		fi
+
+		sudo rm -rf $HOME/.aws/credentials
+		sudo mkdir -p $HOME/.aws
+		sudo touch $HOME/.aws/credentials
+		sudo echo "[default]
+aws_access_key_id = $user
+aws_secret_access_key = $pass" >> $HOME/.aws/credentials
 	fi
 
-	sudo rm -rf /root/.aws/credentials
-	sudo mkdir -p /root/.aws
-	sudo touch /root/.aws/credentials
-	sudo echo "[default]
-aws_access_key_id = $user
-aws_secret_access_key = $pass" >> /root/.aws/credentials
 	echo "${gre}AWS S3 Credentials successfully added!${end}"
 }
 
