cache control
Added support to cutomize Cache-Control HTTP Header.

diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -1511,6 +1511,53 @@ http_header_permission_policy() {
 }
 
 
+http_header_cache_control() {
+	if ! [[ $header_cache_control =~ ^(true|on|off|reset)$ ]]; then
+		echo "${red}[ERROR] Please, enter a valid option for Cache Control header!${end}"
+		exit 1
+	elif [[ $header_cache_control =~ ^(on|true)$ && ! -s /opt/webinoly/templates/source/cch_webinoly.data ]]; then
+		read -p "${blu}Cache Control header value: ${end}" cch_data
+		
+		if [[ -n $cch_data ]]; then
+			sudo touch /opt/webinoly/templates/source/cch_webinoly.data
+			sudo chmod 644 /opt/webinoly/templates/source/cch_webinoly.data
+			sudo chown -R root:root /opt/webinoly/templates/source/cch_webinoly.data
+			
+			echo "$cch_data" >> /opt/webinoly/templates/source/cch_webinoly.data
+			echo "${blu}${dim}Cache Control Header... saving data!${end}"
+		fi
+	elif [[ $header_cache_control =~ ^(true|on)$ && -s /opt/webinoly/templates/source/cch_webinoly.data ]]; then
+		echo "${blu}${dim}Recovering existing saved data for Cache Control!${end}"
+		cch_data=$(sed -n '1p' /opt/webinoly/templates/source/cch_webinoly.data)
+	fi
+	
+	if [[ $header_cache_control =~ ^(true|on)$ && -z $cch_data ]]; then
+		echo "${red}[ERROR] Invalid Cache Control header value!${end}"
+		exit 1
+	elif [[ $header_cache_control == "reset" ]]; then
+		sudo sed -i '/^add_header Cache-Control/s/^/#/' /etc/nginx/common/headers-html.conf
+		sudo rm -rf /opt/webinoly/templates/source/cch_webinoly.data
+		echo "${gre}Cache Control Header disabled and saved data successfully removed!${end}"
+	elif [[ $(conf_read nginx) == "true" ]]; then
+		if [[ $header_cache_control == "off" ]]; then
+			sudo sed -i '/^add_header Cache-Control/s/^/#/' /etc/nginx/common/headers-html.conf
+			echo "${gre}Cache Control Header successfully disabled!${end}"
+		elif [[ $header_cache_control =~ ^(true|on)$ ]]; then
+			sudo sed -Ei "/^#?add_header Cache-Control/d" /etc/nginx/common/headers-html.conf			
+			sudo echo "add_header Cache-Control \"${cch_data}\";" >> /etc/nginx/common/headers-html.conf
+			echo "${gre}Cache Control Header successfully configured!${end}"
+		fi
+	elif [[ $(conf_read nginx) != "true" ]]; then	
+		if [[ $header_cache_control == "off" ]]; then
+			echo "${red}[ERROR] NGINX is not installed!${end}"
+			exit 1
+		elif [[ $header_cache_control =~ ^(true|on)$ ]]; then
+			echo "${gre}Cache Control Header successfully configured and it will be used next time NGINX is installed!${end}"
+		fi
+	fi
+}
+
+
 ext_db_save() {
 	if [[ $external_db_save == "purge" || -n $purge ]]; then
 		conf_delete external-dbu
