update
Update process improved!

diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -264,6 +264,10 @@ create_blackhole_cert() {
 
 
 webinoly_update() {
+	# Update: sudo webinoly -update
+	# Update from branch: sudo webinoly -update=beta
+	# Downgrade: sudo webinoly -update=1.14.0
+	
 	if [[ $(conf_read branch) =~ ^(alpha|beta)$ ]] && ! [[ $update =~ ^(alpha|beta)$ ]]; then
 		echo "${red}[ERROR] Beta/alpha versions can not be updated to stable versions!${end}"
 		exit 1
@@ -275,12 +279,12 @@ webinoly_update() {
 		local branch="-ver=${update}"
 	else
 		local checkver=$(wget --timeout=10 -t 1 -qO- https://api.webinoly.com/check?text=true)
-		if [[ -n $checkver && -n $currentver && ${currentver//.} -ge ${checkver//.} ]]; then
+		if [[ -z $checkver || -z $currentver ]] || ! [[ $checkver =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+			echo "${red}[ERROR] Version check service unavailable!${dim} (Webinoly API)${end}"
+			exit 1
+		elif [[ ${currentver//.} -ge ${checkver//.} ]]; then
 			echo "${gre}You currently have the latest version!${dim} (v${checkver})${end}"
 			exit 0
-		elif [[ -z $checkver || -z $currentver ]]; then
-			echo "${red}[ERROR] Version number unavailable!${end}"
-			exit 1
 		else
 			echo "${dim}Updating...${end}"
 			echo "${blu}${dim}Your current version 'v${currentver}' will be updated to the newest 'v${checkver}' ${end}"
@@ -289,7 +293,14 @@ webinoly_update() {
 	
 	sudo wget --timeout=15 -t 1 --referer="https://update.webinoly.com/?ver=${app_version}" -qrO weby https://qrok.es/wyupd && sudo bash weby upd $branch
 	
-	[[ $? == 0 ]] && echo "${gre}Webinoly App has been updated successfully!${dim} (Updated to: v$(conf_read app-version))${end}"
+	if [[ $? == 0 ]]; then
+		echo "${gre}Webinoly App has been updated successfully!${dim} (Updated to: v$(conf_read app-version))${end}"
+	else
+		sudo rm weby
+		echo "${red}[ERROR] Update process has failed!${end}"
+		exit 1
+	fi
+		
 	api-events_update wy1s
 }
 
