x-headers
Addes support to customize X-Headers: X-Frame-Options, X-Content-Type-Options, X-XSS-Protection

diff --git a/lib/webin b/lib/webin
--- a/lib/webin
+++ b/lib/webin
@@ -1582,16 +1582,16 @@ http_header_robots() {
 		echo "${red}[ERROR] Invalid X-Robots-Tag header value!${end}"
 		exit 1
 	elif [[ $header_robots == "reset" ]]; then
-		sudo sed -i '/^add_header X-Robots-Tag/s/^/#/' /etc/nginx/common/headers-html.conf
+		sudo sed -i '/^add_header X-Robots-Tag/s/^/#/' /etc/nginx/common/headers-http.conf
 		sudo rm -rf /opt/webinoly/templates/source/rob_webinoly.data
 		echo "${gre}X-Robots-Tag Header disabled and saved data successfully removed!${end}"
 	elif [[ $(conf_read nginx) == "true" ]]; then
 		if [[ $header_robots == "off" ]]; then
-			sudo sed -i '/^add_header X-Robots-Tag/s/^/#/' /etc/nginx/common/headers-html.conf
+			sudo sed -i '/^add_header X-Robots-Tag/s/^/#/' /etc/nginx/common/headers-http.conf
 			echo "${gre}X-Robots-Tag Header successfully disabled!${end}"
 		elif [[ $header_robots =~ ^(true|on)$ ]]; then
-			sudo sed -Ei "/^#?add_header X-Robots-Tag/d" /etc/nginx/common/headers-html.conf			
-			sudo echo "add_header X-Robots-Tag \"${rob_data}\";" >> /etc/nginx/common/headers-html.conf
+			sudo sed -Ei "/^#?add_header X-Robots-Tag/d" /etc/nginx/common/headers-http.conf			
+			sudo echo "add_header X-Robots-Tag \"${rob_data}\";" >> /etc/nginx/common/headers-http.conf
 			echo "${gre}X-Robots-Tag Header successfully configured!${end}"
 		fi
 	elif [[ $(conf_read nginx) != "true" ]]; then	
@@ -1600,6 +1600,103 @@ http_header_robots() {
 			exit 1
 		elif [[ $header_robots =~ ^(true|on)$ ]]; then
 			echo "${gre}X-Robots-Tag Header successfully configured and it will be used next time NGINX is installed!${end}"
+		fi
+	fi
+}
+
+
+http_header_xssp() {
+	if ! [[ $header_xssp =~ ^(on|off)$ ]]; then
+		echo "${red}[ERROR] Please, enter a valid option for X-XSS-Protection header!${end}"
+		exit 1
+	fi
+	
+	if [[ $(conf_read nginx) == "true" ]]; then
+		if [[ $header_xssp == "off" ]]; then
+			conf_write header-xssp false
+			sudo sed -i '/^add_header X-XSS-Protection/s/^/#/' /etc/nginx/common/headers-http.conf
+			echo "${gre}X-XSS-Protection Header successfully disabled!${end}"
+		elif [[ $header_xssp == "on" ]]; then
+			conf_delete header-xssp
+			sudo sed -Ei "/^#?add_header X-XSS-Protection/d" /etc/nginx/common/headers-http.conf			
+			sudo echo "add_header X-XSS-Protection \"1; mode=block\";" >> /etc/nginx/common/headers-http.conf
+			echo "${gre}X-XSS-Protection Header successfully configured!${end}"
+		fi
+	elif [[ $(conf_read nginx) != "true" ]]; then	
+		if [[ $header_xssp == "off" ]]; then
+			conf_write header-xssp false
+			echo "${gre}X-XSS-Protection Header successfully configured and it will be disabled next time NGINX is installed!${end}"
+		elif [[ $header_xssp == "on" ]]; then
+			conf_delete header-xssp
+			echo "${gre}X-XSS-Protection Header successfully configured and it will be used next time NGINX is installed!${end}"
+		fi
+	fi
+}
+
+
+http_header_xcto() {
+	if ! [[ $header_xcto =~ ^(on|off)$ ]]; then
+		echo "${red}[ERROR] Please, enter a valid option for X-Content-Type-Options header!${end}"
+		exit 1
+	fi
+	
+	if [[ $(conf_read nginx) == "true" ]]; then
+		if [[ $header_xcto == "off" ]]; then
+			conf_write header-xcto false
+			sudo sed -i '/^add_header X-Content-Type-Options/s/^/#/' /etc/nginx/common/headers-http.conf
+			echo "${gre}X-Content-Type-Options Header successfully disabled!${end}"
+		elif [[ $header_xcto == "on" ]]; then
+			conf_delete header-xcto
+			sudo sed -Ei "/^#?add_header X-Content-Type-Options/d" /etc/nginx/common/headers-http.conf			
+			sudo echo "add_header X-Content-Type-Options nosniff;" >> /etc/nginx/common/headers-http.conf
+			echo "${gre}X-Content-Type-Options Header successfully configured!${end}"
+		fi
+	elif [[ $(conf_read nginx) != "true" ]]; then	
+		if [[ $header_xcto == "off" ]]; then
+			conf_write header-xcto false
+			echo "${gre}X-Content-Type-Options Header successfully configured and it will be disabled next time NGINX is installed!${end}"
+		elif [[ $header_xcto == "on" ]]; then
+			conf_delete header-xcto
+			echo "${gre}X-Content-Type-Options Header successfully configured and it will be used next time NGINX is installed!${end}"
+		fi
+	fi
+}
+
+
+http_header_xfo() {
+	if ! [[ $header_xfo =~ ^(off|deny|sameorigin|allow-from)$ ]]; then
+		echo "${red}[ERROR] Please, enter a valid option for X-Frame-Options header!${end}"
+		exit 1
+	fi
+	
+	local param="${header_xfo^^}"
+	if [[ $header_xfo == "allow-from" ]]; then
+		[[ -z $url ]] && read -p "${blu}Allow-From URL: ${end}" url
+		if [[ -z $url ]] || ! [[ $(is_url $url) =~ ^(http|https|ip|true)$ ]]; then
+			echo "${red}[ERROR] Invalid URL!${end}"
+			exit 1
+		fi
+		local param="\"${header_xfo^^} $url\""
+		conf_write header-xfo-url $url
+	else
+		conf_delete header-xfo-url
+	fi
+	conf_write header-xfo $header_xfo
+	
+	if [[ $(conf_read nginx) == "true" ]]; then
+		if [[ $header_xfo == "off" ]]; then
+			sudo sed -i '/^add_header X-Frame-Options/s/^/#/' /etc/nginx/common/headers-http.conf
+			echo "${gre}X-Frame-Options Header successfully disabled!${end}"
+		elif [[ $header_xfo =~ ^(deny|sameorigin|allow-from)$ ]]; then
+			sudo sed -Ei "/^#?add_header X-Frame-Options/d" /etc/nginx/common/headers-http.conf			
+			sudo echo "add_header X-Frame-Options ${param};" >> /etc/nginx/common/headers-http.conf
+			echo "${gre}X-Frame-Options Header successfully configured!${end}"
+		fi
+	elif [[ $(conf_read nginx) != "true" ]]; then	
+		if [[ $header_xfo == "off" ]]; then
+			echo "${gre}X-Frame-Options Header successfully configured and it will be disabled next time NGINX is installed!${end}"
+		elif [[ $header_xfo =~ ^(deny|sameorigin|allow-from)$ ]]; then
+			echo "${gre}X-Frame-Options Header successfully configured and it will be used next time NGINX is installed!${end}"
 		fi
 	fi
 }
